import gzip
import json
import os
import tempfile

from django.conf import settings
from django.core.management import call_command
from django.core.management.base import BaseCommand, CommandError

from apps.accounts.models import Staff
from apps.job.models import JobFile


class Command(BaseCommand):
    help = "Restore data from backup with cleanup"

    # WARNING: This command may not work correctly if the data model has changed
    # significantly since the backup was created. Any changes result in falures and
    # you should use the manual SQL-based process documented in
    # docs/backup-restore-process.md instead.

    def add_arguments(self, parser):
        parser.add_argument(
            "backup_file", type=str, help="Path to the backup JSON file"
        )
        parser.add_argument(
            "--skip-cleanup", action="store_true", help="Skip clearing existing data"
        )

    # Records to filter from backup before loading.
    # These are framework tables regenerated by `manage.py migrate`.
    SKIP_MODELS = {"migrations.migration", "contenttypes.contenttype"}

    def handle(self, *args, **options):
        # Production safety check - absolutely prevent running in production
        if not settings.DEBUG:
            raise CommandError(
                "This command is DISABLED in production to prevent data loss. "
                "It would wipe your entire database. Use proper database restoration "
                "tools for production environments."
            )

        backup_file = options["backup_file"]
        skip_cleanup = options["skip_cleanup"]

        if not skip_cleanup:
            self.stdout.write("Clearing existing data...")
            call_command("flush", "--noinput")

            # Load essential company configuration
            self.stdout.write("Loading essential company configuration...")
            call_command("loaddata", "apps/workflow/fixtures/company_defaults.json")

        # Truncate content types to avoid PK conflicts with backup data
        from django.db import connection

        with connection.cursor() as cursor:
            if connection.vendor == "mysql":
                cursor.execute("SET FOREIGN_KEY_CHECKS=0")
                cursor.execute("TRUNCATE TABLE django_content_type")
                cursor.execute("SET FOREIGN_KEY_CHECKS=1")
            else:
                cursor.execute("TRUNCATE django_content_type CASCADE")

        # Read backup (handles both .gz and .json)
        if backup_file.endswith(".gz"):
            with gzip.open(backup_file, "rt", encoding="utf-8") as gz_file:
                json_data = json.loads(gz_file.read())
        else:
            with open(backup_file, "r", encoding="utf-8") as f:
                json_data = json.load(f)

        # Filter records that can't or shouldn't be loaded
        filtered_data = self._filter_backup_data(json_data)

        # Write filtered data to temp file and load
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".json", delete=False
        ) as temp_file:
            json.dump(filtered_data, temp_file, indent=2, ensure_ascii=False)
            temp_file_path = temp_file.name

        # Disable FK constraint checking during load — the subset backup
        # doesn't include all referenced models (e.g. XeroPayItem).
        # Production migration uses full dumpdata so doesn't need this.
        # Django's loaddata calls connection.check_constraints() after loading,
        # which does a Python-level FK check independent of MySQL's
        # FOREIGN_KEY_CHECKS setting. We temporarily replace it with a no-op.
        self.stdout.write(f"Loading data from {backup_file}...")
        original_check = connection.check_constraints
        connection.check_constraints = lambda **kwargs: None

        with connection.cursor() as cursor:
            if connection.vendor == "mysql":
                cursor.execute("SET FOREIGN_KEY_CHECKS=0")

        try:
            call_command("loaddata", temp_file_path)
        finally:
            connection.check_constraints = original_check
            with connection.cursor() as cursor:
                if connection.vendor == "mysql":
                    cursor.execute("SET FOREIGN_KEY_CHECKS=1")
            os.unlink(temp_file_path)

        self.stdout.write("Running post-restore fixes...")
        self.post_restore_fixes()

    def _filter_backup_data(self, json_data):
        """Filter records that can't be loaded by Django's deserializer."""
        skip_count = {}
        filtered = []

        for item in json_data:
            model = item["model"]

            # Skip framework tables (regenerated by migrate)
            if model in self.SKIP_MODELS:
                skip_count[model] = skip_count.get(model, 0) + 1
                continue

            filtered.append(item)

        for model, count in sorted(skip_count.items()):
            self.stdout.write(f"  Filtered {count} {model} records")

        return filtered

    def post_restore_fixes(self):
        # Create dummy files for JobFile instances
        self.stdout.write("Creating dummy files for JobFile instances...")
        for job_file in JobFile.objects.filter(file_path__isnull=False).exclude(
            file_path=""
        ):
            dummy_path = os.path.join(settings.MEDIA_ROOT, str(job_file.file_path))
            os.makedirs(os.path.dirname(dummy_path), exist_ok=True)
            with open(dummy_path, "w") as f:
                f.write(f"Dummy file for JobFile {job_file.pk}\n")
                f.write(f"Original path: {job_file.file_path}\n")
            self.stdout.write(f"Created dummy file: {dummy_path}")

        # Create default admin if needed
        self.stdout.write("Creating default admin user...")
        admin_user, created = Staff.objects.get_or_create(
            email="defaultadmin@example.com",
            defaults={
                "first_name": "Default",
                "last_name": "Admin",
                "preferred_name": None,
                "wage_rate": "40.00",
                "hours_mon": "8.0",
                "hours_tue": "8.0",
                "hours_wed": "8.0",
                "hours_thu": "8.0",
                "hours_fri": "8.0",
                "hours_sat": "0.00",
                "hours_sun": "0.00",
                "is_office_staff": True,
                "is_superuser": True,
                "password": (
                    "pbkdf2_sha256$870000$5Nw3RUuFaZZPCkeyVOm4kx$"
                    "Attep1SqGF6ymdwm44LOte4wwszqte0W5ey3xcENFAI="
                ),
                "date_joined": "2024-01-01T00:00:00Z",
                "created_at": "2024-01-01T00:00:00Z",
                "updated_at": "2024-01-01T00:00:00Z",
            },
        )

        if created:
            self.stdout.write(
                self.style.SUCCESS("Created defaultadmin@example.com user")
            )
        else:
            self.stdout.write(
                self.style.SUCCESS("defaultadmin@example.com user already exists")
            )

        self.stdout.write(self.style.SUCCESS("Post-restore fixes completed"))
