"""Record v1's operation surface once, so the port's progress count needs no v1.

v1 is frozen for the remainder of the port, so what its API offered and what its
frontend actually called are constants. Recording them lets
`scripts.checks.status_table` derive "how much is left" from v2's live schema
alone — which is the only way that count can be gated, because CI checks out
this repo and nothing else (`.github/workflows/ci.yml` has one `actions/checkout`
and no submodules), so `../docketworks` does not exist there.

This is a WORK LIST, not a contract authority. It records which operation names
v1's frontend called; it never says what shape v2 must serve. That distinction
is the whole reason the parity ratchet was deleted in 5cefdc5 — it failed builds
when v2's shapes diverged from v1's, which preserved the mistake v2 exists to
correct. Nothing here can fail a build for being *different* from v1; porting an
operation only ever makes the remaining count fall.

Run once, from a checkout with v1 beside it, and commit the output:

    uv run python -m scripts.generate.gen_v1_operations

Re-run it only if v1 ships new frontend call sites, which it should not.
"""

import re
from pathlib import Path

import yaml

from scripts import REPO_ROOT

V1_REPO = REPO_ROOT.parent / "docketworks"
V1_SCHEMA = V1_REPO / "frontend" / "schema.yml"
V1_FRONTEND_SRC = V1_REPO / "frontend" / "src"

OUTPUT_PATH = REPO_ROOT / "scripts" / "v1-frontend-operations.yml"

OPERATION_ID = re.compile(r"operationId:\s*(\S+)")
# v1's frontend reaches the generated client exclusively as `api.<operationId>`
# (its ADR 0021 equivalent), so call sites are found by name rather than by
# tracing imports.
API_CALL = re.compile(r"\bapi\.([A-Za-z0-9_]+)")

CALL_SITE_SUFFIXES = (".ts", ".vue")

HEADER = """\
# v1's operation surface, recorded 2026-08-08 and frozen.
#
# GENERATED by scripts/generate/gen_v1_operations.py. Do not hand-edit the two
# lists; do hand-edit `renamed` when v2 deliberately renames an operation.
#
# WHY THIS EXISTS: the remaining-work count has to be derivable in CI, and CI
# checks out only this repo -- ../docketworks is not there. v1 is frozen, so its
# totals are constants and can simply be stored.
#
# WHAT THIS IS NOT: an authority on v2's contract. It records which operation
# NAMES v1's frontend called, never what shape v2 must serve. Commit 5cefdc5
# deleted the parity ratchet precisely because that gate treated v1 as
# authoritative and so preserved the design v2 exists to replace. Nothing here
# can fail a build because v2 differs from v1.
#
# `renamed` maps a v1 operationId to the v2 one that replaced it, and means
# "this IS ported, under a new name". Without the entry the v1 name reads as
# still unported while the v2 name looks like a brand-new endpoint, so a single
# unrecorded rename corrupts the count in both directions at once. Expect it to
# grow: export_openapi.py pins dissolved v1 app names at zero, so every called
# `workflow_*` operation must be renamed when it ports.
#
# `introduced` lists v2 operations that never existed in v1. Both keys are
# hand-maintained and survive regeneration; the two lists do not.
"""


def _operation_ids(schema: Path) -> list[str]:
    return sorted(set(OPERATION_ID.findall(schema.read_text())))


def _called_operation_ids(src: Path, known: set[str]) -> list[str]:
    called: set[str] = set()
    for path in src.rglob("*"):
        if path.suffix not in CALL_SITE_SUFFIXES or "generated" in str(path):
            continue
        called |= set(API_CALL.findall(path.read_text(errors="ignore")))
    # `api.<something>` also matches helpers that are not operations; keeping
    # only known ids is what makes the count meaningful rather than approximate.
    return sorted(called & known)


def main() -> int:
    if not V1_SCHEMA.is_file():
        raise RuntimeError(
            f"v1 schema not found at {V1_SCHEMA}. This generator runs only on a machine "
            "with the v1 repo checked out beside this one; its committed output is what "
            "CI reads."
        )

    operations = _operation_ids(V1_SCHEMA)
    called = _called_operation_ids(V1_FRONTEND_SRC, set(operations))

    spec_files = len(list((V1_REPO / "frontend" / "tests").rglob("*.spec.ts")))

    # Hand-maintained keys survive regeneration: `renamed` and `introduced` record
    # v2 decisions, which reading v1 can never recover.
    existing = yaml.safe_load(OUTPUT_PATH.read_text()) if OUTPUT_PATH.is_file() else None
    renamed = (existing or {}).get("renamed") or {}
    introduced = (existing or {}).get("introduced") or []
    dropped = (existing or {}).get("dropped") or {}

    body = yaml.safe_dump(
        {
            "e2e_spec_files": spec_files,
            "operations": operations,
            "called": called,
            "renamed": renamed,
            "introduced": introduced,
            "dropped": dropped,
        },
        sort_keys=False,
        default_flow_style=False,
        width=100,
    )
    OUTPUT_PATH.write_text(HEADER + body)

    print(
        f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}: {len(operations)} operations, "
        f"{len(called)} called, {len(renamed)} renamed, {spec_files} v1 spec files"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
