# Generated by Django 6.0.7 on 2026-08-01 10:23

import uuid

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("job", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("po_number", models.CharField(max_length=50, unique=True)),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Optional reference for the purchase order",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("order_date", models.DateField(default=django.utils.timezone.now)),
                ("expected_delivery", models.DateField(blank=True, null=True)),
                ("xero_id", models.UUIDField(blank=True, null=True, unique=True)),
                (
                    "xero_tenant_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted to Supplier"),
                            ("partially_received", "Partially Received"),
                            ("fully_received", "Fully Received"),
                            ("deleted", "Deleted"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("xero_last_modified", models.DateTimeField(blank=True, null=True)),
                (
                    "xero_last_synced",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ("online_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "raw_json",
                    models.JSONField(
                        blank=True,
                        help_text="Raw JSON data from Xero for this purchase order",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who created this purchase order",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_purchase_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary job this PO is for",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="job.job",
                    ),
                ),
                (
                    "pickup_address",
                    models.ForeignKey(
                        blank=True,
                        help_text="Delivery/pickup address for this purchase order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_orders",
                        to="company.supplierpickupaddress",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="company.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrderEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("description", models.TextField()),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="purchasing.purchaseorder",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "dimensions",
                    models.CharField(
                        blank=True,
                        help_text="Dimensions such as length, width, height, etc.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "price_tbc",
                    models.BooleanField(
                        default=False,
                        help_text="If true, the price is to be confirmed and unit cost will be None",
                    ),
                ),
                (
                    "supplier_item_code",
                    models.CharField(
                        blank=True,
                        help_text="Supplier's own item code/SKU",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "item_code",
                    models.CharField(
                        blank=True,
                        help_text="Internal item code for Xero integration",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "received_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total quantity received against this line",
                        max_digits=10,
                    ),
                ),
                (
                    "metal_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("stainless_steel", "Stainless Steel"),
                            ("mild_steel", "Mild Steel"),
                            ("aluminium", "Aluminium"),
                            ("brass", "Brass"),
                            ("copper", "Copper"),
                            ("titanium", "Titanium"),
                            ("zinc", "Zinc"),
                            ("galvanized", "Galvanized"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "alloy",
                    models.CharField(
                        blank=True,
                        help_text="Alloy specification (e.g., 304, 6061)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "specifics",
                    models.CharField(
                        blank=True,
                        help_text="Specific details (e.g., m8 countersunk socket screw)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Where this item will be stored",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "raw_line_data",
                    models.JSONField(
                        blank=True,
                        help_text="Raw JSON data from the source system or document",
                        null=True,
                    ),
                ),
                (
                    "xero_line_item_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Xero's unique identifier for this line item (from line_item_id)",
                        null=True,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        help_text="The job this purchase line is for",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_order_lines",
                        to="job.job",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="po_lines",
                        to="purchasing.purchaseorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrderSupplierQuote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "extracted_data",
                    models.JSONField(
                        blank=True, help_text="Extracted data from the quote", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("deleted", "Deleted")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "purchase_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_quote",
                        to="purchasing.purchaseorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_code",
                    models.CharField(
                        blank=True,
                        help_text="Xero Item Code",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(help_text="Description of the stock item", max_length=255),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Current quantity of the stock item",
                        max_digits=10,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per unit of the stock item",
                        max_digits=10,
                    ),
                ),
                (
                    "unit_revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Revenue per unit (what customer pays)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date the stock item was created",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("purchase_order", "Purchase Order Receipt"),
                            ("split_from_stock", "Split/Offcut from Stock"),
                            ("manual", "Manual Adjustment/Stocktake"),
                            ("product_catalog", "Product Catalog"),
                        ],
                        help_text="Origin of this stock item",
                        max_length=50,
                    ),
                ),
                (
                    "active_source_purchase_order_line_id",
                    models.UUIDField(
                        blank=True,
                        editable=False,
                        help_text="Denormalized pointer used to enforce single active stock item per purchase order line.",
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.TextField(blank=True, help_text="Where we are keeping this", null=True),
                ),
                (
                    "metal_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("stainless_steel", "Stainless Steel"),
                            ("mild_steel", "Mild Steel"),
                            ("aluminium", "Aluminium"),
                            ("brass", "Brass"),
                            ("copper", "Copper"),
                            ("titanium", "Titanium"),
                            ("zinc", "Zinc"),
                            ("galvanized", "Galvanized"),
                            ("other", "Other"),
                        ],
                        help_text="Type of metal",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "alloy",
                    models.CharField(
                        blank=True,
                        help_text="Alloy specification (e.g., 304, 6061)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "specifics",
                    models.CharField(
                        blank=True,
                        help_text="Specific details (e.g., m8 countersunk socket screw)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False when quantity reaches zero or item is fully consumed/transformed",
                    ),
                ),
                (
                    "xero_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique ID from Xero for this item",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "xero_last_modified",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last modified date from Xero for this item",
                        null=True,
                    ),
                ),
                (
                    "xero_last_synced",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this item was last synced with Xero (None = never synced)",
                        null=True,
                    ),
                ),
                (
                    "raw_json",
                    models.JSONField(
                        blank=True,
                        help_text="Raw JSON data from Xero for this item",
                        null=True,
                    ),
                ),
                (
                    "xero_inventory_tracked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item is inventory-tracked in Xero",
                    ),
                ),
                (
                    "parser_attempted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this inventory item was last attempted by the LLM parser",
                        null=True,
                    ),
                ),
                (
                    "parsed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this inventory item was parsed by LLM",
                        null=True,
                    ),
                ),
                (
                    "parser_version",
                    models.CharField(
                        blank=True,
                        help_text="Version of parser used for this data",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "parser_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Parser confidence score 0.00-1.00",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Auto-bumped on every save(); feeds the /api/data-versions/ freshness signal so the frontend stockStore can detect catalogue changes (e.g. Xero unit_cost updates) and refetch.",
                        null=True,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        help_text="The job this stock item is assigned to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_items",
                        to="job.job",
                    ),
                ),
                (
                    "source_parent_stock",
                    models.ForeignKey(
                        blank=True,
                        help_text="The parent stock item this was split from (if source='split_from_stock')",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_stock_splits",
                        to="purchasing.stock",
                    ),
                ),
                (
                    "source_purchase_order_line",
                    models.ForeignKey(
                        blank=True,
                        help_text="The PO line this stock originated from (if source='purchase_order')",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_generated",
                        to="purchasing.purchaseorderline",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="purchaseorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("online_url", ""), _negated=True),
                name="purchasing_purchaseorder_online_url_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("reference", ""), _negated=True),
                name="reference_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("xero_tenant_id", ""), _negated=True),
                name="purchasing_purchaseorder_xero_tenant_id_not_blank",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorderevent",
            index=models.Index(
                fields=["purchase_order", "-timestamp"], name="poevent_po_timestamp_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("alloy", ""), _negated=True),
                name="purchasing_purchaseorderline_alloy_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("dimensions", ""), _negated=True),
                name="dimensions_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("item_code", ""), _negated=True),
                name="purchasing_purchaseorderline_item_code_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("location", ""), _negated=True),
                name="purchasing_purchaseorderline_location_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("metal_type", ""), _negated=True),
                name="purchasing_purchaseorderline_metal_type_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("specifics", ""), _negated=True),
                name="purchasing_purchaseorderline_specifics_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("supplier_item_code", ""), _negated=True),
                name="supplier_item_code_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseordersupplierquote",
            constraint=models.CheckConstraint(
                condition=models.Q(("mime_type", ""), _negated=True),
                name="purchasing_purchaseordersupplierquote_mime_type_not_blank",
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.CombinedSearchVector(
                        django.contrib.postgres.search.CombinedSearchVector(
                            django.contrib.postgres.search.CombinedSearchVector(
                                django.contrib.postgres.search.CombinedSearchVector(
                                    django.contrib.postgres.search.SearchVector(
                                        "description", config="english", weight="A"
                                    ),
                                    "||",
                                    django.contrib.postgres.search.SearchVector(
                                        "item_code", config="english", weight="A"
                                    ),
                                    django.contrib.postgres.search.SearchConfig("english"),
                                ),
                                "||",
                                django.contrib.postgres.search.SearchVector(
                                    "metal_type", config="english", weight="B"
                                ),
                                django.contrib.postgres.search.SearchConfig("english"),
                            ),
                            "||",
                            django.contrib.postgres.search.SearchVector(
                                "alloy", config="english", weight="B"
                            ),
                            django.contrib.postgres.search.SearchConfig("english"),
                        ),
                        "||",
                        django.contrib.postgres.search.SearchVector(
                            "specifics", config="english", weight="B"
                        ),
                        django.contrib.postgres.search.SearchConfig("english"),
                    ),
                    "||",
                    django.contrib.postgres.search.SearchVector(
                        "location", config="english", weight="C"
                    ),
                    django.contrib.postgres.search.SearchConfig("english"),
                ),
                name="stock_fts_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.UniqueConstraint(fields=("xero_id",), name="unique_xero_id_stock"),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.UniqueConstraint(
                fields=("active_source_purchase_order_line_id",),
                name="unique_active_stock_per_po_line",
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.CheckConstraint(
                condition=models.Q(("alloy", ""), _negated=True),
                name="purchasing_stock_alloy_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.CheckConstraint(
                condition=models.Q(("item_code", ""), _negated=True),
                name="purchasing_stock_item_code_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.CheckConstraint(
                condition=models.Q(("location", ""), _negated=True),
                name="purchasing_stock_location_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.CheckConstraint(
                condition=models.Q(("metal_type", ""), _negated=True),
                name="purchasing_stock_metal_type_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.CheckConstraint(
                condition=models.Q(("parser_version", ""), _negated=True),
                name="purchasing_stock_parser_version_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.CheckConstraint(
                condition=models.Q(("specifics", ""), _negated=True),
                name="purchasing_stock_specifics_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.CheckConstraint(
                condition=models.Q(("xero_id", ""), _negated=True),
                name="purchasing_stock_xero_id_not_blank",
            ),
        ),
    ]
