# Generated by Django 6.1.1 on 2026-09-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="xero_status",
            field=models.CharField(
                blank=True,
                help_text="Xero's own word for this order (DRAFT, SUBMITTED, AUTHORISED, BILLED, VOIDED). Separate from `status` because that one answers a different question: whether the goods arrived and were costed to a job, which only Docketworks knows. Xero saying BILLED used to set status=fully_received, marking material received that nobody had receipted.",
                max_length=20,
                null=True,
            ),
        ),
    ]
