# Generated by Django 6.1.1 on 2026-09-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0002_purchaseorder_xero_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="xero_last_pushed",
            field=models.DateTimeField(
                blank=True,
                help_text="When our copy of this order last reached Xero. Distinct from xero_last_synced, which records when we last LOOKED at Xero and is written on every inbound sync — one column cannot answer both questions, and using it for both hides an outstanding send behind the next pull.",
                null=True,
            ),
        ),
    ]
