# Generated by Django 6.1.1 on 2026-09-05 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
        ("job", "0004_costline_managed_by_and_more"),
        ("purchasing", "0004_rename_xero_last_pushed_xero_agreed_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="xero_agreed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When our copy of this order and Xero's were last known to match — either because we sent ours or because we took theirs. Distinct from xero_last_synced, which records when we last LOOKED at Xero and is written on every inbound sync, so it hides an outstanding send behind the next pull. It is also why updated_at cannot answer this: updated_at is the row's ETag and must advance whenever the row changes, including when the change came FROM Xero.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("xero_status", ""), _negated=True),
                name="purchasing_purchaseorder_xero_status_not_blank",
            ),
        ),
    ]
