# Generated by Django 6.1.1 on 2026-09-07 00:50

import uuid

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0007_complete_quote_chat_storage"),
        ("purchasing", "0005_purchaseorder_xero_status_not_blank"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quantity_change", models.DecimalField(decimal_places=3, max_digits=11)),
                ("quantity_before", models.DecimalField(decimal_places=3, max_digits=11)),
                ("quantity_after", models.DecimalField(decimal_places=3, max_digits=11)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("opening", "Opening balance"),
                            ("receipt", "Receipt"),
                            ("receipt_reversal", "Receipt reversal"),
                            ("issue", "Job issue"),
                            ("return", "Job return"),
                            ("stocktake", "Stocktake"),
                        ],
                        max_length=25,
                    ),
                ),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reason", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Stocktake",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="StocktakeConfiguration",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StocktakeLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("location", models.TextField(blank=True, null=True)),
                ("expected_quantity", models.DecimalField(decimal_places=3, max_digits=11)),
                ("expected_version", models.PositiveBigIntegerField()),
                (
                    "counted_quantity",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True),
                ),
                ("counted_at", models.DateTimeField(blank=True, null=True)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="stock",
            name="unique_active_stock_per_po_line",
        ),
        migrations.AddField(
            model_name="stock",
            name="inventory_version",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stock",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3, help_text="Current quantity of the stock item", max_digits=11
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="cost_line",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="job.costline",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="counterpart_job",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="job.job"
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="reverses",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="purchasing.stockmovement",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="purchasing.stock",
            ),
        ),
        migrations.AddField(
            model_name="stocktake",
            name="adjustment_job",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="job.job"),
        ),
        migrations.AddField(
            model_name="stocktake",
            name="corrects",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correction",
                to="purchasing.stocktake",
            ),
        ),
        migrations.AddField(
            model_name="stocktake",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="stocktake",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posted_stocktakes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stocktakeconfiguration",
            name="adjustment_job",
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="job.job"),
        ),
        migrations.AddField(
            model_name="stocktakeline",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="purchasing.stock",
            ),
        ),
        migrations.AddField(
            model_name="stocktakeline",
            name="stocktake",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="purchasing.stocktake",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="stocktake_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="purchasing.stocktakeline",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktakeline",
            constraint=models.UniqueConstraint(
                fields=("stocktake", "stock"), name="stocktake_unique_stock"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktakeline",
            constraint=models.CheckConstraint(
                condition=models.Q(("counted_quantity__gte", 0)), name="count_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktakeline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_cost__gte", 0)), name="count_cost_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "quantity_after",
                        django.db.models.expressions.CombinedExpression(
                            models.F("quantity_before"), "+", models.F("quantity_change")
                        ),
                    )
                ),
                name="movement_balance_equation",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind__in", ["opening", "receipt", "receipt_reversal"]),
                    ("counterpart_job__isnull", False),
                    _connector="OR",
                ),
                name="movement_job_counterpart",
            ),
        ),
    ]
