# Generated by Django 6.0.7 on 2026-07-27 21:58

"""Make Stock.location nullable so location has one spelling of "unset".

PurchaseOrderLine.location was already `null=True, blank=True` while
Stock.location was NOT NULL with blank=True, so the same concept used NULL
in one table and "" in the other. NULL wins, per the rule in CLAUDE.md.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0005_metal_type_null_is_unset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="location",
            field=models.TextField(
                blank=True, help_text="Where we are keeping this", null=True
            ),
        ),
        migrations.RunSQL(
            sql="UPDATE purchasing_stock SET location = NULL WHERE location = ''",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE purchasing_stock "
                "ADD CONSTRAINT location_not_blank CHECK (location <> '')"
            ),
            reverse_sql=(
                "ALTER TABLE purchasing_stock "
                "DROP CONSTRAINT IF EXISTS location_not_blank"
            ),
        ),
    ]
