# Generated by Django 6.1.1 on 2026-09-07 01:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0007_inventory_openings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="active_source_purchase_order_line_id",
        ),
    ]
