# Generated by Django 6.1.1 on 2026-09-07 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0008_alter_costline_managed_by"),
        ("purchasing", "0009_protect_posted_stocktake"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stockmovement",
            name="movement_job_counterpart",
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="opening_quantity",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="kind",
            field=models.CharField(
                choices=[
                    ("opening", "Opening balance"),
                    ("job_opening", "Job position at cutover"),
                    ("receipt", "Receipt"),
                    ("receipt_opening", "Received allocation at cutover"),
                    ("receipt_reversal", "Receipt reversal"),
                    ("issue", "Job issue"),
                    ("return", "Job return"),
                    ("stocktake", "Stocktake"),
                ],
                max_length=25,
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind__in", ["opening", "receipt", "receipt_opening", "receipt_reversal"]),
                    ("counterpart_job__isnull", False),
                    _connector="OR",
                ),
                name="movement_job_counterpart",
            ),
        ),
    ]
