# Generated by Django 6.1.1 on 2026-09-07 23:06

import django.db.models.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0008_alter_costline_managed_by"),
        ("purchasing", "0011_backfill_job_openings"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE purchasing_stock s SET is_active = FALSE
            WHERE s.quantity = 0
              AND EXISTS (SELECT 1 FROM purchasing_stockmovement m
                          WHERE m.stock_id = s.id AND m.kind = 'receipt_opening')
              AND NOT EXISTS (SELECT 1 FROM purchasing_stockmovement m
                              WHERE m.stock_id = s.id AND m.kind IN ('opening', 'receipt'));
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveConstraint(
            model_name="stocktakeline",
            name="stocktake_unique_stock",
        ),
        migrations.AlterField(
            model_name="stock",
            name="source_purchase_order_line",
            field=models.ForeignKey(
                blank=True,
                help_text="The PO line this stock originated from (if source='purchase_order')",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_generated",
                to="purchasing.purchaseorderline",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktakeconfiguration",
            constraint=models.CheckConstraint(
                condition=models.Q(("pk", 1)), name="stocktake_configuration_singleton"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktakeline",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("stocktake", "stock"),
                name="stocktake_unique_stock",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktakeline",
            constraint=models.CheckConstraint(
                condition=models.Q(("location", ""), _negated=True),
                name="stocktake_line_location_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktakeline",
            constraint=models.CheckConstraint(
                condition=models.Q(("reason", ""), _negated=True),
                name="stocktake_line_reason_not_blank",
            ),
        ),
    ]
