# Generated by Django 6.1.1 on 2026-09-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0012_protect_inventory_provenance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="xero_last_synced",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
