# Generated by Django 6.1.1 on 2026-09-08 01:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0010_costline_costline_known_owner"),
        ("purchasing", "0013_purchase_order_inbound_observation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        [
                            "opening",
                            "job_opening",
                            "receipt",
                            "receipt_opening",
                            "receipt_reversal",
                            "issue",
                            "return",
                            "stocktake",
                        ],
                    )
                ),
                name="movement_known_kind",
            ),
        ),
    ]
