# Generated by Django 6.1.1 on 2026-09-08 18:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0014_stockmovement_movement_known_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyReceiptAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "recorded_received_quantity",
                    models.DecimalField(decimal_places=3, max_digits=11),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=11)),
                (
                    "note",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="purchasing.purchaseorderevent",
                    ),
                ),
                (
                    "purchase_order_line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="purchasing.purchaseorderline",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)), name="legacy_receipt_gap_positive"
                    )
                ],
            },
        ),
        migrations.RunSQL(
            """
            CREATE FUNCTION protect_legacy_receipt_adjustment() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'Legacy receipt adjustments are immutable evidence';
            END;
            $$ LANGUAGE plpgsql;
            CREATE TRIGGER immutable_legacy_receipt_adjustment
            BEFORE UPDATE OR DELETE ON purchasing_legacyreceiptadjustment
            FOR EACH ROW EXECUTE FUNCTION protect_legacy_receipt_adjustment();
            """,
            reverse_sql="""
            DROP TRIGGER immutable_legacy_receipt_adjustment ON purchasing_legacyreceiptadjustment;
            DROP FUNCTION protect_legacy_receipt_adjustment();
            """,
        ),
    ]
