# Generated by Django 6.1.1 on 2026-09-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0015_legacy_receipt_adjustment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaseorderline",
            options={"ordering": [models.OrderBy(models.F("created_at"), nulls_first=True), "id"]},
        ),
        # ADR 0057: old line creation times are unknown, not the migration time.
        migrations.AddField(
            model_name="purchaseorderline",
            name="created_at",
            field=models.DateTimeField(null=True, editable=False),
        ),
        migrations.AlterField(
            model_name="purchaseorderline",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
