# Generated by Django 6.1.1 on 2026-09-12 10:21

from django.db import migrations


class Migration(migrations.Migration):
    """Drop the column that arbitrated between two masters.

    Docketworks masters the purchase order and Xero mirrors it, so there is no
    collision to resolve and nothing to record about when the two copies last
    agreed. The column was never released — production has never held it — so
    this removes it rather than migrating what it stored.
    """

    dependencies = [
        ("purchasing", "0016_alter_purchaseorderline_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="xero_agreed_at",
        ),
    ]
