# Generated by Django 6.1.1 on 2026-09-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    """Record that a purchase order owes Xero a call.

    A boolean, defaulting False, rather than a timestamp compared against
    ``updated_at``. The timestamp this replaces arbitrated between two masters
    and matched every row that predated it, which would have rewritten the back
    catalogue in the live organisation. False is the correct value for every
    existing order, so there is nothing to backfill.
    """

    dependencies = [
        ("purchasing", "0017_drop_xero_agreed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="xero_push_due",
            field=models.BooleanField(
                default=False,
                help_text="Xero is owed a call about this order. Set when the status moves, which is the only thing Xero needs to hear about: the order leaving draft, and the receipt that settles its total. Cleared when the push lands. A field edit never sets it — the workspace saves each field as its own PATCH, and Xero holds the order only so a bill has something to link against, which no intermediate state affects.",
            ),
        ),
    ]
