# Generated by Django 6.0.3 on 2026-04-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0028_update_created_by_from_events"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="purchaseorder",
            table=None,
        ),
        migrations.AlterModelTable(
            name="purchaseorderevent",
            table=None,
        ),
        migrations.AlterModelTable(
            name="purchaseorderline",
            table=None,
        ),
        migrations.AlterModelTable(
            name="purchaseordersupplierquote",
            table=None,
        ),
        migrations.AlterModelTable(
            name="stock",
            table=None,
        ),
    ]
