# Generated by Codex on 2026-05-15

from django.db import migrations, models


def use_aluminium(apps, schema_editor):
    PurchaseOrderLine = apps.get_model("purchasing", "PurchaseOrderLine")
    Stock = apps.get_model("purchasing", "Stock")
    legacy_value = "alumin" + "um"

    PurchaseOrderLine.objects.filter(metal_type=legacy_value).update(
        metal_type="aluminium"
    )
    Stock.objects.filter(metal_type=legacy_value).update(metal_type="aluminium")


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0032_stock_parser_attempted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorderline",
            name="metal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("stainless_steel", "Stainless Steel"),
                    ("mild_steel", "Mild Steel"),
                    ("aluminium", "Aluminium"),
                    ("brass", "Brass"),
                    ("copper", "Copper"),
                    ("titanium", "Titanium"),
                    ("zinc", "Zinc"),
                    ("galvanized", "Galvanized"),
                    ("unspecified", "Unspecified"),
                    ("other", "Other"),
                ],
                default="unspecified",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="metal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("stainless_steel", "Stainless Steel"),
                    ("mild_steel", "Mild Steel"),
                    ("aluminium", "Aluminium"),
                    ("brass", "Brass"),
                    ("copper", "Copper"),
                    ("titanium", "Titanium"),
                    ("zinc", "Zinc"),
                    ("galvanized", "Galvanized"),
                    ("unspecified", "Unspecified"),
                    ("other", "Other"),
                ],
                default="unspecified",
                help_text="Type of metal",
                max_length=100,
            ),
        ),
        migrations.RunPython(use_aluminium, migrations.RunPython.noop),
    ]
