# This file is autogenerated by update_init.py script

from .apps import QuotingConfig
from .tests_utils import TestCalculateSheetTenths

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .mcp import QuotingTool, SupplierProductQueryTool
        from .models import (
            ProductParsingMapping,
            ScrapeJob,
            SupplierPriceList,
            SupplierProduct,
        )
        from .serializers import (
            ExtractSupplierPriceListErrorSerializer,
            ExtractSupplierPriceListResponseSerializer,
            ImportStatisticsSerializer,
            PriceListInfoSerializer,
            SupplierInfoSerializer,
            SupplierPriceListUploadSerializer,
            ValidationInfoSerializer,
        )
        from .serializers_scheduled_tasks import (
            ScheduledTaskExecutionSerializer,
            ScheduledTaskSerializer,
        )
        from .tasks import run_all_scrapers_task
        from .tests_mcp import QuotingToolTests, SupplierProductQueryToolTests
        from .utils import (
            calculate_product_mapping_hash,
            calculate_sheet_tenths,
            calculate_supplier_product_hash,
        )
        from .views_scheduled_tasks import (
            ScheduledTaskExecutionViewSet,
            ScheduledTaskViewSet,
        )
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

# EXCLUDED IMPORTS - These contain problematic dependencies that cause circular imports
# Import these directly where needed using:
# from .views import extract_supplier_price_list_data_view
#

__all__ = [
    "ExtractSupplierPriceListErrorSerializer",
    "ExtractSupplierPriceListResponseSerializer",
    "ImportStatisticsSerializer",
    "PriceListInfoSerializer",
    "ProductParsingMapping",
    "QuotingConfig",
    "QuotingTool",
    "QuotingToolTests",
    "ScheduledTaskExecutionSerializer",
    "ScheduledTaskExecutionViewSet",
    "ScheduledTaskSerializer",
    "ScheduledTaskViewSet",
    "ScrapeJob",
    "SupplierInfoSerializer",
    "SupplierPriceList",
    "SupplierPriceListUploadSerializer",
    "SupplierProduct",
    "SupplierProductQueryTool",
    "SupplierProductQueryToolTests",
    "TestCalculateSheetTenths",
    "ValidationInfoSerializer",
    "calculate_product_mapping_hash",
    "calculate_sheet_tenths",
    "calculate_supplier_product_hash",
    "run_all_scrapers_task",
]
