from typing import Any

class OpenApiException(Exception): ...

class ApiException(OpenApiException):
    def __init__(
        self, status: int | None = None, reason: str | None = None, http_resp: Any = None
    ) -> None: ...
    @property
    def status(self) -> int | None: ...
    @property
    def reason(self) -> str | None: ...
    @property
    def body(self) -> bytes | None: ...
    @property
    def headers(self) -> dict[str, str] | None: ...
