# Generated by Django 6.0.4 on 2026-07-06 00:12

import uuid

import django.utils.timezone
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    replaces = [
        ("accounts", "0001_initial"),
        ("accounts", "0002_initial"),
        ("accounts", "0003_alter_historicalstaff_updated_at_and_more"),
        ("accounts", "0004_add_staff_permissions_tables"),
        ("accounts", "0005_alter_staff_groups_alter_staff_user_permissions"),
        ("accounts", "0006_historicalstaff_date_left_staff_date_left"),
        ("accounts", "0007_auto_20250730_2359"),
        ("accounts", "0008_remove_historicalstaff_is_active_and_more"),
        ("accounts", "0009_historicalstaff_xero_user_id_staff_xero_user_id"),
        ("accounts", "0010_rename_is_staff_historicalstaff_is_office_staff_and_more"),
        ("accounts", "0011_remove_ims_payroll_fields"),
        ("accounts", "0012_add_base_wage_rate"),
        ("accounts", "0013_alter_historicalstaff_table_alter_staff_table"),
        ("accounts", "0014_add_is_workshop_staff"),
        ("accounts", "0016_historicalstaff_default_labour_subtype_and_more"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="staff_icons/"),
                ),
                ("password_needs_reset", models.BooleanField(default=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                (
                    "preferred_name",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "base_wage_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Actual hourly pay rate. wage_rate is auto-computed with leave loading.",
                        max_digits=10,
                    ),
                ),
                (
                    "wage_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "xero_user_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "date_left",
                    models.DateField(
                        blank=True,
                        help_text="Date staff member left employment (null for current employees)",
                        null=True,
                    ),
                ),
                ("is_office_staff", models.BooleanField(default=False)),
                ("is_workshop_staff", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hours_mon",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Standard hours for Monday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                (
                    "hours_tue",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Standard hours for Tuesday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                (
                    "hours_wed",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Standard hours for Wednesday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                (
                    "hours_thu",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Standard hours for Thursday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                (
                    "hours_fri",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Standard hours for Friday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                (
                    "hours_sat",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Standard hours for Saturday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                (
                    "hours_sun",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Standard hours for Sunday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Member",
                "verbose_name_plural": "Staff Members",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalStaff",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("icon", models.TextField(blank=True, max_length=100, null=True)),
                ("password_needs_reset", models.BooleanField(default=False)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                (
                    "preferred_name",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "base_wage_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Actual hourly pay rate. wage_rate is auto-computed with leave loading.",
                        max_digits=10,
                    ),
                ),
                (
                    "wage_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "xero_user_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "date_left",
                    models.DateField(
                        blank=True,
                        help_text="Date staff member left employment (null for current employees)",
                        null=True,
                    ),
                ),
                ("is_office_staff", models.BooleanField(default=False)),
                ("is_workshop_staff", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "hours_mon",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Standard hours for Monday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                (
                    "hours_tue",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Standard hours for Tuesday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                (
                    "hours_wed",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Standard hours for Wednesday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                (
                    "hours_thu",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Standard hours for Thursday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                (
                    "hours_fri",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Standard hours for Friday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                (
                    "hours_sat",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Standard hours for Saturday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                (
                    "hours_sun",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Standard hours for Sunday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Staff Member",
                "verbose_name_plural": "historical Staff Members",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
