# Generated by Django 6.0.4 on 2026-07-06 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_baseline"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("job", "0001_baseline"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="default_labour_subtype",
            field=models.ForeignKey(
                blank=True,
                help_text="Labour subtype preselected on new timesheet entries. Auto-set from is_workshop_staff when blank.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="default_for_staff",
                to="job.laboursubtype",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="historicalstaff",
            name="default_labour_subtype",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Labour subtype preselected on new timesheet entries. Auto-set from is_workshop_staff when blank.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="job.laboursubtype",
            ),
        ),
        migrations.AddField(
            model_name="historicalstaff",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
