# Generated by Django 6.0.7 on 2026-08-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_seed_system_automation_user"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("job", "0003_allow_blank_company_and_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstaff",
            name="xero_tenant_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="xero_tenant_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="staff",
            constraint=models.CheckConstraint(
                condition=models.Q(("xero_tenant_id", ""), _negated=True),
                name="staff_xero_tenant_id_not_blank",
            ),
        ),
    ]
