# Generated by Django 6.0.7 on 2026-08-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_staff_payroll_terms"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="staffpayrollterm",
            constraint=models.CheckConstraint(
                condition=models.Q(("xero_salary_wage_id", ""), _negated=True),
                name="payroll_term_salary_wage_id_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffpayrollterm",
            constraint=models.CheckConstraint(
                condition=models.Q(("xero_working_pattern_id", ""), _negated=True),
                name="payroll_term_working_pattern_id_not_blank",
            ),
        ),
    ]
