# Generated by Django 6.0.7 on 2026-08-25 00:51

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_adr_0040_blank_checks"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("job", "0004_costline_managed_by_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="staff",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("office_email"),
                name="staff_office_email_ci_unique",
            ),
        ),
    ]
