# Generated by Django 6.0.7 on 2026-08-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_staff_staff_office_email_ci_unique"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("job", "0004_costline_managed_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstaff",
            name="office_email",
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="staff",
            name="office_email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name="staff",
            constraint=models.CheckConstraint(
                condition=models.Q(("office_email", ""), _negated=True),
                name="staff_office_email_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="staff",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("office_email__isnull", False),
                    ("payroll_email__isnull", False),
                    _connector="OR",
                ),
                name="staff_at_least_one_email",
                violation_error_message="A staff member needs at least one email address.",
            ),
        ),
    ]
