# Generated by Django 6.0.7 on 2026-09-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_staff_staff_payroll_email_ci_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstaff",
            name="base_wage_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text=(
                    "Actual hourly pay rate. wage_rate is auto-computed with labour cost loading."
                ),
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="base_wage_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text=(
                    "Actual hourly pay rate. wage_rate is auto-computed with labour cost loading."
                ),
                max_digits=10,
            ),
        ),
    ]
