# Generated by Django 6.0.7 on 2026-09-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_labour_cost_loading_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstaff",
            name="xero_fields_checksum",
            field=models.CharField(
                blank=True,
                help_text=(
                    "SHA-256 of the last applied Xero employee fields and payroll-term history"
                ),
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="xero_fields_checksum",
            field=models.CharField(
                blank=True,
                help_text=(
                    "SHA-256 of the last applied Xero employee fields and payroll-term history"
                ),
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="staff",
            constraint=models.CheckConstraint(
                condition=~models.Q(xero_fields_checksum=""),
                name="staff_xero_fields_checksum_not_blank",
            ),
        ),
    ]
