# Generated by Django 6.1.1 on 2026-09-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_staff_xero_fields_checksum"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstaff",
            name="xero_payroll_terms_checksum",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="xero_payroll_terms_checksum",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
