# Generated by Django 6.0.3 on 2026-04-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_add_base_wage_rate"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="historicalstaff",
            table=None,
        ),
        migrations.AlterModelTable(
            name="staff",
            table=None,
        ),
    ]
