# Generated by Django 6.0.3 on 2026-04-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_historicalstaff_table_alter_staff_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstaff",
            name="is_workshop_staff",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="is_workshop_staff",
            field=models.BooleanField(default=True),
        ),
    ]
