# Generated by Django 6.1.1 on 2026-09-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_historicalstaff_xero_payroll_terms_checksum_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("job", "0012_alter_costline_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="staff",
            constraint=models.CheckConstraint(
                condition=models.Q(("xero_payroll_terms_checksum", ""), _negated=True),
                name="staff_xero_payroll_terms_checksum_not_blank",
            ),
        ),
    ]
