# Generated by Django 6.1.1 on 2026-09-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_staff_staff_xero_payroll_terms_checksum_not_blank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffpayrollterm",
            name="working_weeks",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
