# Generated by Django 6.0.4 on 2026-06-10 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_create_system_automation_user"),
        ("job", "0094_costline_labour_subtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstaff",
            name="default_labour_subtype",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Labour subtype preselected on new timesheet entries. Auto-set from is_workshop_staff when blank.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="job.laboursubtype",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="default_labour_subtype",
            field=models.ForeignKey(
                blank=True,
                help_text="Labour subtype preselected on new timesheet entries. Auto-set from is_workshop_staff when blank.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="default_for_staff",
                to="job.laboursubtype",
            ),
        ),
    ]
