# Generated by Django 6.0.7 on 2026-08-17 08:23

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("job", "0003_allow_blank_company_and_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("annual_leave", "Annual Leave"),
                            ("sick_leave", "Sick Leave"),
                            ("unpaid_leave", "Unpaid Leave"),
                            ("bereavement_leave", "Bereavement Leave"),
                            ("public_holiday", "Public Holiday"),
                        ],
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.OneToOneField(
                        blank=True,
                        help_text="Special job used for this leave type. Its default Xero pay item is the single source of the Xero mapping.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_type_configuration",
                        to="job.job",
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("leave", "Leave"), ("office_closure", "Office closure")],
                        default="leave",
                        max_length=20,
                    ),
                ),
                ("batch_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_requests",
                        to="timesheet.leavetype",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date", "staff__last_name", "staff__first_name"],
            },
        ),
        migrations.CreateModel(
            name="LeaveDay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField()),
                ("hours", models.DecimalField(decimal_places=3, max_digits=6)),
                (
                    "cost_line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_day",
                        to="job.costline",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_days",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="timesheet.leaverequest",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("staff", "date"), name="unique_staff_leave_day"
                    ),
                    models.UniqueConstraint(
                        fields=("request", "date"), name="unique_request_leave_day"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("hours__gt", Decimal("0"))),
                        name="timesheet_leave_day_positive_hours",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="leaverequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="timesheet_leave_request_date_order",
            ),
        ),
    ]
