# Generated by Django 6.0.7 on 2026-08-18 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timesheet", "0002_seed_leave_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="leaverequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("note", ""), _negated=True),
                name="timesheet_leave_request_note_not_blank",
            ),
        ),
    ]
