# Generated by Django 6.1.1 on 2026-10-01 09:50

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timesheet", "0004_public_holiday_posts_nowhere"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimesheetEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("event_type", models.CharField(max_length=100)),
                ("delta_before", models.JSONField(blank=True, null=True)),
                ("delta_after", models.JSONField(blank=True, null=True)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("accounting_date", models.DateField()),
                ("cost_line_id", models.UUIDField(db_index=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timesheet_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["worker", "accounting_date", "-timestamp"],
                        name="tsevent_worker_day_idx",
                    )
                ],
            },
        ),
    ]
