# Generated by Django 6.1.1 on 2026-10-05 12:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timesheet", "0006_approve_time_entered_before_approval_bound_pay"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceDay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField()),
                ("clock_in", models.TimeField()),
                ("clock_out", models.TimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_days",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("staff", "date"), name="unique_staff_attendance_day"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("clock_out__isnull", True),
                            ("clock_out__gt", models.F("clock_in")),
                            _connector="OR",
                        ),
                        name="timesheet_attendance_finish_after_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("submitted_at__isnull", True),
                            ("clock_out__isnull", False),
                            _connector="OR",
                        ),
                        name="timesheet_attendance_sent_only_when_clocked_out",
                    ),
                ],
            },
        ),
    ]
