# Generated by Django 6.1.1 on 2026-10-05 19:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timesheet", "0007_attendanceday"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendanceday",
            name="breaks_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="AttendanceBreak",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
                ("paid", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attendance_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breaks",
                        to="timesheet.attendanceday",
                    ),
                ),
            ],
            options={
                "ordering": ["start", "created_at", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end__gt", models.F("start"))),
                        name="timesheet_attendance_break_end_after_start",
                    )
                ],
            },
        ),
    ]
