# Generated by Django 6.0.3 on 2026-04-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0015_populate_xero_addresses"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="client",
            table=None,
        ),
        migrations.AlterModelTable(
            name="clientcontact",
            table=None,
        ),
        migrations.AlterModelTable(
            name="supplier",
            table="client_client",
        ),
        migrations.AlterModelTable(
            name="supplierpickupaddress",
            table=None,
        ),
    ]
