# Generated by Django 6.0.4 on 2026-04-19 20:57
import logging

from django.db import migrations, models
from django.db.models import Q

logger = logging.getLogger("xero")


def backfill_allow_jobs_false(apps, schema_editor):
    """
    Retroactively apply the new allow_jobs enforcement to clients that were
    already archived or merged in Xero before this field existed.
    """
    Client = apps.get_model("client", "Client")

    updated = Client.objects.filter(
        Q(xero_archived=True) | Q(merged_into__isnull=False),
        allow_jobs=True,
    ).update(allow_jobs=False)

    logger.info(
        "Migration 0018: set allow_jobs=False on %d archived/merged clients",
        updated,
    )


def reverse_backfill_allow_jobs_false(apps, schema_editor):
    """
    No-op: the schema reversal (field removal) drops every value.
    """


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0017_reassign_stranded_merged_client_fks"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="allow_jobs",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "If False, this client cannot be selected as the client "
                    "on a Job. Use for Xero contacts that must exist (tax "
                    "authorities, internal accounts, etc.) but should never "
                    "appear on a job. Automatically set to False when a "
                    "client is archived or merged in Xero."
                ),
            ),
        ),
        migrations.RunPython(
            backfill_allow_jobs_false,
            reverse_backfill_allow_jobs_false,
        ),
    ]
