# Generated by Django 6.0.4 on 2026-05-14 21:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0019_client_name_fts_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierSearchAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("alias", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["alias"],
            },
        ),
        migrations.AddField(
            model_name="suppliersearchalias",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_search_aliases",
                to="client.client",
            ),
        ),
        migrations.AddConstraint(
            model_name="suppliersearchalias",
            constraint=models.UniqueConstraint(
                fields=("client", "alias"),
                name="unique_supplier_search_alias_per_client",
            ),
        ),
    ]
