# This file is autogenerated by update_init.py script

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .auto_archive_service import AutoArchiveResult, AutoArchiveService
        from .chat_file_service import ChatFileService
        from .chat_service import ChatService
        from .data_integrity_service import DataIntegrityService
        from .data_quality_report import ArchivedJobsComplianceService
        from .delivery_docket_service import generate_delivery_docket
        from .delta_checksum import (
            ChecksumInput,
            compute_job_delta_checksum,
            normalise_value,
        )
        from .file_service import (
            create_thumbnail,
            get_thumbnail_folder,
            sync_job_folder,
        )
        from .import_quote_service import (
            QuoteImportError,
            QuoteImportResult,
            import_quote_from_drafts,
            import_quote_from_file,
            preview_quote_import,
            preview_quote_import_from_drafts,
            serialize_draft_lines,
            serialize_validation_report,
        )
        from .job_profitability_report import JobProfitabilityReportService
        from .job_rest_service import (
            DeltaValidationError,
            JobDeltaPayload,
            JobRestService,
            PreconditionFailed,
        )
        from .job_service import (
            JobStaffService,
            archive_complete_jobs,
            get_job_total_value,
            get_paid_complete_jobs,
            recalculate_job_invoicing_state,
        )
        from .job_summary_pdf_service import JobSummaryPdfService
        from .kanban_categorization_service import (
            KanbanCategorizationService,
            KanbanColumn,
        )
        from .kanban_service import KanbanSerializationContext, KanbanService
        from .mcp_chat_service import MCPChatService
        from .month_end_service import MonthEndService
        from .paid_flag_service import PaidFlagResult, PaidFlagService
        from .quote_mode_controller import QuoteModeController
        from .quote_sync_service import apply_quote, link_quote_sheet, preview_quote
        from .time_entry_rates import (
            calculate_time_unit_rates,
            get_bill_rate_multiplier,
            is_leave_pay_item,
            leave_wage_rate_multiplier,
            normalize_multiplier,
            resolve_xero_pay_item,
            resolve_xero_pay_item_for_job,
            to_decimal,
        )
        from .workshop_pdf_service import (
            add_delivery_docket_details_table,
            add_handover_section,
            add_letterhead_banner,
            add_logo,
            add_materials_used_table,
            add_time_used_table,
            add_title,
            add_workshop_details_table,
            add_workshop_letterhead,
            convert_html_to_reportlab,
            create_delivery_docket_main_document,
            create_delivery_docket_pdf,
            create_image_document,
            create_workshop_main_document,
            create_workshop_pdf,
            draw_table_with_page_breaks,
            format_hours_compact,
            format_hours_display,
            format_retail_line_total,
            get_pdf_file_paths,
            get_time_breakdown,
            get_workshop_hours,
            merge_pdfs,
            process_attachments,
            wait_until_file_ready,
        )
        from .workshop_service import WorkshopTimesheetService
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "ArchivedJobsComplianceService",
    "AutoArchiveResult",
    "AutoArchiveService",
    "ChatFileService",
    "ChatService",
    "ChecksumInput",
    "DataIntegrityService",
    "DeltaValidationError",
    "JobDeltaPayload",
    "JobProfitabilityReportService",
    "JobRestService",
    "JobStaffService",
    "JobSummaryPdfService",
    "KanbanCategorizationService",
    "KanbanColumn",
    "KanbanSerializationContext",
    "KanbanService",
    "MCPChatService",
    "MonthEndService",
    "PaidFlagResult",
    "PaidFlagService",
    "PreconditionFailed",
    "QuoteImportError",
    "QuoteImportResult",
    "QuoteModeController",
    "WorkshopTimesheetService",
    "add_delivery_docket_details_table",
    "add_handover_section",
    "add_letterhead_banner",
    "add_logo",
    "add_materials_used_table",
    "add_time_used_table",
    "add_title",
    "add_workshop_details_table",
    "add_workshop_letterhead",
    "apply_quote",
    "archive_complete_jobs",
    "calculate_time_unit_rates",
    "compute_job_delta_checksum",
    "convert_html_to_reportlab",
    "create_delivery_docket_main_document",
    "create_delivery_docket_pdf",
    "create_image_document",
    "create_thumbnail",
    "create_workshop_main_document",
    "create_workshop_pdf",
    "draw_table_with_page_breaks",
    "format_hours_compact",
    "format_hours_display",
    "format_retail_line_total",
    "generate_delivery_docket",
    "get_bill_rate_multiplier",
    "get_job_total_value",
    "get_paid_complete_jobs",
    "get_pdf_file_paths",
    "get_thumbnail_folder",
    "get_time_breakdown",
    "get_workshop_hours",
    "import_quote_from_drafts",
    "import_quote_from_file",
    "is_leave_pay_item",
    "leave_wage_rate_multiplier",
    "link_quote_sheet",
    "merge_pdfs",
    "normalise_value",
    "normalize_multiplier",
    "preview_quote",
    "preview_quote_import",
    "preview_quote_import_from_drafts",
    "process_attachments",
    "recalculate_job_invoicing_state",
    "resolve_xero_pay_item",
    "resolve_xero_pay_item_for_job",
    "serialize_draft_lines",
    "serialize_validation_report",
    "sync_job_folder",
    "to_decimal",
    "wait_until_file_ready",
]
