# Generated by Django 6.0.7 on 2026-08-01 10:23

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchTelemetryEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("search", "Search"), ("click", "Click")],
                        max_length=20,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("company", "Company"),
                            ("kanban", "Kanban"),
                            ("stock", "Stock"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
                ("query", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "normalized_query",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("result_count", models.PositiveIntegerField(default=0)),
                ("returned_count", models.PositiveIntegerField(default=0)),
                ("returned_result_ids", models.JSONField(blank=True, default=list)),
                (
                    "selected_result_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "selected_label",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("selected_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "source_event_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_telemetry_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workflow_searchtelemetryevent",
                "ordering": ["-occurred_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["domain", "event_type", "-occurred_at"],
                        name="wf_search_domain_event_idx",
                    ),
                    models.Index(
                        fields=["domain", "normalized_query", "-occurred_at"],
                        name="wf_search_domain_query_idx",
                    ),
                    models.Index(
                        fields=["source", "-occurred_at"],
                        name="workflow_search_source_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("normalized_query", ""), _negated=True),
                        name="normalized_query_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("query", ""), _negated=True),
                        name="query_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("selected_label", ""), _negated=True),
                        name="selected_label_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("selected_result_id", ""), _negated=True),
                        name="selected_result_id_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source_event_hash", ""), _negated=True),
                        name="source_event_hash_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source", ""), _negated=True),
                        name="source_not_blank",
                    ),
                ],
            },
        ),
    ]
