# Generated by Django 6.0.7 on 2026-08-01 10:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionReplayRecording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("initial_path", models.CharField(max_length=500)),
                ("latest_path", models.CharField(max_length=500)),
                ("job_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("viewport_width", models.PositiveIntegerField(blank=True, null=True)),
                ("viewport_height", models.PositiveIntegerField(blank=True, null=True)),
                ("event_count", models.PositiveIntegerField(default=0)),
                ("compressed_bytes", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="session_replay_recordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workflow_sessionreplayrecording",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionReplayChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("first_event_timestamp_ms", models.BigIntegerField()),
                ("last_event_timestamp_ms", models.BigIntegerField()),
                ("event_count", models.PositiveIntegerField()),
                ("compressed_bytes", models.PositiveIntegerField()),
                ("storage_path", models.CharField(max_length=500)),
                ("sha256", models.CharField(max_length=64)),
                ("path", models.CharField(max_length=500)),
                ("job_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("viewport_width", models.PositiveIntegerField(blank=True, null=True)),
                ("viewport_height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="diagnostics.sessionreplayrecording",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_sessionreplaychunk",
                "ordering": ["recording_id", "sequence"],
            },
        ),
        migrations.AddIndex(
            model_name="sessionreplayrecording",
            index=models.Index(
                fields=["user", "-started_at"], name="workflow_replay_user_start_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionreplayrecording",
            index=models.Index(fields=["started_at"], name="workflow_replay_started_idx"),
        ),
        migrations.AddIndex(
            model_name="sessionreplayrecording",
            index=models.Index(
                fields=["job_id", "-started_at"], name="workflow_replay_job_start_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionreplayrecording",
            constraint=models.CheckConstraint(
                condition=models.Q(("user_agent", ""), _negated=True),
                name="user_agent_not_blank",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionreplaychunk",
            index=models.Index(
                fields=["recording", "sequence"], name="workflow_chunk_record_seq_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionreplaychunk",
            index=models.Index(fields=["created_at"], name="workflow_chunk_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="sessionreplaychunk",
            constraint=models.UniqueConstraint(
                fields=("recording", "sequence"),
                name="workflow_session_replay_chunk_recording_sequence_uniq",
            ),
        ),
    ]
