# This file is autogenerated by update_init.py script

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .phone_call_service import (
            CallClassification,
            PhoneCallDeleteResult,
            PhoneCallSyncResult,
            PhoneMatcher,
            PhoneProviderCallPage,
            PhoneProviderConfig,
            PhoneProviderPortalClient,
            archive_recording,
            assign_phone_number,
            call_parties,
            configured_own_numbers,
            delete_archived_provider_recordings,
            delete_local_recording,
            is_call_payload,
            link_phone_call_to_job,
            normalize_phone,
            provider_delete_recording,
            recording_file_path,
            rematch_calls_for_numbers,
            sync_call_history,
            sync_recent_calls,
            unlink_phone_call_job,
            upsert_call_record,
        )
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "CallClassification",
    "PhoneCallDeleteResult",
    "PhoneCallSyncResult",
    "PhoneMatcher",
    "PhoneProviderCallPage",
    "PhoneProviderConfig",
    "PhoneProviderPortalClient",
    "archive_recording",
    "assign_phone_number",
    "call_parties",
    "configured_own_numbers",
    "delete_archived_provider_recordings",
    "delete_local_recording",
    "is_call_payload",
    "link_phone_call_to_job",
    "normalize_phone",
    "provider_delete_recording",
    "recording_file_path",
    "rematch_calls_for_numbers",
    "sync_call_history",
    "sync_recent_calls",
    "unlink_phone_call_job",
    "upsert_call_record",
]
