# Generated by Django 6.0.7 on 2026-08-01 07:40

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceAPIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Service name (e.g., 'Chatbot Service')",
                        max_length=100,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="API key for authentication",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Service API Key",
                "verbose_name_plural": "Service API Keys",
                "db_table": "workflow_serviceapikey",
            },
        ),
        migrations.CreateModel(
            name="CompanyDefaults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "company_acronym",
                    models.CharField(
                        blank=True,
                        help_text="Short acronym for the company (e.g., 'MSM' for Morris Sheetmetal)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "time_markup",
                    models.DecimalField(decimal_places=2, default=0.3, max_digits=5),
                ),
                (
                    "materials_markup",
                    models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
                ),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.1500"),
                        help_text="Sales tax rate applied to amounts DocketWorks quotes before Xero has issued an invoice, as a fraction (0.1500 = 15% NZ GST). Xero remains authoritative for tax on invoices that exist.",
                        max_digits=5,
                    ),
                ),
                (
                    "wage_rate",
                    models.DecimalField(decimal_places=2, default=32.0, max_digits=6),
                ),
                (
                    "annual_leave_loading",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        help_text="Percentage added to base_wage_rate to get costing wage_rate (20.00 = 20%)",
                        max_digits=5,
                    ),
                ),
                (
                    "workshop_efficiency_factor",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.750"),
                        help_text="Fraction of clocked workshop hours that count as schedulable productive output (e.g. 0.750 = 75%). Accounts for breaks, tool changes, idle time. Applied to per-day capacity in the workshop scheduler after subtracting booked time/leave.",
                        max_digits=4,
                    ),
                ),
                (
                    "financial_year_start_month",
                    models.IntegerField(
                        default=4,
                        help_text="Month the financial year starts (1=January, 4=April, 7=July, etc.)",
                    ),
                ),
                (
                    "starting_job_number",
                    models.IntegerField(
                        default=1,
                        help_text="Helper field to set the starting job number based on the latest paper job",
                    ),
                ),
                (
                    "starting_po_number",
                    models.IntegerField(
                        default=1,
                        help_text="Helper field to set the starting purchase order number",
                    ),
                ),
                (
                    "po_prefix",
                    models.CharField(
                        default="PO-",
                        help_text="Prefix for purchase order numbers (e.g., PO-, JO-)",
                        max_length=10,
                    ),
                ),
                (
                    "master_quote_template_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the master Google Sheets quote template",
                        null=True,
                    ),
                ),
                (
                    "master_quote_template_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Sheets ID for the quote template",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "gdrive_quotes_folder_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the Google Drive folder for storing quotes",
                        null=True,
                    ),
                ),
                (
                    "gdrive_quotes_folder_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Drive folder ID for storing quotes",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "google_shared_drive_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Shared Drive ID for the company shared drive",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "gdrive_how_we_work_folder_id",
                    models.CharField(
                        blank=True,
                        help_text="Folder ID for '01 - How we work' (policies, basics)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "gdrive_sops_folder_id",
                    models.CharField(
                        blank=True,
                        help_text="Folder ID for '02 - SOPs' (standard operating procedures)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "gdrive_reference_library_folder_id",
                    models.CharField(
                        blank=True,
                        help_text="Folder ID for '03 - Reference Library' (reference documents, forms, registers)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "accounting_provider",
                    models.CharField(
                        default="xero",
                        help_text="Active accounting integration: 'xero' or 'myob'",
                        max_length=20,
                    ),
                ),
                (
                    "xero_tenant_id",
                    models.CharField(
                        blank=True,
                        help_text="The Xero tenant ID to use for this company",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "xero_shortcode",
                    models.CharField(
                        blank=True,
                        help_text="Xero organisation shortcode for deep linking (e.g., '!8-5Xl')",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "xero_sales_branding_theme_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Controls the layout and presentation of every quote and sales invoice created in Xero. It is configured during Xero setup and required before sales documents can be created.",
                        null=True,
                        verbose_name="Xero sales branding theme",
                    ),
                ),
                (
                    "xero_quote_terms",
                    models.TextField(
                        default="Terms of trade can be found on our website.",
                        help_text="Terms sent on every quote created by DocketWorks. Required — Xero does not apply its own Terms (Quotes) default to quotes created through the API. Copy the same text to Xero's Terms (Quotes) setting so quotes created directly in Xero during an outage use the same terms.",
                        max_length=4000,
                        verbose_name="Xero quote terms",
                    ),
                ),
                (
                    "enable_xero_sync",
                    models.BooleanField(
                        default=True,
                        help_text="Gate for Xero sync. Defaults True (prod). Dev fixture sets False; seed_xero_from_database sets True after prod IDs are cleared.",
                    ),
                ),
                (
                    "xero_automated_day_floor",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Reserve this many Xero daily API calls for user-initiated work. Automated sync aborts when the active Xero app reports remaining daily calls at or below this value.",
                    ),
                ),
                (
                    "xero_payroll_calendar_name",
                    models.CharField(
                        default="Weekly",
                        help_text="Name of Xero Payroll calendar to use (e.g., 'Weekly 2025')",
                        max_length=100,
                    ),
                ),
                (
                    "xero_payroll_calendar_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Cached Xero Payroll calendar ID (set by xero --setup command)",
                        null=True,
                    ),
                ),
                (
                    "xero_payroll_start_date",
                    models.DateField(
                        blank=True,
                        help_text="Date Xero payroll went live — reconciliation ignores data before this",
                        null=True,
                    ),
                ),
                (
                    "weekend_timesheets_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Show Saturday and Sunday in timesheet views (7-day week). Off = 5-day Mon-Fri.",
                    ),
                ),
                (
                    "job_delta_soft_fail",
                    models.BooleanField(
                        default=True,
                        help_text="When enabled, job delta checksum mismatches are logged and recorded without blocking the save. Disable to reject stale updates.",
                    ),
                ),
                ("mon_start", models.TimeField(default="07:00")),
                ("mon_end", models.TimeField(default="15:00")),
                ("tue_start", models.TimeField(default="07:00")),
                ("tue_end", models.TimeField(default="15:00")),
                ("wed_start", models.TimeField(default="07:00")),
                ("wed_end", models.TimeField(default="15:00")),
                ("thu_start", models.TimeField(default="07:00")),
                ("thu_end", models.TimeField(default="15:00")),
                ("fri_start", models.TimeField(default="07:00")),
                ("fri_end", models.TimeField(default="15:00")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_xero_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="The last time Xero data was synchronized",
                        null=True,
                    ),
                ),
                (
                    "last_xero_deep_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="The last time a deep Xero sync was performed (looking back 90 days)",
                        null=True,
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(
                        blank=True,
                        help_text="Street address line 1",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True,
                        help_text="Street address line 2 (optional)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "suburb",
                    models.CharField(
                        blank=True,
                        help_text="Suburb (for NZ addresses)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, help_text="City", max_length=100, null=True),
                ),
                (
                    "post_code",
                    models.CharField(
                        blank=True,
                        help_text="Postal/ZIP code",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="New Zealand", help_text="Country name", max_length=100
                    ),
                ),
                (
                    "company_email",
                    models.EmailField(
                        blank=True,
                        help_text="Company contact email address",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "company_url",
                    models.URLField(blank=True, help_text="Company website URL", null=True),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Company logo (square/standard)",
                        null=True,
                        upload_to="company_logos/",
                    ),
                ),
                (
                    "logo_wide",
                    models.ImageField(
                        blank=True,
                        help_text="Wide company logo for letterheads and PDFs",
                        null=True,
                        upload_to="company_logos/",
                    ),
                ),
                (
                    "test_company_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the test company used for testing (e.g., 'ABC Carpet Cleaning TEST IGNORE'). This company's name is preserved during data backports.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "kpi_daily_billable_hours_green",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Daily total billable hours across all staff above which the day is green",
                        max_digits=5,
                        verbose_name="Daily billable hours (green)",
                    ),
                ),
                (
                    "kpi_daily_billable_hours_amber",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Daily total billable hours across all staff above which the day is amber",
                        max_digits=5,
                        verbose_name="Daily billable hours (amber)",
                    ),
                ),
                (
                    "kpi_daily_gp_target",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Daily gross profit target in dollars",
                        max_digits=10,
                        verbose_name="Daily gross profit target",
                    ),
                ),
                (
                    "kpi_daily_shop_hours_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Target percentage of daily hours spent on shop (non-billable) jobs",
                        max_digits=5,
                        verbose_name="Daily shop hours percentage target",
                    ),
                ),
                (
                    "kpi_job_gp_target_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Target gross profit percentage for individual jobs",
                        max_digits=5,
                        verbose_name="Target GP % per job",
                    ),
                ),
                (
                    "kpi_daily_gp_green",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Daily gross profit above which the day is green",
                        max_digits=10,
                        verbose_name="Daily GP (green)",
                    ),
                ),
                (
                    "kpi_daily_gp_amber",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Daily gross profit above which the day is amber",
                        max_digits=10,
                        verbose_name="Daily GP (amber)",
                    ),
                ),
                (
                    "daily_approved_hours_target",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Target daily hours of newly-approved work flowing into the shop, used by the Sales Pipeline scoreboard",
                        max_digits=5,
                        verbose_name="Daily approved hours target",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Defaults",
                "verbose_name_plural": "Company Defaults",
                "db_table": "workflow_companydefaults",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="companydefaults_singleton"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AppError",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField()),
                ("data", models.JSONField(blank=True, null=True)),
                ("app", models.CharField(blank=True, max_length=50, null=True)),
                ("file", models.CharField(blank=True, max_length=200, null=True)),
                ("function", models.CharField(blank=True, max_length=100, null=True)),
                ("severity", models.IntegerField(default=40)),
                ("job_id", models.UUIDField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("session_replay_id", models.UUIDField(blank=True, null=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Error",
                "verbose_name_plural": "Application Errors",
                "db_table": "workflow_apperror",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp", "severity"],
                        name="workflow_apperror_time_sev_idx",
                    ),
                    models.Index(
                        fields=["resolved", "timestamp"],
                        name="workflow_apperror_res_time_idx",
                    ),
                    models.Index(fields=["app", "severity"], name="workflow_apperror_app_sev_idx"),
                    models.Index(
                        fields=["session_replay_id", "timestamp"],
                        name="workflow_aperr_replay_time_idx",
                    ),
                ],
            },
        ),
    ]
