# Generated by Django 6.0.7 on 2026-09-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_integration_settings_row"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companydefaults",
            old_name="annual_leave_loading",
            new_name="labour_cost_loading",
        ),
        migrations.AlterField(
            model_name="companydefaults",
            name="labour_cost_loading",
            field=models.DecimalField(
                decimal_places=2,
                default=20.0,
                help_text=(
                    "Percentage added to each base wage to recover paid non-worked time in "
                    "the labour cost assigned to worked hours. Include annual leave, public "
                    "holidays, sick leave, bereavement leave, and employer-paid ACC time; "
                    "measure the percentage for this business (20.00 turns $40.00 into $48.00)."
                ),
                max_digits=5,
            ),
        ),
    ]
