# Generated by Django 6.0.7 on 2026-09-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
        ("core", "0004_rename_annual_leave_loading"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="address_raw_json",
            field=models.JSONField(
                blank=True,
                help_text="Raw JSON data from Google Places for the address above",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="formatted_address",
            field=models.CharField(
                blank=True,
                help_text="The address Google matched, filled in when someone picks a candidate on this screen. Read-only: it records what was confirmed, not what was typed.",
                max_length=500,
                null=True,
                verbose_name="Address as Google has it",
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="google_place_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="region",
            field=models.CharField(
                blank=True,
                help_text="The region Google reports for the address above — 'Canterbury Region', or plainly 'Auckland'. Read-only, and the basis for which public holidays this business observes.",
                max_length=100,
                null=True,
                verbose_name="Region",
            ),
        ),
        migrations.AddConstraint(
            model_name="companydefaults",
            constraint=models.CheckConstraint(
                condition=models.Q(("formatted_address", ""), _negated=True),
                name="formatted_address_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="companydefaults",
            constraint=models.CheckConstraint(
                condition=models.Q(("google_place_id", ""), _negated=True),
                name="companydefaults_google_place_id_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="companydefaults",
            constraint=models.CheckConstraint(
                condition=models.Q(("region", ""), _negated=True), name="region_not_blank"
            ),
        ),
    ]
