# Generated by Django 6.0.7 on 2026-09-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_company_address_geocode"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="session_replay_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Record staff browser sessions for diagnostics. Recordings capture everything on screen and are visible to superusers only.",
            ),
        ),
    ]
