# Generated by Django 6.1.1 on 2026-09-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_session_replay_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="quote_expiry_days",
            field=models.PositiveSmallIntegerField(
                default=30, help_text="Days a quote sent to a customer stays valid."
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="session_replay_retention_days",
            field=models.PositiveSmallIntegerField(
                default=14,
                help_text="Days to keep session replays before the nightly purge deletes them and their stored events. This is the only limit on how long a recording of someone's screen survives.",
            ),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="phone_provider_recording_deletion_after_days",
            field=models.PositiveSmallIntegerField(default=31),
        ),
    ]
