# Generated by Django 6.1.1 on 2026-10-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_clear_placeholder_xero_tenant_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companydefaults",
            name="kpi_daily_gp_target",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Overhead per weekday in dollars: monthly operating expenses spread across the month's weekdays. A day on the KPI calendar is green once its gross profit covers this share; weekends are owed none of it.",
                max_digits=10,
                verbose_name="Daily gross profit target",
            ),
        ),
        migrations.AlterField(
            model_name="companydefaults",
            name="weekend_timesheets_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Show Saturday and Sunday in timesheet views and the KPI calendar (7-day week). Off = 5-day Mon-Fri. Weekend work is counted either way; this only decides whether the days are drawn.",
            ),
        ),
    ]
