# Generated by Django 6.1.1 on 2026-10-05 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_kpi_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="lunch_minutes",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Length of the unpaid lunch break in minutes, between 5 and 120.",
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(120),
                ],
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="lunch_start",
            field=models.TimeField(
                default="11:30", help_text="When the workshop's unpaid lunch break starts."
            ),
        ),
    ]
