# Generated by Django 6.1.1 on 2026-10-05 19:09

from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_lunch_break"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="afternoon_break_minutes",
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text="Length of the paid afternoon break in minutes: 5 to 120, or 0 for none.",
                validators=[apps.core.models.validate_break_minutes],
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="afternoon_break_start",
            field=models.TimeField(
                default="13:30", help_text="When the workshop's paid afternoon break starts."
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="morning_break_minutes",
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text="Length of the paid morning break in minutes: 5 to 120, or 0 for none.",
                validators=[apps.core.models.validate_break_minutes],
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="morning_break_start",
            field=models.TimeField(
                default="08:30", help_text="When the workshop's paid morning break starts."
            ),
        ),
        migrations.AlterField(
            model_name="companydefaults",
            name="lunch_minutes",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Length of the unpaid lunch break in minutes: 5 to 120, or 0 for none.",
                validators=[apps.core.models.validate_break_minutes],
            ),
        ),
    ]
