# Generated by Django 6.1.1 on 2026-10-06 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_standard_breaks"),
        ("job", "0017_costline_remote_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="break_job",
            field=models.ForeignKey(
                blank=True,
                help_text="Internal job every break is booked to: paid breaks and lunch.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="job.job",
            ),
        ),
    ]
