# Generated by Django 6.0.7 on 2026-08-25 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalformentry",
            name="entered_by",
        ),
        migrations.RemoveField(
            model_name="historicalformentry",
            name="form",
        ),
        migrations.RemoveField(
            model_name="historicalformentry",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalformentry",
            name="job",
        ),
        migrations.RemoveField(
            model_name="historicalformentry",
            name="staff",
        ),
        migrations.RemoveField(
            model_name="historicalprocedure",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalprocedure",
            name="job",
        ),
        migrations.AddField(
            model_name="form",
            name="category",
            field=models.CharField(
                choices=[
                    ("safety", "Safety"),
                    ("training", "Training"),
                    ("incident", "Incident"),
                    ("meeting", "Meeting"),
                    ("register", "Register"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="formentry",
            name="parent_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_entries",
                to="process.formentry",
            ),
        ),
        migrations.AddField(
            model_name="formentry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="procedure",
            name="category",
            field=models.CharField(
                choices=[
                    ("safety", "Safety"),
                    ("jsa", "JSA"),
                    ("training", "Training"),
                    ("reference", "Reference"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalForm",
        ),
        migrations.DeleteModel(
            name="HistoricalFormEntry",
        ),
        migrations.DeleteModel(
            name="HistoricalProcedure",
        ),
    ]
