# Generated by Django 6.0.3 on 2026-04-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0002_formentry_staff_historicalformentry_staff_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="form",
            table=None,
        ),
        migrations.AlterModelTable(
            name="formentry",
            table=None,
        ),
        migrations.AlterModelTable(
            name="historicalform",
            table=None,
        ),
        migrations.AlterModelTable(
            name="historicalformentry",
            table=None,
        ),
        migrations.AlterModelTable(
            name="historicalprocedure",
            table=None,
        ),
        migrations.AlterModelTable(
            name="procedure",
            table=None,
        ),
    ]
