# Generated by Django 6.0.7 on 2026-08-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0005_acknowledgement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formentry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
