# Generated by Django 6.0.4 on 2026-07-06 00:12

import uuid
from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_baseline"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_line_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("description", models.TextField()),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "line_amount_excl_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "line_amount_incl_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill Line Item",
                "verbose_name_plural": "Bill Line Items",
            },
        ),
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_id", models.UUIDField(unique=True)),
                (
                    "xero_tenant_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("number", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("AUTHORISED", "Authorised"),
                            ("DELETED", "Deleted"),
                            ("VOIDED", "Voided"),
                            ("PAID", "Paid"),
                        ],
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                (
                    "total_excl_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("tax", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_incl_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=10)),
                ("xero_last_modified", models.DateTimeField()),
                (
                    "xero_last_synced",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("raw_json", models.JSONField()),
                ("django_created_at", models.DateTimeField(auto_now_add=True)),
                ("django_updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Credit Note",
                "verbose_name_plural": "Credit Notes",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CreditNoteLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_line_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("description", models.TextField()),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "line_amount_excl_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "line_amount_incl_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Note Line Item",
                "verbose_name_plural": "Credit Note Line Items",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_id", models.UUIDField(unique=True)),
                (
                    "xero_tenant_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("number", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("AUTHORISED", "Authorised"),
                            ("DELETED", "Deleted"),
                            ("VOIDED", "Voided"),
                            ("PAID", "Paid"),
                        ],
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                (
                    "total_excl_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("tax", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_incl_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=10)),
                ("xero_last_modified", models.DateTimeField()),
                (
                    "xero_last_synced",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("raw_json", models.JSONField()),
                ("django_created_at", models.DateTimeField(auto_now_add=True)),
                ("django_updated_at", models.DateTimeField(auto_now=True)),
                ("online_url", models.URLField(blank=True, null=True)),
                ("billing_metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-date", "number"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_line_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("description", models.TextField()),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "line_amount_excl_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "line_amount_incl_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Line Item",
                "verbose_name_plural": "Invoice Line Items",
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_id", models.UUIDField(unique=True)),
                (
                    "xero_tenant_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SENT", "Sent"),
                            ("DECLINED", "Declined"),
                            ("ACCEPTED", "Accepted"),
                            ("INVOICED", "Invoiced"),
                            ("DELETED", "Deleted"),
                        ],
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                (
                    "total_excl_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_incl_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("xero_last_modified", models.DateTimeField(blank=True, null=True)),
                (
                    "xero_last_synced",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("number", models.CharField(blank=True, max_length=255, null=True)),
                ("online_url", models.URLField(blank=True, null=True)),
                ("raw_json", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_id", models.UUIDField(unique=True)),
                (
                    "xero_tenant_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("number", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("AUTHORISED", "Authorised"),
                            ("DELETED", "Deleted"),
                            ("VOIDED", "Voided"),
                            ("PAID", "Paid"),
                        ],
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                (
                    "total_excl_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("tax", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_incl_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=10)),
                ("xero_last_modified", models.DateTimeField()),
                (
                    "xero_last_synced",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("raw_json", models.JSONField()),
                ("django_created_at", models.DateTimeField(auto_now_add=True)),
                ("django_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="client.client"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill",
                "verbose_name_plural": "Bills",
                "ordering": ["-date", "number"],
            },
        ),
    ]
