# Generated by Django 6.0.7 on 2026-08-01 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("company", "0001_initial"),
        ("job", "0001_initial"),
        ("xero", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="billlineitem",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="xero.xeroaccount",
            ),
        ),
        migrations.AddField(
            model_name="billlineitem",
            name="bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="accounting.bill",
            ),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="company.company"
            ),
        ),
        migrations.AddField(
            model_name="creditnotelineitem",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="xero.xeroaccount",
            ),
        ),
        migrations.AddField(
            model_name="creditnotelineitem",
            name="credit_note",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="accounting.creditnote",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="company.company"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="job.job",
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="xero.xeroaccount",
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="accounting.invoice",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="company.company"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="job",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quote",
                to="job.job",
            ),
        ),
        migrations.AddConstraint(
            model_name="bill",
            constraint=models.CheckConstraint(
                condition=models.Q(("xero_tenant_id", ""), _negated=True),
                name="accounting_bill_xero_tenant_id_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnote",
            constraint=models.CheckConstraint(
                condition=models.Q(("xero_tenant_id", ""), _negated=True),
                name="accounting_creditnote_xero_tenant_id_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("online_url", ""), _negated=True),
                name="accounting_invoice_online_url_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("xero_tenant_id", ""), _negated=True),
                name="accounting_invoice_xero_tenant_id_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="quote",
            constraint=models.CheckConstraint(
                condition=models.Q(("number", ""), _negated=True),
                name="number_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="quote",
            constraint=models.CheckConstraint(
                condition=models.Q(("online_url", ""), _negated=True),
                name="accounting_quote_online_url_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="quote",
            constraint=models.CheckConstraint(
                condition=models.Q(("xero_tenant_id", ""), _negated=True),
                name="accounting_quote_xero_tenant_id_not_blank",
            ),
        ),
    ]
