# Generated by Django 6.0.4 on 2026-07-06 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_baseline"),
        ("company", "0001_baseline"),
        ("job", "0001_baseline"),
        ("workflow", "0001_baseline"),
    ]

    operations = [
        migrations.AddField(
            model_name="billlineitem",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workflow.xeroaccount",
            ),
        ),
        migrations.AddField(
            model_name="billlineitem",
            name="bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="accounting.bill",
            ),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="company.client"
            ),
        ),
        migrations.AddField(
            model_name="creditnotelineitem",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workflow.xeroaccount",
            ),
        ),
        migrations.AddField(
            model_name="creditnotelineitem",
            name="credit_note",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="accounting.creditnote",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="company.client"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="job.job",
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workflow.xeroaccount",
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="accounting.invoice",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="company.client"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="job",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quote",
                to="job.job",
            ),
        ),
    ]
