# Generated by Django 6.0.3 on 2026-04-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_quote_number"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bill",
            table=None,
        ),
        migrations.AlterModelTable(
            name="billlineitem",
            table=None,
        ),
        migrations.AlterModelTable(
            name="creditnote",
            table=None,
        ),
        migrations.AlterModelTable(
            name="creditnotelineitem",
            table=None,
        ),
        migrations.AlterModelTable(
            name="invoice",
            table=None,
        ),
        migrations.AlterModelTable(
            name="invoicelineitem",
            table=None,
        ),
        migrations.AlterModelTable(
            name="quote",
            table=None,
        ),
    ]
