# Generated by Django 6.0.4 on 2026-05-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_alter_bill_table_alter_billlineitem_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="billing_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
