# Minimal override of ninja_jwt.tokens: upstream annotates for_user with an
# instance-typed self so calling it as the classmethod it really is fails mypy.
# Covers only the surface v2 uses; extend as call sites appear.
from datetime import timedelta
from typing import Any, Self

from django.contrib.auth.base_user import AbstractBaseUser

class Token:
    token_type: str
    lifetime: timedelta
    def __init__(self, token: str | bytes | None = None, verify: bool = True) -> None: ...
    def __str__(self) -> str: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def verify(self) -> None: ...
    def set_exp(
        self,
        claim: str = "exp",
        from_time: Any | None = None,
        lifetime: timedelta | None = None,
    ) -> None: ...
    @classmethod
    def for_user(cls, user: AbstractBaseUser) -> Self: ...

class AccessToken(Token): ...

class RefreshToken(Token):
    no_copy_claims: tuple[str, ...]
    @property
    def access_token(self) -> AccessToken: ...

class SlidingToken(Token): ...
class UntypedToken(Token): ...
