# Generated by Django 6.0.4 on 2026-07-06 00:12

import uuid

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        # client_name_trgm_idx (gin_trgm_ops) below needs pg_trgm installed
        TrigramExtension(),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "xero_contact_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "xero_tenant_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("is_account_customer", models.BooleanField(default=False)),
                ("is_supplier", models.BooleanField(default=False)),
                (
                    "allow_jobs",
                    models.BooleanField(
                        default=True,
                        help_text="If False, this client cannot be selected as the client on a Job. Use for Xero contacts that must exist (tax authorities, internal accounts, etc.) but should never appear on a job. Automatically set to False when a client is archived or merged in Xero.",
                    ),
                ),
                ("xero_last_modified", models.DateTimeField()),
                ("raw_json", models.JSONField(blank=True, null=True)),
                (
                    "primary_contact_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "primary_contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "additional_contact_persons",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("django_created_at", models.DateTimeField(auto_now_add=True)),
                ("django_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "xero_last_synced",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "xero_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this client has been archived/merged in Xero",
                    ),
                ),
                (
                    "xero_merged_into_id",
                    models.CharField(
                        blank=True,
                        help_text="The Xero contact ID this client was merged into (temporary storage)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        help_text="The client this was merged into",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_from_clients",
                        to="company.client",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[],
            options={
                "db_table": "client_client",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("company.client",),
        ),
        migrations.CreateModel(
            name="ClientContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the contact person", max_length=255
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address of the contact",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Job title if it's helpful - else leave blank",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this is the primary contact for the client",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this contact",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft delete flag - inactive contacts are hidden from normal queries",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="The client this contact belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="company.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Contact",
                "verbose_name_plural": "Client Contacts",
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.CreateModel(
            name="ClientContactMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[("phone", "Phone"), ("email", "Email")], max_length=20
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("normalized_value", models.CharField(db_index=True, max_length=255)),
                ("label", models.CharField(blank=True, max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        choices=[("imported", "Imported"), ("local", "Local")],
                        default="local",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_methods",
                        to="company.client",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_methods",
                        to="company.clientcontact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Contact Method",
                "verbose_name_plural": "Client Contact Methods",
                "ordering": ["method_type", "-is_primary", "label", "value"],
            },
        ),
        migrations.CreateModel(
            name="SupplierPickupAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this address (e.g., 'Main Warehouse', 'City Branch')",
                        max_length=255,
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        help_text="Street address including unit/suite number",
                        max_length=255,
                    ),
                ),
                (
                    "suburb",
                    models.CharField(
                        blank=True,
                        help_text="Suburb or neighbourhood (e.g., Thorndon, Northcote Point)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="City (e.g., Wellington, Auckland)", max_length=100
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="State or province",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        help_text="Postal or ZIP code",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="New Zealand", help_text="Country name", max_length=100
                    ),
                ),
                (
                    "google_place_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Place ID for this address",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Latitude coordinate",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Longitude coordinate",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this is the primary pickup address for the supplier",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes (e.g., opening hours, access instructions)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft delete flag - inactive addresses are hidden from normal queries",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="The supplier this pickup address belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup_addresses",
                        to="company.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Pickup Address",
                "verbose_name_plural": "Supplier Pickup Addresses",
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierSearchAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("alias", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_search_aliases",
                        to="company.client",
                    ),
                ),
            ],
            options={
                "ordering": ["alias"],
            },
        ),
        migrations.AddIndex(
            model_name="client",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector("name", config="english"),
                name="client_name_fts_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="client_name_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddConstraint(
            model_name="clientcontact",
            constraint=models.UniqueConstraint(
                fields=("client", "name"), name="unique_client_contact_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="clientcontactmethod",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("client__isnull", False), ("contact__isnull", True)),
                    models.Q(("client__isnull", True), ("contact__isnull", False)),
                    _connector="OR",
                ),
                name="client_contact_method_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="clientcontactmethod",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("client__isnull", False), ("contact__isnull", True)
                ),
                fields=("client", "method_type", "normalized_value"),
                name="unique_client_contact_method_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="clientcontactmethod",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("client__isnull", True), ("contact__isnull", False)
                ),
                fields=("contact", "method_type", "normalized_value"),
                name="unique_contact_contact_method_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="clientcontactmethod",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("client__isnull", False),
                    ("contact__isnull", True),
                    ("is_primary", True),
                ),
                fields=("client", "method_type"),
                name="unique_client_primary_contact_method",
            ),
        ),
        migrations.AddConstraint(
            model_name="clientcontactmethod",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("client__isnull", True),
                    ("contact__isnull", False),
                    ("is_primary", True),
                ),
                fields=("contact", "method_type"),
                name="unique_contact_primary_contact_method",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierpickupaddress",
            constraint=models.UniqueConstraint(
                fields=("client", "name"), name="unique_supplier_pickup_address_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="suppliersearchalias",
            constraint=models.UniqueConstraint(
                fields=("client", "alias"),
                name="unique_supplier_search_alias_per_client",
            ),
        ),
    ]
