# Generated by Django 6.0.4 on 2026-07-06 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_rename_client_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientcontact",
            name="company",
            field=models.ForeignKey(
                help_text="The company this contact belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="clientcontact",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this is the primary contact for the company",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="allow_jobs",
            field=models.BooleanField(
                default=True,
                help_text="If False, this company cannot be selected as the company on a Job. Use for Xero contacts that must exist (tax authorities, internal accounts, etc.) but should never appear on a job. Automatically set to False when a company is archived or merged in Xero.",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="xero_archived",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this company has been archived/merged in Xero",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="xero_merged_into_id",
            field=models.CharField(
                blank=True,
                help_text="The Xero contact ID this company was merged into (temporary storage)",
                max_length=255,
                null=True,
            ),
        ),
    ]
