# Generated by Django 6.1.1 on 2026-10-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_backfill_xero_tenant_on_linked_companies"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="company",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("xero_contact_id__isnull", True),
                    ("xero_tenant_id__isnull", False),
                    _connector="OR",
                ),
                name="company_xero_contact_id_has_tenant",
            ),
        ),
    ]
