# Generated by Codex for KAN-278 Stage B.

from typing import Any

from django.db import migrations


def forwards(apps: Any, schema_editor: Any) -> None:
    Person = apps.get_model("company", "Person")
    CompanyPersonLink = apps.get_model("company", "CompanyPersonLink")
    ContactMethod = apps.get_model("company", "ContactMethod")
    Job = apps.get_model("job", "Job")
    PhoneCallRecord = apps.get_model("crm", "PhoneCallRecord")

    for link in CompanyPersonLink.objects.filter(person__isnull=True).order_by("id"):
        person = Person.objects.create(
            name=link.name,
            email=link.email,
            is_active=link.is_active,
        )
        link.person = person
        link.xero_name = link.name
        link.save(update_fields=["person", "xero_name", "updated_at"])

    person_by_link_id = dict(
        CompanyPersonLink.objects.exclude(person__isnull=True).values_list(
            "id", "person_id"
        )
    )

    for method in ContactMethod.objects.exclude(contact__isnull=True).order_by("id"):
        person_id = person_by_link_id[method.contact_id]
        method.person_id = person_id
        method.contact_id = None
        method.save(update_fields=["person", "contact", "updated_at"])

    for job in Job.objects.exclude(contact__isnull=True).order_by("id"):
        job.person_id = person_by_link_id[job.contact_id]
        job.save(update_fields=["person"])

    for call in PhoneCallRecord.objects.exclude(contact__isnull=True).order_by("id"):
        call.person_id = person_by_link_id[call.contact_id]
        call.save(update_fields=["person", "updated_at"])


def backwards(apps: Any, schema_editor: Any) -> None:
    CompanyPersonLink = apps.get_model("company", "CompanyPersonLink")
    ContactMethod = apps.get_model("company", "ContactMethod")
    Job = apps.get_model("job", "Job")
    PhoneCallRecord = apps.get_model("crm", "PhoneCallRecord")

    def link_id_for_person(
        *, person_id: Any, company_id: Any | None, owner: str
    ) -> Any:
        links = CompanyPersonLink.objects.filter(person_id=person_id)
        if company_id is not None:
            links = links.filter(company_id=company_id)
        link_ids = list(links.order_by("id").values_list("id", flat=True)[:2])
        if len(link_ids) == 1:
            return link_ids[0]
        if len(link_ids) == 0:
            raise RuntimeError(
                f"Cannot reverse people backfill for {owner}: "
                f"person_id={person_id} has no matching company link"
            )
        raise RuntimeError(
            f"Cannot reverse people backfill for {owner}: "
            f"person_id={person_id} maps to multiple company links"
        )

    for call in PhoneCallRecord.objects.exclude(person__isnull=True).order_by("id"):
        call.contact_id = link_id_for_person(
            person_id=call.person_id,
            company_id=call.company_id,
            owner=f"PhoneCallRecord {call.id}",
        )
        call.person_id = None
        call.save(update_fields=["contact", "person", "updated_at"])

    for job in Job.objects.exclude(person__isnull=True).order_by("id"):
        job.contact_id = link_id_for_person(
            person_id=job.person_id,
            company_id=job.company_id,
            owner=f"Job {job.id}",
        )
        job.person_id = None
        job.save(update_fields=["contact", "person"])

    for method in ContactMethod.objects.exclude(person__isnull=True).order_by("id"):
        method.contact_id = link_id_for_person(
            person_id=method.person_id,
            company_id=None,
            owner=f"ContactMethod {method.id}",
        )
        method.person_id = None
        method.save(update_fields=["contact", "person", "updated_at"])

    for link in CompanyPersonLink.objects.exclude(person__isnull=True).select_related(
        "person"
    ):
        link.name = link.person.name
        link.email = link.person.email
        link.is_active = link.person.is_active
        link.person_id = None
        link.xero_name = None
        link.save(
            update_fields=[
                "name",
                "email",
                "is_active",
                "person",
                "xero_name",
                "updated_at",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_person_link_structure"),
        ("job", "0004_job_person_alter_job_contact"),
        ("crm", "0005_phonecallrecord_person_alter_phonecallrecord_contact"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
