# Generated by Django 6.0.4 on 2026-07-08 22:47

from typing import Any

import django.db.models.deletion
from django.db import migrations, models


def repair_people_final_shape(apps: Any, schema_editor: Any) -> None:
    Person = apps.get_model("company", "Person")
    CompanyPersonLink = apps.get_model("company", "CompanyPersonLink")
    ContactMethod = apps.get_model("company", "ContactMethod")

    for link in CompanyPersonLink.objects.filter(person__isnull=True).iterator():
        person = Person.objects.create(
            name=link.name,
            email=link.email,
            is_active=link.is_active,
        )
        link.person = person
        if link.xero_name is None:
            link.xero_name = link.name
        link.save(update_fields=["person", "xero_name"])

    for method in ContactMethod.objects.filter(
        person__isnull=True, contact__isnull=False
    ).select_related("contact"):
        method.person_id = method.contact.person_id
        method.contact_id = None
        method.save(update_fields=["person", "contact", "updated_at"])

    # Collapse exact duplicates before final partial unique constraints land.
    owner_fields = [
        ("company_id", ContactMethod.objects.filter(company__isnull=False)),
        ("person_id", ContactMethod.objects.filter(person__isnull=False)),
    ]
    for owner_field, queryset in owner_fields:
        duplicates = (
            queryset.values(owner_field, "method_type", "normalized_value")
            .annotate(count=models.Count("id"))
            .filter(count__gt=1)
        )
        for duplicate in duplicates:
            matches = queryset.filter(
                **{
                    owner_field: duplicate[owner_field],
                    "method_type": duplicate["method_type"],
                    "normalized_value": duplicate["normalized_value"],
                }
            ).order_by("-is_primary", "created_at", "id")
            keep = matches.first()
            matches.exclude(pk=keep.pk).delete()

        primary_duplicates = (
            queryset.filter(is_primary=True)
            .values(owner_field, "method_type")
            .annotate(count=models.Count("id"))
            .filter(count__gt=1)
        )
        for duplicate in primary_duplicates:
            matches = queryset.filter(
                **{
                    owner_field: duplicate[owner_field],
                    "method_type": duplicate["method_type"],
                    "is_primary": True,
                }
            ).order_by("created_at", "id")
            keep = matches.first()
            matches.exclude(pk=keep.pk).update(is_primary=False)

    missing_links = CompanyPersonLink.objects.filter(person__isnull=True).count()
    missing_methods = ContactMethod.objects.filter(
        person__isnull=True, contact__isnull=False
    ).count()
    ownerless_methods = ContactMethod.objects.filter(
        company__isnull=True, person__isnull=True
    ).count()
    overowned_methods = ContactMethod.objects.filter(
        company__isnull=False, person__isnull=False
    ).count()
    if missing_links or missing_methods or ownerless_methods or overowned_methods:
        raise RuntimeError(
            "Final people schema repair failed: "
            f"missing_links={missing_links}, missing_methods={missing_methods}, "
            f"ownerless_methods={ownerless_methods}, "
            f"overowned_methods={overowned_methods}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_backfill_person"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companypersonlink",
            options={
                "ordering": ["-is_primary", "person__name"],
                "verbose_name": "Company Person Link",
                "verbose_name_plural": "Company Person Links",
            },
        ),
        migrations.RemoveConstraint(
            model_name="companypersonlink",
            name="unique_company_contact_name",
        ),
        migrations.RemoveField(
            model_name="company",
            name="additional_contact_persons",
        ),
        migrations.RemoveField(
            model_name="company",
            name="primary_contact_email",
        ),
        migrations.RemoveField(
            model_name="company",
            name="primary_contact_name",
        ),
        migrations.RunPython(repair_people_final_shape, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="contactmethod",
            name="contact",
        ),
        migrations.AlterField(
            model_name="companypersonlink",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_links",
                to="company.person",
            ),
        ),
        migrations.AddConstraint(
            model_name="companypersonlink",
            constraint=models.UniqueConstraint(
                fields=("company", "person"), name="unique_company_person_link"
            ),
        ),
        migrations.AddConstraint(
            model_name="companypersonlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("xero_name__isnull", False)),
                fields=("company", "xero_name"),
                name="unique_company_person_link_xero_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactmethod",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("company__isnull", False), ("person__isnull", True)),
                    models.Q(("company__isnull", True), ("person__isnull", False)),
                    _connector="OR",
                ),
                name="contact_method_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactmethod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("company__isnull", False)),
                fields=("company", "method_type", "normalized_value"),
                name="unique_company_contact_method_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactmethod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("person__isnull", False)),
                fields=("person", "method_type", "normalized_value"),
                name="unique_person_contact_method_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactmethod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("company__isnull", False), ("is_primary", True)),
                fields=("company", "method_type"),
                name="unique_company_primary_contact_method",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactmethod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True), ("person__isnull", False)),
                fields=("person", "method_type"),
                name="unique_person_primary_contact_method",
            ),
        ),
        migrations.RemoveField(
            model_name="companypersonlink",
            name="email",
        ),
        migrations.RemoveField(
            model_name="companypersonlink",
            name="name",
        ),
    ]
