# Generated by Django 6.0.4 on 2026-07-12 08:32

from typing import Any

from django.db import migrations


def delete_unreferenced_people(apps: Any, schema_editor: Any) -> None:
    Person = apps.get_model("company", "Person")
    Person.objects.filter(
        company_links__isnull=True,
        contact_methods__isnull=True,
        jobs__isnull=True,
        phone_calls__isnull=True,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_alter_companypersonlink_options_and_more"),
        ("crm", "0006_remove_phonecallrecord_contact_and_more"),
        ("job", "0006_rename_job_event_people_company_terms"),
    ]

    operations = [
        migrations.RunPython(delete_unreferenced_people, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="companypersonlink",
            name="unique_company_person_link_xero_name",
        ),
        migrations.RemoveField(
            model_name="companypersonlink",
            name="xero_name",
        ),
    ]
