# Generated by Django 6.0.7 on 2026-08-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0012_text_unset_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="allow_jobs",
            field=models.BooleanField(
                default=True,
                help_text="If False, this company cannot be selected as the company on a Job. Use for Xero contacts that must exist (tax authorities, internal accounts, etc.) but should never appear on a job. Automatically set to False when a company is archived or merged in Xero, and restored on un-archive (merged companies stay blocked).",
            ),
        ),
    ]
