# Generated by Django 6.0.4 on 2026-07-06 00:12

import uuid
from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_baseline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this provider", max_length=100
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="API Key for this AI Provider",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "default",
                    models.BooleanField(
                        default=False, help_text="Use this provider as the default"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        help_text="Specific model name (e.g., gemini-2.5-flash-lite-preview-06-17)",
                        max_length=100,
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("Claude", "Anthropic"),
                            ("Gemini", "Google"),
                            ("Mistral", "Mistral"),
                            ("OpenAI", "Openai"),
                        ],
                        help_text="Type of AI provider",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Provider",
                "verbose_name_plural": "AI Providers",
            },
        ),
        migrations.CreateModel(
            name="AppError",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField()),
                ("data", models.JSONField(blank=True, null=True)),
                ("app", models.CharField(blank=True, max_length=50, null=True)),
                ("file", models.CharField(blank=True, max_length=200, null=True)),
                ("function", models.CharField(blank=True, max_length=100, null=True)),
                ("severity", models.IntegerField(default=40)),
                ("job_id", models.UUIDField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Error",
                "verbose_name_plural": "Application Errors",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ServiceAPIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Service name (e.g., 'Chatbot Service')",
                        max_length=100,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="API key for authentication",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Service API Key",
                "verbose_name_plural": "Service API Keys",
            },
        ),
        migrations.CreateModel(
            name="XeroAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_id", models.UUIDField(unique=True)),
                (
                    "xero_tenant_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "account_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("account_name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "account_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("tax_type", models.CharField(blank=True, max_length=50, null=True)),
                ("enable_payments", models.BooleanField(default=False)),
                ("xero_last_modified", models.DateTimeField()),
                (
                    "xero_last_synced",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("raw_json", models.JSONField()),
                ("django_created_at", models.DateTimeField(auto_now_add=True)),
                ("django_updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="XeroPayRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_id", models.UUIDField(unique=True)),
                ("xero_tenant_id", models.CharField(max_length=255)),
                ("payroll_calendar_id", models.UUIDField(blank=True, null=True)),
                ("period_start_date", models.DateField()),
                ("period_end_date", models.DateField()),
                ("payment_date", models.DateField()),
                (
                    "pay_run_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "pay_run_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "total_pay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("raw_json", models.JSONField()),
                ("xero_last_modified", models.DateTimeField()),
                (
                    "xero_last_synced",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("django_created_at", models.DateTimeField(auto_now_add=True)),
                ("django_updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Xero Pay Run",
                "verbose_name_plural": "Xero Pay Runs",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="XeroSyncCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_key", models.CharField(max_length=50, unique=True)),
                ("last_modified", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="XeroError",
            fields=[
                (
                    "apperror_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="workflow.apperror",
                    ),
                ),
                ("entity", models.CharField(max_length=100)),
                ("reference_id", models.CharField(max_length=255)),
                ("kind", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Xero Error",
                "verbose_name_plural": "Xero Errors",
            },
            bases=("workflow.apperror",),
        ),
        migrations.CreateModel(
            name="SessionReplayRecording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("initial_path", models.CharField(max_length=500)),
                ("latest_path", models.CharField(max_length=500)),
                ("job_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("viewport_width", models.PositiveIntegerField(blank=True, null=True)),
                ("viewport_height", models.PositiveIntegerField(blank=True, null=True)),
                ("event_count", models.PositiveIntegerField(default=0)),
                ("compressed_bytes", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="session_replay_recordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionReplayChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("first_event_timestamp_ms", models.BigIntegerField()),
                ("last_event_timestamp_ms", models.BigIntegerField()),
                ("event_count", models.PositiveIntegerField()),
                ("compressed_bytes", models.PositiveIntegerField()),
                ("storage_path", models.CharField(max_length=500)),
                ("sha256", models.CharField(max_length=64)),
                ("path", models.CharField(max_length=500)),
                ("job_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("viewport_width", models.PositiveIntegerField(blank=True, null=True)),
                ("viewport_height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="workflow.sessionreplayrecording",
                    ),
                ),
            ],
            options={
                "ordering": ["recording_id", "sequence"],
            },
        ),
        migrations.AddField(
            model_name="apperror",
            name="session_replay",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="app_errors",
                to="workflow.sessionreplayrecording",
            ),
        ),
        migrations.CreateModel(
            name="XeroApp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=64)),
                ("client_id", models.CharField(max_length=128, unique=True)),
                ("client_secret", models.CharField(max_length=256)),
                ("redirect_uri", models.CharField(max_length=512)),
                (
                    "webhook_key",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("tenant_id", models.CharField(blank=True, max_length=100, null=True)),
                ("token_type", models.CharField(blank=True, max_length=50, null=True)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("scope", models.TextField(blank=True, null=True)),
                ("day_remaining", models.IntegerField(blank=True, null=True)),
                ("minute_remaining", models.IntegerField(blank=True, null=True)),
                ("snapshot_at", models.DateTimeField(blank=True, null=True)),
                ("last_429_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="xero_app_only_one_active",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="XeroPayItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "xero_id",
                    models.CharField(
                        blank=True,
                        help_text="Xero's UUID for this pay item",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "xero_tenant_id",
                    models.CharField(
                        blank=True,
                        help_text="Xero tenant this pay item belongs to",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'Ordinary Time', 'Annual Leave')",
                        max_length=100,
                    ),
                ),
                (
                    "uses_leave_api",
                    models.BooleanField(
                        help_text="True = Xero Leave API, False = Xero Timesheets API"
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rate multiplier from Xero (1.0, 1.5, 2.0, etc.). NULL for leave types.",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "xero_last_modified",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last modified timestamp from Xero",
                        null=True,
                    ),
                ),
                (
                    "xero_last_synced",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="When we last synced this record from Xero",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Xero Pay Item",
                "verbose_name_plural": "Xero Pay Items",
                "ordering": ["uses_leave_api", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "uses_leave_api"),
                        name="unique_pay_item_name_per_api",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="XeroPaySlip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_id", models.UUIDField(unique=True)),
                ("xero_tenant_id", models.CharField(max_length=255)),
                ("xero_employee_id", models.UUIDField()),
                (
                    "employee_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gross_earnings",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "net_pay",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "timesheet_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Hours from timesheet_earnings_lines (actual worked hours)",
                        max_digits=8,
                    ),
                ),
                (
                    "leave_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Hours from leave_earnings_lines (sick, annual, etc.)",
                        max_digits=8,
                    ),
                ),
                ("raw_json", models.JSONField()),
                ("xero_last_modified", models.DateTimeField()),
                (
                    "xero_last_synced",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("django_created_at", models.DateTimeField(auto_now_add=True)),
                ("django_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pay_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pay_slips",
                        to="workflow.xeropayrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xero Pay Slip",
                "verbose_name_plural": "Xero Pay Slips",
                "ordering": ["-pay_run__payment_date", "employee_name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyDefaults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "company_acronym",
                    models.CharField(
                        blank=True,
                        help_text="Short acronym for the company (e.g., 'MSM' for Morris Sheetmetal)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "time_markup",
                    models.DecimalField(decimal_places=2, default=0.3, max_digits=5),
                ),
                (
                    "materials_markup",
                    models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
                ),
                (
                    "wage_rate",
                    models.DecimalField(decimal_places=2, default=32.0, max_digits=6),
                ),
                (
                    "annual_leave_loading",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        help_text="Percentage added to base_wage_rate to get costing wage_rate (20.00 = 20%)",
                        max_digits=5,
                    ),
                ),
                (
                    "workshop_efficiency_factor",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.750"),
                        help_text="Fraction of clocked workshop hours that count as schedulable productive output (e.g. 0.750 = 75%). Accounts for breaks, tool changes, idle time. Applied to per-day capacity in the workshop scheduler after subtracting booked time/leave.",
                        max_digits=4,
                    ),
                ),
                (
                    "financial_year_start_month",
                    models.IntegerField(
                        default=4,
                        help_text="Month the financial year starts (1=January, 4=April, 7=July, etc.)",
                    ),
                ),
                (
                    "starting_job_number",
                    models.IntegerField(
                        default=1,
                        help_text="Helper field to set the starting job number based on the latest paper job",
                    ),
                ),
                (
                    "starting_po_number",
                    models.IntegerField(
                        default=1,
                        help_text="Helper field to set the starting purchase order number",
                    ),
                ),
                (
                    "po_prefix",
                    models.CharField(
                        default="PO-",
                        help_text="Prefix for purchase order numbers (e.g., PO-, JO-)",
                        max_length=10,
                    ),
                ),
                (
                    "master_quote_template_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the master Google Sheets quote template",
                        null=True,
                    ),
                ),
                (
                    "master_quote_template_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Sheets ID for the quote template",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "gdrive_quotes_folder_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the Google Drive folder for storing quotes",
                        null=True,
                    ),
                ),
                (
                    "gdrive_quotes_folder_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Drive folder ID for storing quotes",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "google_shared_drive_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Shared Drive ID for the company shared drive",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "gdrive_how_we_work_folder_id",
                    models.CharField(
                        blank=True,
                        help_text="Folder ID for '01 - How we work' (policies, basics)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "gdrive_sops_folder_id",
                    models.CharField(
                        blank=True,
                        help_text="Folder ID for '02 - SOPs' (standard operating procedures)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "gdrive_reference_library_folder_id",
                    models.CharField(
                        blank=True,
                        help_text="Folder ID for '03 - Reference Library' (reference documents, forms, registers)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "accounting_provider",
                    models.CharField(
                        default="xero",
                        help_text="Active accounting integration: 'xero' or 'myob'",
                        max_length=20,
                    ),
                ),
                (
                    "xero_tenant_id",
                    models.CharField(
                        blank=True,
                        help_text="The Xero tenant ID to use for this company",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "xero_shortcode",
                    models.CharField(
                        blank=True,
                        help_text="Xero organisation shortcode for deep linking (e.g., '!8-5Xl')",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "enable_xero_sync",
                    models.BooleanField(
                        default=True,
                        help_text="Gate for Xero sync. Defaults True (prod). Dev fixture sets False; seed_xero_from_database sets True after prod IDs are cleared.",
                    ),
                ),
                (
                    "xero_automated_day_floor",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Reserve this many Xero daily API calls for user-initiated work. Automated sync aborts when the active Xero app reports remaining daily calls at or below this value.",
                    ),
                ),
                (
                    "xero_payroll_calendar_name",
                    models.CharField(
                        default="Weekly",
                        help_text="Name of Xero Payroll calendar to use (e.g., 'Weekly 2025')",
                        max_length=100,
                    ),
                ),
                (
                    "xero_payroll_calendar_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Cached Xero Payroll calendar ID (set by xero --setup command)",
                        null=True,
                    ),
                ),
                (
                    "xero_payroll_start_date",
                    models.DateField(
                        blank=True,
                        help_text="Date Xero payroll went live — reconciliation ignores data before this",
                        null=True,
                    ),
                ),
                (
                    "weekend_timesheets_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Show Saturday and Sunday in timesheet views (7-day week). Off = 5-day Mon-Fri.",
                    ),
                ),
                (
                    "job_delta_soft_fail",
                    models.BooleanField(
                        default=True,
                        help_text="When enabled, job delta checksum mismatches are logged and recorded without blocking the save. Disable to reject stale updates.",
                    ),
                ),
                ("mon_start", models.TimeField(default="07:00")),
                ("mon_end", models.TimeField(default="15:00")),
                ("tue_start", models.TimeField(default="07:00")),
                ("tue_end", models.TimeField(default="15:00")),
                ("wed_start", models.TimeField(default="07:00")),
                ("wed_end", models.TimeField(default="15:00")),
                ("thu_start", models.TimeField(default="07:00")),
                ("thu_end", models.TimeField(default="15:00")),
                ("fri_start", models.TimeField(default="07:00")),
                ("fri_end", models.TimeField(default="15:00")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_xero_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="The last time Xero data was synchronized",
                        null=True,
                    ),
                ),
                (
                    "last_xero_deep_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="The last time a deep Xero sync was performed (looking back 90 days)",
                        null=True,
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(
                        blank=True,
                        help_text="Street address line 1",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True,
                        help_text="Street address line 2 (optional)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "suburb",
                    models.CharField(
                        blank=True,
                        help_text="Suburb (for NZ addresses)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, help_text="City", max_length=100, null=True
                    ),
                ),
                (
                    "post_code",
                    models.CharField(
                        blank=True,
                        help_text="Postal/ZIP code",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="New Zealand", help_text="Country name", max_length=100
                    ),
                ),
                (
                    "company_email",
                    models.EmailField(
                        blank=True,
                        help_text="Company contact email address",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "company_url",
                    models.URLField(
                        blank=True, help_text="Company website URL", null=True
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Company logo (square/standard)",
                        null=True,
                        upload_to="company_logos/",
                    ),
                ),
                (
                    "logo_wide",
                    models.ImageField(
                        blank=True,
                        help_text="Wide company logo for letterheads and PDFs",
                        null=True,
                        upload_to="company_logos/",
                    ),
                ),
                (
                    "test_client_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the test client used for testing (e.g., 'ABC Carpet Cleaning TEST IGNORE'). This client's name is preserved during data backports.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "kpi_daily_billable_hours_green",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Daily total billable hours across all staff above which the day is green",
                        max_digits=5,
                        verbose_name="Daily billable hours (green)",
                    ),
                ),
                (
                    "kpi_daily_billable_hours_amber",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Daily total billable hours across all staff above which the day is amber",
                        max_digits=5,
                        verbose_name="Daily billable hours (amber)",
                    ),
                ),
                (
                    "kpi_daily_gp_target",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Daily gross profit target in dollars",
                        max_digits=10,
                        verbose_name="Daily gross profit target",
                    ),
                ),
                (
                    "kpi_daily_shop_hours_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Target percentage of daily hours spent on shop (non-billable) jobs",
                        max_digits=5,
                        verbose_name="Daily shop hours percentage target",
                    ),
                ),
                (
                    "kpi_job_gp_target_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Target gross profit percentage for individual jobs",
                        max_digits=5,
                        verbose_name="Target GP % per job",
                    ),
                ),
                (
                    "kpi_daily_gp_green",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Daily gross profit above which the day is green",
                        max_digits=10,
                        verbose_name="Daily GP (green)",
                    ),
                ),
                (
                    "kpi_daily_gp_amber",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Daily gross profit above which the day is amber",
                        max_digits=10,
                        verbose_name="Daily GP (amber)",
                    ),
                ),
                (
                    "daily_approved_hours_target",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Target daily hours of newly-approved work flowing into the shop, used by the Sales Pipeline scoreboard",
                        max_digits=5,
                        verbose_name="Daily approved hours target",
                    ),
                ),
                (
                    "shop_client",
                    models.ForeignKey(
                        help_text="Internal client used for tracking shop work.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="company.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Defaults",
                "verbose_name_plural": "Company Defaults",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="companydefaults_singleton"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchTelemetryEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("search", "Search"), ("click", "Click")],
                        max_length=20,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("kanban", "Kanban"),
                            ("stock", "Stock"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=100)),
                ("query", models.CharField(blank=True, max_length=255)),
                ("normalized_query", models.CharField(blank=True, max_length=255)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("result_count", models.PositiveIntegerField(default=0)),
                ("returned_count", models.PositiveIntegerField(default=0)),
                ("returned_result_ids", models.JSONField(blank=True, default=list)),
                ("selected_result_id", models.CharField(blank=True, max_length=255)),
                ("selected_label", models.CharField(blank=True, max_length=255)),
                ("selected_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "source_event_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_telemetry_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["domain", "event_type", "-occurred_at"],
                        name="wf_search_domain_event_idx",
                    ),
                    models.Index(
                        fields=["domain", "normalized_query", "-occurred_at"],
                        name="wf_search_domain_query_idx",
                    ),
                    models.Index(
                        fields=["source", "-occurred_at"],
                        name="workflow_search_source_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="sessionreplayrecording",
            index=models.Index(
                fields=["user", "-started_at"], name="workflow_replay_user_start_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionreplayrecording",
            index=models.Index(
                fields=["started_at"], name="workflow_replay_started_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionreplayrecording",
            index=models.Index(
                fields=["job_id", "-started_at"], name="workflow_replay_job_start_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionreplaychunk",
            index=models.Index(
                fields=["recording", "sequence"], name="workflow_chunk_record_seq_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionreplaychunk",
            index=models.Index(
                fields=["created_at"], name="workflow_chunk_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionreplaychunk",
            constraint=models.UniqueConstraint(
                fields=("recording", "sequence"),
                name="workflow_session_replay_chunk_recording_sequence_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="apperror",
            index=models.Index(
                fields=["timestamp", "severity"], name="workflow_apperror_time_sev_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apperror",
            index=models.Index(
                fields=["resolved", "timestamp"], name="workflow_apperror_res_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apperror",
            index=models.Index(
                fields=["app", "severity"], name="workflow_apperror_app_sev_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apperror",
            index=models.Index(
                fields=["session_replay", "timestamp"],
                name="workflow_aperr_replay_time_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="xeropayslip",
            unique_together={("pay_run", "xero_employee_id")},
        ),
    ]
