# Generated by Django 6.0.4 on 2026-07-06 00:12

import uuid
from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    replaces = [
        ("workflow", "0001_initial"),
        ("workflow", "0003_companydefaults_alter_client_xero_contact_id"),
        ("workflow", "0004_companydefaults_company_name"),
        ("workflow", "0005_remove_companydefaults_id_and_more"),
        ("workflow", "0006_quotepricing"),
        ("workflow", "0007_remove_historicaljob_client_name_and_more"),
        ("workflow", "0008_remove_jobpricing_job_pricing_number"),
        ("workflow", "0009_historicaljob_job_is_valid_job_job_is_valid"),
        ("workflow", "0010_remove_historicaljob_job_name_remove_job_job_name"),
        ("workflow", "0011_remove_timeentry_minutes_timeentry_description_and_more"),
        ("workflow", "0012_alter_timeentry_staff"),
        ("workflow", "0013_alter_timeentry_date"),
        ("workflow", "0014_historicaljob_quote_acceptance_date_and_more"),
        ("workflow", "0015_historicaljob_delivery_date_job_delivery_date"),
        ("workflow", "0016_materialentry_item_code"),
        ("workflow", "0017_materialentry_comments"),
        ("workflow", "0018_rename_cost_adjustmententry_cost_adjustment_and_more"),
        ("workflow", "0019_alter_historicaljob_delivery_date_and_more"),
        ("workflow", "0020_historicaljob_material_gauge_quantity_and_more"),
        ("workflow", "0021_alter_historicaljob_description_and_more"),
        ("workflow", "0022_alter_historicaljob_description_and_more"),
        ("workflow", "0023_alter_historicaljob_contact_phone_and_more"),
        ("workflow", "0024_alter_jobpricing_options_jobpricing_revision_number"),
        ("workflow", "0025_historicaljob_latest_estimate_pricing_and_more"),
        ("workflow", "0026_alter_job_latest_estimate_pricing_and_more"),
        ("workflow", "0027_remove_jobpricing_job"),
        ("workflow", "0028_jobpricing_job"),
        ("workflow", "0029_alter_jobpricing_job"),
        ("workflow", "0030_alter_jobpricing_job"),
        ("workflow", "0031_alter_jobpricing_job"),
        ("workflow", "0032_alter_job_latest_estimate_pricing_and_more"),
        ("workflow", "0033_remove_jobpricing_job_and_more"),
        ("workflow", "0034_alter_materialentry_quantity_and_more"),
        ("workflow", "0035_alter_adjustmententry_comments_and_more"),
        ("workflow", "0036_historicalstaff_hours_fri_historicalstaff_hours_mon_and_more"),
        ("workflow", "0037_remove_historicalstaff_charge_out_rate_and_more"),
        ("workflow", "0038_historicaljob_shop_job_job_shop_job"),
        ("workflow", "0039_historicaljob_charge_out_rate_job_charge_out_rate"),
        ("workflow", "0040_alter_historicaljob_charge_out_rate_and_more"),
        ("workflow", "0041_timeentry_wage_rate_multiplier"),
        ("workflow", "0042_jobpricing_job"),
        ("workflow", "0043_alter_jobpricing_job"),
        ("workflow", "0044_remove_timeentry_mins_per_item_timeentry_hours_and_more"),
        ("workflow", "0045_remove_timeentry_minutes"),
        ("workflow", "0046_alter_adjustmententry_options_alter_bill_options_and_more"),
        ("workflow", "0047_rename_last_modified_bill_xero_last_modified_and_more"),
        ("workflow", "0048_billlineitem_xero_id_invoicelineitem_xero_id"),
        ("workflow", "0049_companydefaults_created_at_and_more"),
        ("workflow", "0050_alter_historicalstaff_created_at_and_more"),
        ("workflow", "0051_alter_historicalstaff_updated_at_and_more"),
        ("workflow", "0052_alter_jobpricing_job"),
        ("workflow", "0053_alter_job_latest_estimate_pricing_and_more"),
        ("workflow", "0054_remove_historicaljob_shop_job_remove_job_shop_job_and_more"),
        ("workflow", "0055_alter_historicaljob_description_and_more"),
        ("workflow", "0056_rename_total_bill_total_excl_tax_and_more"),
        ("workflow", "0057_rename_line_amount_billlineitem_line_amount_excl_tax_and_more"),
        ("workflow", "0058_alter_billlineitem_options_and_more"),
        ("workflow", "0059_rename_creditlineitem_creditnotelineitem_and_more"),
        ("workflow", "0060_xerojournal_xerojournallineitem"),
        ("workflow", "0061_xerojournallineitem_xero_last_modified"),
        ("workflow", "0062_xerojournal_xero_last_modified"),
        ("workflow", "0063_rename_date_xerojournal_journal_date"),
        ("workflow", "0064_remove_xerojournallineitem_xero_last_modified"),
        ("workflow", "0065_alter_xerojournal_journal_number"),
        ("workflow", "0066_jobfile"),
        ("workflow", "0067_jobfile_status"),
        ("workflow", "0067_supplier_purchase_purchaseline_and_more"),
        ("workflow", "0068_jobevent"),
        ("workflow", "0068_purchase_created_at_purchase_updated_at_and_more"),
        ("workflow", "0069_rename_user_jobevent_staff"),
        ("workflow", "0070_jobevent_event_type"),
        ("workflow", "0071_alter_jobevent_timestamp"),
        ("workflow", "0072_merge_20250113_1626"),
        ("workflow", "0073_jobpricing_is_historical"),
        ("workflow", "0074_bill_xero_last_synced_client_xero_last_synced_and_more"),
        ("workflow", "0075_invoice_online_url_quote"),
        ("workflow", "0075_jobfile_print_on_jobsheet"),
        ("workflow", "0076_invoice_job"),
        ("workflow", "0076_remove_jobpricing_pricing_type_and_more"),
        ("workflow", "0077_alter_quote_job"),
        ("workflow", "0078_alter_quote_job"),
        ("workflow", "0079_merge_20250207_1950"),
        ("workflow", "0080_alter_historicaljob_material_gauge_quantity_and_more"),
        ("workflow", "0080_historicaljob_complex_job_job_complex_job_and_more"),
        ("workflow", "0081_add_last_xero_sync_to_company_defaults"),
        ("workflow", "0082_add_last_xero_deep_sync"),
        ("workflow", "0083_setup_xero_sync_service"),
        ("workflow", "0084_cleanup_company_defaults"),
        ("workflow", "0085_auto_20250302_2205"),
        ("workflow", "0086_alter_historicaljob_contact_person_and_more"),
        ("workflow", "0087_companydefaults_is_primary"),
        ("workflow", "0088_merge_20250305_0549"),
        ("workflow", "0089_companydefaults_starting_job_number_and_more"),
        ("workflow", "0090_alter_staff_options"),
        ("workflow", "0091_rename_coolected_historicaljob_collected_and_more"),
        ("workflow", "0093_historicaljob_notes_job_notes"),
        ("workflow", "0094_migrate_material_gauge_to_notes"),
        ("workflow", "0095_alter_staff_options_and_more"),
        ("workflow", "0096_merge_20250310_2039"),
        ("workflow", "0097_alter_historicalstaff_ims_payroll_id_and_more"),
        ("workflow", "0098_alter_historicalstaff_ims_payroll_id_and_more"),
        ("workflow", "0099_historicaljob_created_by_job_created_by"),
        ("workflow", "0100_companydefaults_xero_tenant_id"),
        ("workflow", "0101_merge_20250317_1527"),
        ("workflow", "0102_add_job_to_purchase_line"),
        ("workflow", "0103_companydefaults_starting_po_number"),
        ("workflow", "0104_alter_purchaseorder_expected_delivery"),
        ("workflow", "0105_add_xero_fields_to_purchase_order"),
        ("workflow", "0106_add_price_tbc_to_purchase_order_line"),
        ("workflow", "0107_purchaseorder_online_url_purchaseorder_raw_json"),
        ("workflow", "0108_xeroaccount_xero_last_synced"),
        ("workflow", "0109_stock"),
        ("workflow", "0110_purchaseorder_reference"),
        ("workflow", "0111_alter_timeentry_minutes_per_item"),
        ("workflow", "0112_remove_purchaseline_purchase_and_more"),
        ("workflow", "0113_remove_stock_source_id_materialentry_source_stock_and_more"),
        ("workflow", "0114_stock_is_active"),
        ("workflow", "0115_alter_stock_id"),
        ("workflow", "0116_stock_alloy_stock_location_stock_metal_type_and_more"),
        ("workflow", "0117_alter_stock_metal_type"),
        ("workflow", "0118_alter_materialentry_source_stock"),
        ("workflow", "0119_alter_materialentry_source_stock"),
        ("workflow", "0120_add_purchase_order_deleted_status"),
        ("workflow", "0121_purchaseorderline_alloy_purchaseorderline_location_and_more"),
        ("workflow", "0122_companydefaults_anthropic_api_key_and_more"),
        ("workflow", "0123_alter_purchaseorder_order_date_and_more"),
        ("workflow", "0124_companydefaults_billable_threshold_amber_and_more"),
        ("workflow", "0125_normalize_po_numbers"),
        ("workflow", "0126_alter_purchaseorder_order_date"),
        ("workflow", "0127_remove_purchaseorder_raw_json_and_more"),
        ("workflow", "0128_stock_retail_rate"),
        ("workflow", "0129_companydefaults_gemini_api_key_stock_job_and_more"),
        ("workflow", "0130_purchaseorderline_raw_line_data_stock_job_and_more"),
        ("workflow", "0131_aiprovider_companydefaults_anthropic_api_key_and_more"),
        ("workflow", "0132_stock_job_stock_source_purchase_order_line"),
        ("workflow", "0133_bill_xero_tenant_id_client_xero_tenant_id_and_more"),
        ("workflow", "0134_alter_purchaseorder_order_date"),
        ("workflow", "0135_job_people_staff_icon_and_more"),
        ("workflow", "0136_rename_job_status"),
        ("workflow", "0137_auto_20250508_2012"),
        ("workflow", "0138_stock_job_stock_source_purchase_order_line"),
        ("workflow", "0139_bill_xero_tenant_id_client_xero_tenant_id_and_more"),
        ("workflow", "0140_remove_staff_groups_remove_staff_user_permissions_and_more"),
        ("workflow", "0141_remove_timeentry_job_pricing_remove_timeentry_staff_and_more"),
        ("workflow", "0142_remove_historicaljob_client_and_more"),
        ("workflow", "0143_alter_stock_job"),
        ("workflow", "0144_remove_adjustmententry_job_pricing_and_more"),
        ("workflow", "0145_fix_jobpricing_chain"),
        ("workflow", "0146_delete_adjustmententry_delete_materialentry"),
        ("workflow", "0147_companydefaults_po_prefix"),
        ("workflow", "0148_client_primary_contact_email_and_more"),
        ("workflow", "0149_remove_client_secondary_contact_email_and_more"),
        ("workflow", "0150_client_all_phones"),
        ("workflow", "0151_remove_purchaseline_purchase_and_more"),
        ("workflow", "0152_remove_companydefaults_anthropic_api_key_and_more"),
        ("workflow", "0153_delete_client_client"),
        ("workflow", "0154_auto_20250604_1054"),
        ("workflow", "0155_remove_stock_job_remove_stock_source_parent_stock_and_more"),
        ("workflow", "0156_remove_stock_job_remove_stock_source_parent_stock_and_more"),
        ("workflow", "0157_remove_bill_client_remove_billlineitem_bill_and_more"),
        ("workflow", "0158_delete_bill_delete_billlineitem_delete_creditnote_and_more"),
        ("workflow", "0159_add_shop_client_name_field"),
        ("workflow", "0160_alter_aiprovider_provider_type"),
        ("workflow", "0161_companydefaults_gdrive_quotes_folder_id_and_more"),
        ("workflow", "0162_alter_companydefaults_gdrive_quotes_folder_id_and_more"),
        ("workflow", "0163_rename_active_to_default_add_model_name"),
        ("workflow", "0164_serviceapikey"),
        ("workflow", "0165_app_error_models"),
        ("workflow", "0166_alter_apperror_options_alter_xeroerror_options_and_more"),
        ("workflow", "0167_alter_aiprovider_table"),
        ("workflow", "0168_enhance_app_error_model"),
        ("workflow", "0169_remove_aiprovider_company_field"),
        ("workflow", "0170_companydefaults_xero_annual_leave_earnings_rate_id_and_more"),
        ("workflow", "0171_protect_critical_fks"),
        ("workflow", "0172_alter_xerotoken_scope"),
        ("workflow", "0173_add_test_client_name_field"),
        ("workflow", "0174_add_xero_payroll_models"),
        ("workflow", "0175_make_payroll_fields_required"),
        ("workflow", "0176_add_company_address_fields"),
        ("workflow", "0177_add_company_email_url"),
        ("workflow", "0178_add_company_acronym"),
        ("workflow", "0179_add_xero_payroll_calendar_id"),
        ("workflow", "0180_alter_xerotoken_scope"),
        ("workflow", "0181_payrollcategory"),
        ("workflow", "0182_populate_payroll_categories"),
        ("workflow", "0183_remove_payroll_fields_from_companydefaults"),
        ("workflow", "0184_add_xero_shortcode"),
        ("workflow", "0185_fix_unpaid_leave_and_remove_posts_to_xero"),
        ("workflow", "0186_simplify_payroll_category"),
        ("workflow", "0188_delete_payrollcategory"),
        ("workflow", "0189_add_xero_payroll_calendar_id"),
        ("workflow", "0190_add_openai_provider_type"),
        ("workflow", "0191_add_annual_leave_loading"),
        ("workflow", "0192_add_financial_year_start_month"),
        ("workflow", "0193_add_job_gp_target_percentage"),
        ("workflow", "0194_add_profit_thresholds"),
        ("workflow", "0195_rename_kpi_threshold_fields"),
        ("workflow", "0196_alter_companydefaults_kpi_daily_billable_hours_amber_and_more"),
        ("workflow", "0197_alter_xerotoken_scope"),
        ("workflow", "0198_add_shared_drive_fields"),
        ("workflow", "0199_populate_shared_drive_ids"),
        ("workflow", "0200_xerosynccursor"),
        ("workflow", "0201_add_xero_payroll_start_date"),
        ("workflow", "0202_populate_xero_payroll_start_date"),
        ("workflow", "0203_companydefaults_solo"),
        ("workflow", "0204_alter_xerotoken_scope"),
        ("workflow", "0205_companydefaults_company_phone"),
        ("workflow", "0206_companydefaults_logo_companydefaults_logo_wide"),
        ("workflow", "0207_unique_pay_item_name"),
        ("workflow", "0208_enable_xero_sync"),
        ("workflow", "0209_add_accounting_provider"),
        ("workflow", "0209_rename_workflow_ap_timesta_ae5a69_idx_workflow_ap_timesta_a3d224_idx_and_more"),
        ("workflow", "0210_merge_20260412_2225"),
        ("workflow", "0211_apperror_app_error_resolved_msg_idx"),
        ("workflow", "0212_companydefaults_singleton_check"),
        ("workflow", "0213_companydefaults_weekend_timesheets_enabled"),
        ("workflow", "0214_cachestate"),
        ("workflow", "0215_add_daily_approved_hours_target"),
        ("workflow", "0216_workshop_efficiency_factor"),
        ("workflow", "0217_xeroapp"),
        ("workflow", "0218_populate_xero_app"),
        ("workflow", "0219_delete_xerotoken"),
        ("workflow", "0221_drop_django_apscheduler_tables"),
        ("workflow", "0222_remove_xero_sync_service"),
        ("workflow", "0223_delete_cachestate"),
        ("workflow", "0224_remove_app_error_resolved_msg_idx"),
        ("workflow", "0225_alter_companydefaults_annual_leave_loading"),
        ("workflow", "0227_delete_xero_journal"),
        ("workflow", "0228_session_replay"),
        ("workflow", "0230_session_replay_file_storage"),
        ("workflow", "0231_companydefaults_shop_client_fk"),
        ("workflow", "0232_rename_workflow_ap_timesta_a3d224_idx_workflow_apperror_time_sev_idx_and_more"),
        ("workflow", "0233_companydefaults_job_delta_soft_fail_and_more"),
        ("workflow", "0234_nullable_company_defaults_optional_urls"),
        ("workflow", "0235_searchtelemetryevent"),
        ("workflow", "0236_remove_companydefaults_charge_out_rate"),
        ("workflow", "0237_remove_companydefaults_phone_fields"),
    ]

    dependencies = [
        ("client", "0001_baseline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this provider", max_length=100
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="API Key for this AI Provider",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "default",
                    models.BooleanField(
                        default=False, help_text="Use this provider as the default"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        help_text="Specific model name (e.g., gemini-2.5-flash-lite-preview-06-17)",
                        max_length=100,
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("Claude", "Anthropic"),
                            ("Gemini", "Google"),
                            ("Mistral", "Mistral"),
                            ("OpenAI", "Openai"),
                        ],
                        help_text="Type of AI provider",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Provider",
                "verbose_name_plural": "AI Providers",
            },
        ),
        migrations.CreateModel(
            name="AppError",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField()),
                ("data", models.JSONField(blank=True, null=True)),
                ("app", models.CharField(blank=True, max_length=50, null=True)),
                ("file", models.CharField(blank=True, max_length=200, null=True)),
                ("function", models.CharField(blank=True, max_length=100, null=True)),
                ("severity", models.IntegerField(default=40)),
                ("job_id", models.UUIDField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Error",
                "verbose_name_plural": "Application Errors",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ServiceAPIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Service name (e.g., 'Chatbot Service')",
                        max_length=100,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="API key for authentication",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Service API Key",
                "verbose_name_plural": "Service API Keys",
            },
        ),
        migrations.CreateModel(
            name="XeroAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_id", models.UUIDField(unique=True)),
                (
                    "xero_tenant_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "account_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("account_name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "account_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("tax_type", models.CharField(blank=True, max_length=50, null=True)),
                ("enable_payments", models.BooleanField(default=False)),
                ("xero_last_modified", models.DateTimeField()),
                (
                    "xero_last_synced",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("raw_json", models.JSONField()),
                ("django_created_at", models.DateTimeField(auto_now_add=True)),
                ("django_updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="XeroPayRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_id", models.UUIDField(unique=True)),
                ("xero_tenant_id", models.CharField(max_length=255)),
                ("payroll_calendar_id", models.UUIDField(blank=True, null=True)),
                ("period_start_date", models.DateField()),
                ("period_end_date", models.DateField()),
                ("payment_date", models.DateField()),
                (
                    "pay_run_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "pay_run_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "total_pay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("raw_json", models.JSONField()),
                ("xero_last_modified", models.DateTimeField()),
                (
                    "xero_last_synced",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("django_created_at", models.DateTimeField(auto_now_add=True)),
                ("django_updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Xero Pay Run",
                "verbose_name_plural": "Xero Pay Runs",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="XeroSyncCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_key", models.CharField(max_length=50, unique=True)),
                ("last_modified", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="XeroError",
            fields=[
                (
                    "apperror_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="workflow.apperror",
                    ),
                ),
                ("entity", models.CharField(max_length=100)),
                ("reference_id", models.CharField(max_length=255)),
                ("kind", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Xero Error",
                "verbose_name_plural": "Xero Errors",
            },
            bases=("workflow.apperror",),
        ),
        migrations.CreateModel(
            name="SessionReplayRecording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("initial_path", models.CharField(max_length=500)),
                ("latest_path", models.CharField(max_length=500)),
                ("job_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("viewport_width", models.PositiveIntegerField(blank=True, null=True)),
                ("viewport_height", models.PositiveIntegerField(blank=True, null=True)),
                ("event_count", models.PositiveIntegerField(default=0)),
                ("compressed_bytes", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="session_replay_recordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionReplayChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("first_event_timestamp_ms", models.BigIntegerField()),
                ("last_event_timestamp_ms", models.BigIntegerField()),
                ("event_count", models.PositiveIntegerField()),
                ("compressed_bytes", models.PositiveIntegerField()),
                ("storage_path", models.CharField(max_length=500)),
                ("sha256", models.CharField(max_length=64)),
                ("path", models.CharField(max_length=500)),
                ("job_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("viewport_width", models.PositiveIntegerField(blank=True, null=True)),
                ("viewport_height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="workflow.sessionreplayrecording",
                    ),
                ),
            ],
            options={
                "ordering": ["recording_id", "sequence"],
            },
        ),
        migrations.AddField(
            model_name="apperror",
            name="session_replay",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="app_errors",
                to="workflow.sessionreplayrecording",
            ),
        ),
        migrations.CreateModel(
            name="XeroApp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=64)),
                ("client_id", models.CharField(max_length=128, unique=True)),
                ("client_secret", models.CharField(max_length=256)),
                ("redirect_uri", models.CharField(max_length=512)),
                (
                    "webhook_key",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("tenant_id", models.CharField(blank=True, max_length=100, null=True)),
                ("token_type", models.CharField(blank=True, max_length=50, null=True)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("scope", models.TextField(blank=True, null=True)),
                ("day_remaining", models.IntegerField(blank=True, null=True)),
                ("minute_remaining", models.IntegerField(blank=True, null=True)),
                ("snapshot_at", models.DateTimeField(blank=True, null=True)),
                ("last_429_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="xero_app_only_one_active",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="XeroPayItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "xero_id",
                    models.CharField(
                        blank=True,
                        help_text="Xero's UUID for this pay item",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "xero_tenant_id",
                    models.CharField(
                        blank=True,
                        help_text="Xero tenant this pay item belongs to",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'Ordinary Time', 'Annual Leave')",
                        max_length=100,
                    ),
                ),
                (
                    "uses_leave_api",
                    models.BooleanField(
                        help_text="True = Xero Leave API, False = Xero Timesheets API"
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rate multiplier from Xero (1.0, 1.5, 2.0, etc.). NULL for leave types.",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "xero_last_modified",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last modified timestamp from Xero",
                        null=True,
                    ),
                ),
                (
                    "xero_last_synced",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="When we last synced this record from Xero",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Xero Pay Item",
                "verbose_name_plural": "Xero Pay Items",
                "ordering": ["uses_leave_api", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "uses_leave_api"),
                        name="unique_pay_item_name_per_api",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="XeroPaySlip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_id", models.UUIDField(unique=True)),
                ("xero_tenant_id", models.CharField(max_length=255)),
                ("xero_employee_id", models.UUIDField()),
                (
                    "employee_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gross_earnings",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "net_pay",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "timesheet_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Hours from timesheet_earnings_lines (actual worked hours)",
                        max_digits=8,
                    ),
                ),
                (
                    "leave_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Hours from leave_earnings_lines (sick, annual, etc.)",
                        max_digits=8,
                    ),
                ),
                ("raw_json", models.JSONField()),
                ("xero_last_modified", models.DateTimeField()),
                (
                    "xero_last_synced",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("django_created_at", models.DateTimeField(auto_now_add=True)),
                ("django_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pay_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pay_slips",
                        to="workflow.xeropayrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xero Pay Slip",
                "verbose_name_plural": "Xero Pay Slips",
                "ordering": ["-pay_run__payment_date", "employee_name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyDefaults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "company_acronym",
                    models.CharField(
                        blank=True,
                        help_text="Short acronym for the company (e.g., 'MSM' for Morris Sheetmetal)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "time_markup",
                    models.DecimalField(decimal_places=2, default=0.3, max_digits=5),
                ),
                (
                    "materials_markup",
                    models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
                ),
                (
                    "wage_rate",
                    models.DecimalField(decimal_places=2, default=32.0, max_digits=6),
                ),
                (
                    "annual_leave_loading",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        help_text="Percentage added to base_wage_rate to get costing wage_rate (20.00 = 20%)",
                        max_digits=5,
                    ),
                ),
                (
                    "workshop_efficiency_factor",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.750"),
                        help_text="Fraction of clocked workshop hours that count as schedulable productive output (e.g. 0.750 = 75%). Accounts for breaks, tool changes, idle time. Applied to per-day capacity in the workshop scheduler after subtracting booked time/leave.",
                        max_digits=4,
                    ),
                ),
                (
                    "financial_year_start_month",
                    models.IntegerField(
                        default=4,
                        help_text="Month the financial year starts (1=January, 4=April, 7=July, etc.)",
                    ),
                ),
                (
                    "starting_job_number",
                    models.IntegerField(
                        default=1,
                        help_text="Helper field to set the starting job number based on the latest paper job",
                    ),
                ),
                (
                    "starting_po_number",
                    models.IntegerField(
                        default=1,
                        help_text="Helper field to set the starting purchase order number",
                    ),
                ),
                (
                    "po_prefix",
                    models.CharField(
                        default="PO-",
                        help_text="Prefix for purchase order numbers (e.g., PO-, JO-)",
                        max_length=10,
                    ),
                ),
                (
                    "master_quote_template_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the master Google Sheets quote template",
                        null=True,
                    ),
                ),
                (
                    "master_quote_template_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Sheets ID for the quote template",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "gdrive_quotes_folder_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the Google Drive folder for storing quotes",
                        null=True,
                    ),
                ),
                (
                    "gdrive_quotes_folder_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Drive folder ID for storing quotes",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "google_shared_drive_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Shared Drive ID for the company shared drive",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "gdrive_how_we_work_folder_id",
                    models.CharField(
                        blank=True,
                        help_text="Folder ID for '01 - How we work' (policies, basics)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "gdrive_sops_folder_id",
                    models.CharField(
                        blank=True,
                        help_text="Folder ID for '02 - SOPs' (standard operating procedures)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "gdrive_reference_library_folder_id",
                    models.CharField(
                        blank=True,
                        help_text="Folder ID for '03 - Reference Library' (reference documents, forms, registers)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "accounting_provider",
                    models.CharField(
                        default="xero",
                        help_text="Active accounting integration: 'xero' or 'myob'",
                        max_length=20,
                    ),
                ),
                (
                    "xero_tenant_id",
                    models.CharField(
                        blank=True,
                        help_text="The Xero tenant ID to use for this company",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "xero_shortcode",
                    models.CharField(
                        blank=True,
                        help_text="Xero organisation shortcode for deep linking (e.g., '!8-5Xl')",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "enable_xero_sync",
                    models.BooleanField(
                        default=True,
                        help_text="Gate for Xero sync. Defaults True (prod). Dev fixture sets False; seed_xero_from_database sets True after prod IDs are cleared.",
                    ),
                ),
                (
                    "xero_automated_day_floor",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Reserve this many Xero daily API calls for user-initiated work. Automated sync aborts when the active Xero app reports remaining daily calls at or below this value.",
                    ),
                ),
                (
                    "xero_payroll_calendar_name",
                    models.CharField(
                        default="Weekly",
                        help_text="Name of Xero Payroll calendar to use (e.g., 'Weekly 2025')",
                        max_length=100,
                    ),
                ),
                (
                    "xero_payroll_calendar_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Cached Xero Payroll calendar ID (set by xero --setup command)",
                        null=True,
                    ),
                ),
                (
                    "xero_payroll_start_date",
                    models.DateField(
                        blank=True,
                        help_text="Date Xero payroll went live — reconciliation ignores data before this",
                        null=True,
                    ),
                ),
                (
                    "weekend_timesheets_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Show Saturday and Sunday in timesheet views (7-day week). Off = 5-day Mon-Fri.",
                    ),
                ),
                (
                    "job_delta_soft_fail",
                    models.BooleanField(
                        default=True,
                        help_text="When enabled, job delta checksum mismatches are logged and recorded without blocking the save. Disable to reject stale updates.",
                    ),
                ),
                ("mon_start", models.TimeField(default="07:00")),
                ("mon_end", models.TimeField(default="15:00")),
                ("tue_start", models.TimeField(default="07:00")),
                ("tue_end", models.TimeField(default="15:00")),
                ("wed_start", models.TimeField(default="07:00")),
                ("wed_end", models.TimeField(default="15:00")),
                ("thu_start", models.TimeField(default="07:00")),
                ("thu_end", models.TimeField(default="15:00")),
                ("fri_start", models.TimeField(default="07:00")),
                ("fri_end", models.TimeField(default="15:00")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_xero_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="The last time Xero data was synchronized",
                        null=True,
                    ),
                ),
                (
                    "last_xero_deep_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="The last time a deep Xero sync was performed (looking back 90 days)",
                        null=True,
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(
                        blank=True,
                        help_text="Street address line 1",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True,
                        help_text="Street address line 2 (optional)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "suburb",
                    models.CharField(
                        blank=True,
                        help_text="Suburb (for NZ addresses)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, help_text="City", max_length=100, null=True
                    ),
                ),
                (
                    "post_code",
                    models.CharField(
                        blank=True,
                        help_text="Postal/ZIP code",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="New Zealand", help_text="Country name", max_length=100
                    ),
                ),
                (
                    "company_email",
                    models.EmailField(
                        blank=True,
                        help_text="Company contact email address",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "company_url",
                    models.URLField(
                        blank=True, help_text="Company website URL", null=True
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Company logo (square/standard)",
                        null=True,
                        upload_to="company_logos/",
                    ),
                ),
                (
                    "logo_wide",
                    models.ImageField(
                        blank=True,
                        help_text="Wide company logo for letterheads and PDFs",
                        null=True,
                        upload_to="company_logos/",
                    ),
                ),
                (
                    "test_client_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the test client used for testing (e.g., 'ABC Carpet Cleaning TEST IGNORE'). This client's name is preserved during data backports.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "kpi_daily_billable_hours_green",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Daily total billable hours across all staff above which the day is green",
                        max_digits=5,
                        verbose_name="Daily billable hours (green)",
                    ),
                ),
                (
                    "kpi_daily_billable_hours_amber",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Daily total billable hours across all staff above which the day is amber",
                        max_digits=5,
                        verbose_name="Daily billable hours (amber)",
                    ),
                ),
                (
                    "kpi_daily_gp_target",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Daily gross profit target in dollars",
                        max_digits=10,
                        verbose_name="Daily gross profit target",
                    ),
                ),
                (
                    "kpi_daily_shop_hours_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Target percentage of daily hours spent on shop (non-billable) jobs",
                        max_digits=5,
                        verbose_name="Daily shop hours percentage target",
                    ),
                ),
                (
                    "kpi_job_gp_target_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Target gross profit percentage for individual jobs",
                        max_digits=5,
                        verbose_name="Target GP % per job",
                    ),
                ),
                (
                    "kpi_daily_gp_green",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Daily gross profit above which the day is green",
                        max_digits=10,
                        verbose_name="Daily GP (green)",
                    ),
                ),
                (
                    "kpi_daily_gp_amber",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Daily gross profit above which the day is amber",
                        max_digits=10,
                        verbose_name="Daily GP (amber)",
                    ),
                ),
                (
                    "daily_approved_hours_target",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Target daily hours of newly-approved work flowing into the shop, used by the Sales Pipeline scoreboard",
                        max_digits=5,
                        verbose_name="Daily approved hours target",
                    ),
                ),
                (
                    "shop_client",
                    models.ForeignKey(
                        help_text="Internal client used for tracking shop work.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="client.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Defaults",
                "verbose_name_plural": "Company Defaults",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="companydefaults_singleton"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchTelemetryEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("search", "Search"), ("click", "Click")],
                        max_length=20,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("kanban", "Kanban"),
                            ("stock", "Stock"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=100)),
                ("query", models.CharField(blank=True, max_length=255)),
                ("normalized_query", models.CharField(blank=True, max_length=255)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("result_count", models.PositiveIntegerField(default=0)),
                ("returned_count", models.PositiveIntegerField(default=0)),
                ("returned_result_ids", models.JSONField(blank=True, default=list)),
                ("selected_result_id", models.CharField(blank=True, max_length=255)),
                ("selected_label", models.CharField(blank=True, max_length=255)),
                ("selected_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "source_event_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_telemetry_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["domain", "event_type", "-occurred_at"],
                        name="wf_search_domain_event_idx",
                    ),
                    models.Index(
                        fields=["domain", "normalized_query", "-occurred_at"],
                        name="wf_search_domain_query_idx",
                    ),
                    models.Index(
                        fields=["source", "-occurred_at"],
                        name="workflow_search_source_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="sessionreplayrecording",
            index=models.Index(
                fields=["user", "-started_at"], name="workflow_replay_user_start_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionreplayrecording",
            index=models.Index(
                fields=["started_at"], name="workflow_replay_started_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionreplayrecording",
            index=models.Index(
                fields=["job_id", "-started_at"], name="workflow_replay_job_start_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionreplaychunk",
            index=models.Index(
                fields=["recording", "sequence"], name="workflow_chunk_record_seq_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionreplaychunk",
            index=models.Index(
                fields=["created_at"], name="workflow_chunk_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionreplaychunk",
            constraint=models.UniqueConstraint(
                fields=("recording", "sequence"),
                name="workflow_session_replay_chunk_recording_sequence_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="apperror",
            index=models.Index(
                fields=["timestamp", "severity"], name="workflow_apperror_time_sev_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apperror",
            index=models.Index(
                fields=["resolved", "timestamp"], name="workflow_apperror_res_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apperror",
            index=models.Index(
                fields=["app", "severity"], name="workflow_apperror_app_sev_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apperror",
            index=models.Index(
                fields=["session_replay", "timestamp"],
                name="workflow_aperr_replay_time_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="xeropayslip",
            unique_together={("pay_run", "xero_employee_id")},
        ),
    ]
