# Generated by Django 6.0.4 on 2026-07-06 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_alter_clientcontact_company_and_more"),
        ("workflow", "0005_rename_shop_client_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companydefaults",
            name="shop_company",
            field=models.ForeignKey(
                help_text="Internal company used for tracking shop work.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="companydefaults",
            name="test_company_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the test company used for testing (e.g., 'ABC Carpet Cleaning TEST IGNORE'). This company's name is preserved during data backports.",
                max_length=255,
                null=True,
            ),
        ),
    ]
