# Generated by Django 6.0.4 on 2026-07-15 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0009_rename_remaining_crm_telemetry_sources"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="xeroapp",
            name="tenant_id",
        ),
    ]
