# Generated by Django 5.2.4 on 2026-07-16 00:00

from uuid import UUID

from django.db import migrations, models


def populate_connected_install_theme(apps, _schema_editor):
    """Backfill connected installs; setup handles unconnected installations."""
    CompanyDefaults = apps.get_model("workflow", "CompanyDefaults")
    XeroApp = apps.get_model("workflow", "XeroApp")

    company_defaults = CompanyDefaults.objects.first()
    if company_defaults is None or company_defaults.xero_tenant_id is None:
        return

    has_usable_oauth = (
        XeroApp.objects.filter(is_active=True)
        .exclude(refresh_token__isnull=True)
        .exclude(refresh_token="")
        .exists()
    )
    if not has_usable_oauth:
        return

    from apps.workflow.accounting.document_theme_service import (
        resolve_sales_branding_theme,
    )
    from apps.workflow.accounting.registry import get_provider

    selected_theme = resolve_sales_branding_theme(get_provider(), None)
    if selected_theme is None:
        raise RuntimeError(
            "Xero returned no branding themes while configuring the sales "
            "branding theme migration."
        )

    CompanyDefaults.objects.filter(pk=company_defaults.pk).update(
        xero_sales_branding_theme_id=UUID(selected_theme.external_id)
    )


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0010_remove_xeroapp_tenant_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="xero_sales_branding_theme_id",
            field=models.UUIDField(
                blank=True,
                help_text=(
                    "Branding theme applied to every quote and sales invoice "
                    "created in Xero. Select a theme containing the required "
                    "terms and conditions; it is configured during Xero setup "
                    "and required before sales documents can be created."
                ),
                null=True,
                verbose_name="Xero sales branding theme",
            ),
        ),
        migrations.RunPython(
            populate_connected_install_theme,
            migrations.RunPython.noop,
        ),
    ]
