# Generated by Django 5.2.4 on 2026-07-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0010_remove_xeroapp_tenant_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="xero_sales_branding_theme_id",
            field=models.UUIDField(
                blank=True,
                help_text=(
                    "Branding theme applied to every quote and sales invoice "
                    "created in Xero. Select a theme containing the required "
                    "terms and conditions; if unset, the first Xero theme is "
                    "selected automatically when the next sales document is "
                    "created."
                ),
                null=True,
                verbose_name="Xero sales branding theme",
            ),
        ),
    ]
