# Generated by Django 6.0.7 on 2026-07-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0012_use_latest_gemini_flash_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotebookLmLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Menu item name", max_length=100)),
                ("url", models.URLField(help_text="NotebookLM notebook URL")),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="Show this link in the training menu"
                    ),
                ),
                (
                    "restriction",
                    models.CharField(
                        choices=[
                            ("none", "All staff"),
                            ("superuser", "Superusers only"),
                        ],
                        default="none",
                        help_text="Who may see this link in the menu",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Menu display order"),
                ),
            ],
            options={
                "verbose_name": "NotebookLM Link",
                "verbose_name_plural": "NotebookLM Links",
                "ordering": ["order", "name"],
            },
        ),
    ]
