# Generated by Django 6.0.7 on 2026-07-31 21:21

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0018_text_unset_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="gst_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.1500"),
                help_text="Sales tax rate applied to amounts DocketWorks quotes before Xero has issued an invoice, as a fraction (0.1500 = 15% NZ GST). Xero remains authoritative for tax on invoices that exist.",
                max_digits=5,
            ),
        ),
    ]
