# Generated by Django 6.0.7 on 2026-08-01 07:24

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0012_text_unset_constraints"),
        ("workflow", "0019_company_defaults_gst_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companydefaults",
            name="gst_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.1500"),
                help_text="Sales tax rate applied to amounts DocketWorks quotes before Xero has issued an invoice, as a fraction (0.1500 = 15% NZ GST). Xero remains authoritative for tax on invoices that exist.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("0.9999")),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="companydefaults",
            constraint=models.CheckConstraint(
                condition=models.Q(("gst_rate__gte", 0), ("gst_rate__lt", 1)),
                name="companydefaults_gst_rate_is_a_fraction",
            ),
        ),
    ]
