# Generated by Django 5.2 on 2025-12-31 04:18

import uuid
from decimal import Decimal

import django.utils.timezone
from django.db import migrations, models


def create_seed_xero_pay_items(apps, schema_editor):
    """Create seed XeroPayItem records with fixed UUIDs matching production.

    These UUIDs are canonical — they match the PKs used by production
    Job.default_xero_pay_item and CostLine.xero_pay_item FKs. This means
    backups can exclude XeroPayItem and the FK references still resolve.
    """
    XeroPayItem = apps.get_model("workflow", "XeroPayItem")

    # UUIDs match production records referenced by Jobs/CostLines
    seed_items = [
        {
            "id": "3829750d-1528-440c-8260-0ce4a7b620f3",
            "name": "Ordinary Time",
            "uses_leave_api": False,
            "multiplier": Decimal("1.00"),
        },
        {
            "id": "adc9d1ba-5ba7-4692-b71f-785e36ce35c8",
            "name": "Time and one half",
            "uses_leave_api": False,
            "multiplier": Decimal("1.50"),
        },
        {
            "id": "8ad696a0-f0cd-42b4-9700-39a942d9ccfd",
            "name": "Double Time",
            "uses_leave_api": False,
            "multiplier": Decimal("2.00"),
        },
        {
            "id": "90909bb3-7c5f-473a-8b51-e4d5cfcb3a5a",
            "name": "Annual Leave",
            "uses_leave_api": True,
            "multiplier": Decimal("0.00"),
        },
        {
            "id": "e678e692-312d-4f38-b9f8-31c84d6d6ba8",
            "name": "Sick Leave",
            "uses_leave_api": True,
            "multiplier": Decimal("1.00"),
        },
        {
            "id": "b58930e0-2bb9-4dde-b7ec-5a16ea78b4cb",
            "name": "Unpaid Leave",
            "uses_leave_api": True,
            "multiplier": Decimal("0.00"),
        },
        {
            "id": "c4848bba-737e-45a8-adaa-61cd072a84ca",
            "name": "Bereavement Leave",
            "uses_leave_api": True,
            "multiplier": Decimal("1.00"),
        },
    ]

    created = 0
    for item in seed_items:
        if not XeroPayItem.objects.filter(id=item["id"]).exists():
            XeroPayItem.objects.create(**item)
            created += 1
    print(
        f"  Created {created} seed XeroPayItem records ({len(seed_items) - created} already existed)"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0186_simplify_payroll_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="XeroPayItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "xero_id",
                    models.CharField(
                        blank=True,
                        help_text="Xero's UUID for this pay item",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "xero_tenant_id",
                    models.CharField(
                        blank=True,
                        help_text="Xero tenant this pay item belongs to",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'Ordinary Time', 'Annual Leave')",
                        max_length=100,
                    ),
                ),
                (
                    "uses_leave_api",
                    models.BooleanField(
                        help_text="True = Xero Leave API, False = Xero Timesheets API"
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rate multiplier from Xero (1.0, 1.5, 2.0, etc.). NULL for leave types.",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "xero_last_modified",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last modified timestamp from Xero",
                        null=True,
                    ),
                ),
                (
                    "xero_last_synced",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="When we last synced this record from Xero",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Xero Pay Item",
                "verbose_name_plural": "Xero Pay Items",
                "db_table": "workflow_xeropayitem",
                "ordering": ["uses_leave_api", "name"],
            },
        ),
        migrations.RunPython(create_seed_xero_pay_items, migrations.RunPython.noop),
    ]
