# Generated by Django 6.0.1 on 2026-03-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0199_populate_shared_drive_ids"),
    ]

    operations = [
        migrations.CreateModel(
            name="XeroSyncCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_key", models.CharField(max_length=50, unique=True)),
                ("last_modified", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
