# Generated by Django 6.0.1 on 2026-03-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0200_xerosynccursor"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="xero_payroll_start_date",
            field=models.DateField(
                blank=True,
                help_text="Date Xero payroll went live — reconciliation ignores data before this",
                null=True,
            ),
        ),
    ]
