# Generated by Django 6.0.1 on 2026-03-12 07:06

from datetime import date

from django.db import migrations


def set_payroll_start_date(apps, schema_editor):
    CompanyDefaults = apps.get_model("workflow", "CompanyDefaults")
    for defaults in CompanyDefaults.objects.all():
        if not defaults.xero_payroll_start_date:
            defaults.xero_payroll_start_date = date(2025, 8, 1)
            defaults.save(update_fields=["xero_payroll_start_date"])


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0201_add_xero_payroll_start_date"),
    ]

    operations = [
        migrations.RunPython(set_payroll_start_date, migrations.RunPython.noop),
    ]
