# Generated by Django 6.0.3 on 2026-03-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0203_companydefaults_solo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xerotoken",
            name="scope",
            field=models.TextField(
                default="offline_access openid profile email accounting.contacts accounting.invoices accounting.attachments accounting.settings projects payroll.timesheets payroll.payruns payroll.payslip payroll.employees payroll.settings"
            ),
        ),
    ]
