# Generated by Django 6.0.3 on 2026-03-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0204_alter_xerotoken_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="company_phone",
            field=models.CharField(
                blank=True, help_text="Company phone number", max_length=30, null=True
            ),
        ),
    ]
