# Generated by Django 6.0.3 on 2026-03-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0205_companydefaults_company_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Company logo (square/standard)",
                null=True,
                upload_to="company_logos/",
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="logo_wide",
            field=models.ImageField(
                blank=True,
                help_text="Wide company logo for letterheads and PDFs",
                null=True,
                upload_to="company_logos/",
            ),
        ),
    ]
