# Generated by Django 6.0.3 on 2026-03-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0207_unique_pay_item_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="enable_xero_sync",
            field=models.BooleanField(
                default=True,
                help_text="Gate for Xero sync. Defaults True (prod). Dev fixture sets False; seed_xero_from_database sets True after prod IDs are cleared.",
            ),
        ),
    ]
