# Generated by Django 6.0.3 on 2026-04-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0208_enable_xero_sync"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="apperror",
            new_name="workflow_ap_timesta_a3d224_idx",
            old_name="workflow_ap_timesta_ae5a69_idx",
        ),
        migrations.RenameIndex(
            model_name="apperror",
            new_name="workflow_ap_resolve_2fe33d_idx",
            old_name="workflow_ap_resolve_b7bee8_idx",
        ),
        migrations.RenameIndex(
            model_name="apperror",
            new_name="workflow_ap_app_bd9fa3_idx",
            old_name="workflow_ap_app_083df1_idx",
        ),
        migrations.AlterModelTable(
            name="aiprovider",
            table=None,
        ),
        migrations.AlterModelTable(
            name="apperror",
            table=None,
        ),
        migrations.AlterModelTable(
            name="serviceapikey",
            table=None,
        ),
        migrations.AlterModelTable(
            name="xeroerror",
            table=None,
        ),
        migrations.AlterModelTable(
            name="xeropayitem",
            table=None,
        ),
        migrations.AlterModelTable(
            name="xeropayrun",
            table=None,
        ),
        migrations.AlterModelTable(
            name="xeropayslip",
            table=None,
        ),
    ]
