# Generated by Django 6.0.3 on 2026-04-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0208_enable_xero_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="accounting_provider",
            field=models.CharField(
                default="xero",
                help_text="Active accounting integration: 'xero' or 'myob'",
                max_length=20,
            ),
        ),
    ]
