# Generated by Django 6.0.3 on 2026-04-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0209_add_accounting_provider"),
        (
            "workflow",
            "0209_rename_workflow_ap_timesta_ae5a69_idx_workflow_ap_timesta_a3d224_idx_and_more",
        ),
    ]

    operations = []
