# Generated by Django 6.0.3 on 2026-04-18 21:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0210_merge_20260412_2225"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="apperror",
            index=models.Index(
                fields=["resolved", "message"], name="app_error_resolved_msg_idx"
            ),
        ),
    ]
