# Generated by Django 6.0.4 on 2026-04-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0212_companydefaults_singleton_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="weekend_timesheets_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Show Saturday and Sunday in timesheet views (7-day week). Off = 5-day Mon-Fri.",
            ),
        ),
    ]
