# Generated by Django 6.0.4 on 2026-04-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0213_companydefaults_weekend_timesheets_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="CacheState",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("disabled_until", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
