# Generated by Django 6.0.4 on 2026-04-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0214_cachestate"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="daily_approved_hours_target",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Target daily hours of newly-approved work flowing into the shop, used by the Sales Pipeline scoreboard",
                max_digits=5,
                verbose_name="Daily approved hours target",
            ),
        ),
    ]
