# Generated by Django 6.0.4 on 2026-04-27 21:50

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0215_add_daily_approved_hours_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="workshop_efficiency_factor",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.750"),
                help_text="Fraction of clocked workshop hours that count as schedulable productive output (e.g. 0.750 = 75%). Accounts for breaks, tool changes, idle time. Applied to per-day capacity in the workshop scheduler after subtracting booked time/leave.",
                max_digits=4,
            ),
        ),
    ]
