# Generated by Django 6.0.4 on 2026-05-02 21:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0216_workshop_efficiency_factor"),
    ]

    operations = [
        migrations.CreateModel(
            name="XeroApp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=64)),
                ("client_id", models.CharField(max_length=128, unique=True)),
                ("client_secret", models.CharField(max_length=256)),
                ("redirect_uri", models.CharField(max_length=512)),
                (
                    "webhook_key",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("tenant_id", models.CharField(blank=True, max_length=100, null=True)),
                ("token_type", models.CharField(blank=True, max_length=50, null=True)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("scope", models.TextField(blank=True, null=True)),
                ("day_remaining", models.IntegerField(blank=True, null=True)),
                ("minute_remaining", models.IntegerField(blank=True, null=True)),
                ("snapshot_at", models.DateTimeField(blank=True, null=True)),
                ("last_429_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="xero_app_only_one_active",
                    )
                ],
            },
        ),
    ]
