# Generated by Django 6.0.4 on 2026-05-02 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0218_populate_xero_app"),
    ]

    operations = [
        migrations.DeleteModel(
            name="XeroToken",
        ),
    ]
