# Generated by Django 6.0.4 on 2026-05-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0224_remove_app_error_resolved_msg_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companydefaults",
            name="annual_leave_loading",
            field=models.DecimalField(
                decimal_places=2,
                default=20.0,
                help_text="Percentage added to base_wage_rate to get costing wage_rate (20.00 = 20%)",
                max_digits=5,
            ),
        ),
    ]
