# Generated by Django 6.0.4 on 2026-06-02 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0231_companydefaults_shop_client_fk"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="apperror",
            new_name="workflow_apperror_time_sev_idx",
            old_name="workflow_ap_timesta_a3d224_idx",
        ),
        migrations.RenameIndex(
            model_name="apperror",
            new_name="workflow_apperror_res_time_idx",
            old_name="workflow_ap_resolve_2fe33d_idx",
        ),
        migrations.RenameIndex(
            model_name="apperror",
            new_name="workflow_apperror_app_sev_idx",
            old_name="workflow_ap_app_bd9fa3_idx",
        ),
        migrations.RenameIndex(
            model_name="apperror",
            new_name="workflow_aperr_replay_time_idx",
            old_name="workflow_ap_session_3fb195_idx",
        ),
        migrations.RenameIndex(
            model_name="sessionreplaychunk",
            new_name="workflow_chunk_record_seq_idx",
            old_name="workflow_se_recordi_6fd6ad_idx",
        ),
        migrations.RenameIndex(
            model_name="sessionreplaychunk",
            new_name="workflow_chunk_created_idx",
            old_name="workflow_se_created_4d2352_idx",
        ),
        migrations.RenameIndex(
            model_name="sessionreplayrecording",
            new_name="workflow_replay_user_start_idx",
            old_name="workflow_se_user_id_04e004_idx",
        ),
        migrations.RenameIndex(
            model_name="sessionreplayrecording",
            new_name="workflow_replay_started_idx",
            old_name="workflow_se_started_b2d73c_idx",
        ),
        migrations.RenameIndex(
            model_name="sessionreplayrecording",
            new_name="workflow_replay_job_start_idx",
            old_name="workflow_se_job_id_c58f78_idx",
        ),
    ]
