# This file is autogenerated by update_init.py script

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .company_merge_service import reassign_company_fk_records
        from .company_rest_service import CompanyRestService
        from .duplicate_phone_report import (
            DuplicatePhoneIssue,
            DuplicatePhoneOwner,
            DuplicatePhoneReportService,
            DuplicatePhoneSummary,
            DuplicatePhonesReport,
        )
        from .geocoding_service import (
            GeocodingError,
            GeocodingNotConfiguredError,
            GeocodingResult,
            geocode_address,
            get_api_key,
        )
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "CompanyRestService",
    "DuplicatePhoneIssue",
    "DuplicatePhoneOwner",
    "DuplicatePhoneReportService",
    "DuplicatePhoneSummary",
    "DuplicatePhonesReport",
    "GeocodingError",
    "GeocodingNotConfiguredError",
    "GeocodingResult",
    "geocode_address",
    "get_api_key",
    "reassign_company_fk_records",
]
