# This file is autogenerated by update_init.py script

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .company_merge_service import reassign_company_fk_records
        from .company_rest_service import CompanyPhoneAnnotations, CompanyRestService
        from .duplicate_person_report import (
            DuplicatePersonCandidate,
            DuplicatePersonCompanyLink,
            DuplicatePersonContactMethod,
            DuplicatePersonMatch,
            DuplicatePersonReport,
            DuplicatePersonReportService,
            DuplicatePersonReportSummary,
            DuplicatePersonSummary,
            normalize_person_email,
            normalize_person_name,
        )
        from .duplicate_phone_report import (
            DuplicatePhoneIssue,
            DuplicatePhoneOwner,
            DuplicatePhoneReportService,
            DuplicatePhoneSummary,
            DuplicatePhonesReport,
        )
        from .geocoding_service import (
            GeocodingError,
            GeocodingNotConfiguredError,
            GeocodingResult,
            geocode_address,
            get_api_key,
        )
        from .person_merge_service import PersonMergeCounts, merge_people
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "CompanyPhoneAnnotations",
    "CompanyRestService",
    "DuplicatePersonCandidate",
    "DuplicatePersonCompanyLink",
    "DuplicatePersonContactMethod",
    "DuplicatePersonMatch",
    "DuplicatePersonReport",
    "DuplicatePersonReportService",
    "DuplicatePersonReportSummary",
    "DuplicatePersonSummary",
    "DuplicatePhoneIssue",
    "DuplicatePhoneOwner",
    "DuplicatePhoneReportService",
    "DuplicatePhoneSummary",
    "DuplicatePhonesReport",
    "GeocodingError",
    "GeocodingNotConfiguredError",
    "GeocodingResult",
    "PersonMergeCounts",
    "geocode_address",
    "get_api_key",
    "merge_people",
    "normalize_person_email",
    "normalize_person_name",
    "reassign_company_fk_records",
]
