# Generated by Django 6.0.7 on 2026-08-01 10:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("job", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(max_length=150)),
                (
                    "normalized_number",
                    models.CharField(db_index=True, max_length=150, unique=True),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "endpoint_type",
                    models.CharField(
                        choices=[
                            ("main_line", "Main line"),
                            ("staff_mobile", "Staff mobile"),
                            ("staff_ddi", "Staff DDI"),
                            ("extension", "Extension"),
                            ("shared", "Shared"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "provider_account_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("provider_metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phone_endpoints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["endpoint_type", "label", "normalized_number"],
            },
        ),
        migrations.CreateModel(
            name="PhoneCallRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider_call_id", models.CharField(max_length=255, unique=True)),
                ("account_code", models.CharField(max_length=100)),
                ("call_datetime", models.DateTimeField(db_index=True)),
                ("call_date", models.DateField(db_index=True)),
                ("call_time", models.TimeField()),
                ("call_type", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("origin", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "destination",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "normalized_origin",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "normalized_destination",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("inbound", "Inbound"),
                            ("outbound", "Outbound"),
                            ("internal", "Internal"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("our_number", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "external_number",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                (
                    "charge",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
                ),
                ("job_linked_at", models.DateTimeField(blank=True, null=True)),
                ("raw_json", models.JSONField()),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phone_calls",
                        to="company.company",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phone_calls",
                        to="job.job",
                    ),
                ),
                (
                    "job_linked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_phone_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phone_calls",
                        to="company.person",
                    ),
                ),
                (
                    "destination_endpoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destination_phone_calls",
                        to="crm.phoneendpoint",
                    ),
                ),
                (
                    "origin_endpoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="origin_phone_calls",
                        to="crm.phoneendpoint",
                    ),
                ),
            ],
            options={
                "ordering": ["-call_datetime"],
            },
        ),
        migrations.CreateModel(
            name="PhoneProviderSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("downloads_enabled", models.BooleanField(default=False)),
                ("recording_deletion_enabled", models.BooleanField(default=False)),
                ("base_url", models.URLField(blank=True, default=None, null=True)),
                ("username", models.TextField(blank=True, null=True)),
                ("password", models.TextField(blank=True, null=True)),
                (
                    "account_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Phone Provider Settings",
                "verbose_name_plural": "Phone Provider Settings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("account_code", ""), _negated=True),
                        name="crm_phoneprovidersettings_account_code_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("base_url", ""), _negated=True),
                        name="base_url_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("password", ""), _negated=True),
                        name="crm_phoneprovidersettings_password_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("username", ""), _negated=True),
                        name="crm_phoneprovidersettings_username_not_blank",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PhoneCallRecording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider_recording_id",
                    models.CharField(max_length=255, unique=True),
                ),
                ("account_code", models.CharField(max_length=100)),
                ("filename", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "storage_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("byte_size", models.PositiveIntegerField(blank=True, null=True)),
                ("sha256", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("archive_error", models.TextField(blank=True, null=True)),
                (
                    "provider_deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("provider_delete_error", models.TextField(blank=True, null=True)),
                (
                    "local_deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "call",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recording",
                        to="crm.phonecallrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-call__call_datetime"],
                "indexes": [
                    models.Index(
                        fields=["account_code", "archived_at"],
                        name="crm_phone_rec_archive_idx",
                    ),
                    models.Index(
                        fields=["provider_deleted_at", "archived_at"],
                        name="crm_phone_rec_delete_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("archive_error", ""), _negated=True),
                        name="archive_error_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("content_type", ""), _negated=True),
                        name="content_type_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("filename", ""), _negated=True),
                        name="filename_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("provider_delete_error", ""), _negated=True),
                        name="provider_delete_error_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sha256", ""), _negated=True),
                        name="sha256_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("storage_path", ""), _negated=True),
                        name="storage_path_not_blank",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="phoneendpoint",
            index=models.Index(
                fields=["is_active", "normalized_number"],
                name="crm_phone_endpoint_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="phoneendpoint",
            index=models.Index(fields=["staff", "is_active"], name="crm_phone_endpoint_staff_idx"),
        ),
        migrations.AddConstraint(
            model_name="phoneendpoint",
            constraint=models.CheckConstraint(
                condition=models.Q(("provider_account_code", ""), _negated=True),
                name="provider_account_code_not_blank",
            ),
        ),
        migrations.AddIndex(
            model_name="phonecallrecord",
            index=models.Index(
                fields=["account_code", "-call_datetime"],
                name="crm_phone_acct_call_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="phonecallrecord",
            index=models.Index(
                fields=["company", "-call_datetime"], name="crm_phone_company_call_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phonecallrecord",
            index=models.Index(
                fields=["person", "-call_datetime"], name="crm_phone_person_call_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phonecallrecord",
            index=models.Index(fields=["job", "-call_datetime"], name="crm_phone_job_call_idx"),
        ),
        migrations.AddIndex(
            model_name="phonecallrecord",
            index=models.Index(
                fields=["direction", "-call_datetime"], name="crm_phone_direction_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phonecallrecord",
            index=models.Index(
                fields=["origin_endpoint", "-call_datetime"],
                name="crm_phone_origin_ep_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="phonecallrecord",
            index=models.Index(
                fields=["destination_endpoint", "-call_datetime"],
                name="crm_phone_dest_ep_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="phonecallrecord",
            index=models.Index(fields=["normalized_origin"], name="crm_phone_origin_norm_idx"),
        ),
        migrations.AddIndex(
            model_name="phonecallrecord",
            index=models.Index(fields=["normalized_destination"], name="crm_phone_dest_norm_idx"),
        ),
        migrations.AddConstraint(
            model_name="phonecallrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("call_type", ""), _negated=True),
                name="call_type_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="phonecallrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("description", ""), _negated=True),
                name="crm_phonecallrecord_description_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="phonecallrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("destination", ""), _negated=True),
                name="destination_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="phonecallrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("external_number", ""), _negated=True),
                name="external_number_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="phonecallrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("normalized_destination", ""), _negated=True),
                name="normalized_destination_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="phonecallrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("normalized_origin", ""), _negated=True),
                name="normalized_origin_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="phonecallrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("origin", ""), _negated=True),
                name="origin_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="phonecallrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("our_number", ""), _negated=True),
                name="our_number_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="phonecallrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("status", ""), _negated=True),
                name="status_not_blank",
            ),
        ),
    ]
