# Generated by Django 6.0.4 on 2026-07-06 00:12

import uuid

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_baseline"),
        ("job", "0001_baseline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneProviderSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("downloads_enabled", models.BooleanField(default=False)),
                ("recording_deletion_enabled", models.BooleanField(default=False)),
                ("base_url", models.URLField(blank=True, default=None, null=True)),
                (
                    "username",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "password",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "account_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Phone Provider Settings",
                "verbose_name_plural": "Phone Provider Settings",
            },
        ),
        migrations.CreateModel(
            name="PhoneEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(max_length=150)),
                (
                    "normalized_number",
                    models.CharField(db_index=True, max_length=150, unique=True),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "endpoint_type",
                    models.CharField(
                        choices=[
                            ("main_line", "Main line"),
                            ("staff_mobile", "Staff mobile"),
                            ("staff_ddi", "Staff DDI"),
                            ("extension", "Extension"),
                            ("shared", "Shared"),
                        ],
                        max_length=30,
                    ),
                ),
                ("provider_account_code", models.CharField(blank=True, max_length=100)),
                ("provider_metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phone_endpoints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["endpoint_type", "label", "normalized_number"],
            },
        ),
        migrations.CreateModel(
            name="PhoneCallRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider_call_id", models.CharField(max_length=255, unique=True)),
                ("account_code", models.CharField(max_length=100)),
                ("call_datetime", models.DateTimeField(db_index=True)),
                ("call_date", models.DateField(db_index=True)),
                ("call_time", models.TimeField()),
                ("call_type", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("origin", models.CharField(blank=True, max_length=150)),
                ("destination", models.CharField(blank=True, max_length=150)),
                ("normalized_origin", models.CharField(blank=True, max_length=150)),
                (
                    "normalized_destination",
                    models.CharField(blank=True, max_length=150),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("inbound", "Inbound"),
                            ("outbound", "Outbound"),
                            ("internal", "Internal"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("our_number", models.CharField(blank=True, max_length=150)),
                ("external_number", models.CharField(blank=True, max_length=150)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                (
                    "charge",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("job_linked_at", models.DateTimeField(blank=True, null=True)),
                ("raw_json", models.JSONField()),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phone_calls",
                        to="client.client",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phone_calls",
                        to="client.clientcontact",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phone_calls",
                        to="job.job",
                    ),
                ),
                (
                    "job_linked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_phone_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_endpoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destination_phone_calls",
                        to="crm.phoneendpoint",
                    ),
                ),
                (
                    "origin_endpoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="origin_phone_calls",
                        to="crm.phoneendpoint",
                    ),
                ),
            ],
            options={
                "ordering": ["-call_datetime"],
            },
        ),
        migrations.CreateModel(
            name="PhoneCallRecording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider_recording_id",
                    models.CharField(max_length=255, unique=True),
                ),
                ("account_code", models.CharField(max_length=100)),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("storage_path", models.CharField(blank=True, max_length=500)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("byte_size", models.PositiveIntegerField(blank=True, null=True)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("archive_error", models.TextField(blank=True)),
                (
                    "provider_deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("provider_delete_error", models.TextField(blank=True)),
                (
                    "local_deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "call",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recording",
                        to="crm.phonecallrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-call__call_datetime"],
                "indexes": [
                    models.Index(
                        fields=["account_code", "archived_at"],
                        name="crm_phone_rec_archive_idx",
                    ),
                    models.Index(
                        fields=["provider_deleted_at", "archived_at"],
                        name="crm_phone_rec_delete_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="phoneendpoint",
            index=models.Index(
                fields=["is_active", "normalized_number"],
                name="crm_phone_endpoint_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="phoneendpoint",
            index=models.Index(
                fields=["staff", "is_active"], name="crm_phone_endpoint_staff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phonecallrecord",
            index=models.Index(
                fields=["account_code", "-call_datetime"],
                name="crm_phone_acct_call_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="phonecallrecord",
            index=models.Index(
                fields=["client", "-call_datetime"], name="crm_phone_client_call_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phonecallrecord",
            index=models.Index(
                fields=["contact", "-call_datetime"], name="crm_phone_contact_call_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phonecallrecord",
            index=models.Index(
                fields=["job", "-call_datetime"], name="crm_phone_job_call_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phonecallrecord",
            index=models.Index(
                fields=["direction", "-call_datetime"], name="crm_phone_direction_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phonecallrecord",
            index=models.Index(
                fields=["origin_endpoint", "-call_datetime"],
                name="crm_phone_origin_ep_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="phonecallrecord",
            index=models.Index(
                fields=["destination_endpoint", "-call_datetime"],
                name="crm_phone_dest_ep_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="phonecallrecord",
            index=models.Index(
                fields=["normalized_origin"], name="crm_phone_origin_norm_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phonecallrecord",
            index=models.Index(
                fields=["normalized_destination"], name="crm_phone_dest_norm_idx"
            ),
        ),
    ]
