# Generated by Django 6.0.4 on 2026-07-08 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_person_link_structure"),
        ("crm", "0004_rename_client_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonecallrecord",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="person_phone_calls",
                to="company.person",
            ),
        ),
        migrations.AlterField(
            model_name="phonecallrecord",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="phone_calls",
                to="company.companypersonlink",
            ),
        ),
    ]
