# Generated by Django 6.0.4 on 2026-07-08 22:47

from typing import Any

import django.db.models.deletion
from django.db import migrations, models


def repair_call_people(apps: Any, schema_editor: Any) -> None:
    PhoneCallRecord = apps.get_model("crm", "PhoneCallRecord")
    CompanyPersonLink = apps.get_model("company", "CompanyPersonLink")

    link_person_by_id = dict(
        CompanyPersonLink.objects.exclude(person__isnull=True).values_list(
            "id", "person_id"
        )
    )
    calls = PhoneCallRecord.objects.filter(person__isnull=True).exclude(
        contact__isnull=True
    )
    for call in calls.iterator():
        person_id = link_person_by_id.get(call.contact_id)
        if person_id is not None:
            call.person_id = person_id
            call.save(update_fields=["person"])


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_alter_companypersonlink_options_and_more"),
        ("crm", "0005_phonecallrecord_person_alter_phonecallrecord_contact"),
    ]

    operations = [
        migrations.RunPython(repair_call_people, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="phonecallrecord",
            name="crm_phone_contact_call_idx",
        ),
        migrations.RemoveField(
            model_name="phonecallrecord",
            name="contact",
        ),
        migrations.AlterField(
            model_name="phonecallrecord",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="phone_calls",
                to="company.person",
            ),
        ),
        migrations.AddIndex(
            model_name="phonecallrecord",
            index=models.Index(
                fields=["person", "-call_datetime"], name="crm_phone_person_call_idx"
            ),
        ),
    ]
