# Generated by Django 6.0.4 on 2026-07-02 07:36

import encrypted_model_fields.fields
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def encrypt_existing_provider_credentials(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    PhoneProviderSettings = apps.get_model("crm", "PhoneProviderSettings")
    for settings in PhoneProviderSettings.objects.all():
        settings.save(update_fields=["username", "password", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_phone_endpoints_and_classification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phoneprovidersettings",
            name="password",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="phoneprovidersettings",
            name="username",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.RunPython(
            encrypt_existing_provider_credentials,
            migrations.RunPython.noop,
        ),
    ]
