# Generated by Django 6.0.4 on 2026-07-04 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0023_drop_scalar_phone_fields"),
        ("crm", "0007_alter_phoneprovidersettings_password_and_more"),
        ("job", "0104_non_negative_labour_rates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="phonecallrecord",
            index=models.Index(fields=["origin"], name="crm_phone_origin_num_idx"),
        ),
        migrations.AddIndex(
            model_name="phonecallrecord",
            index=models.Index(fields=["destination"], name="crm_phone_dest_num_idx"),
        ),
    ]
