# Generated by Django 6.0.4 on 2026-07-06 00:12

import uuid
from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.job.models.costing


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_baseline"),
        ("workflow", "0001_baseline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("estimate", "Estimate"),
                            ("quote", "Quote"),
                            ("actual", "Actual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rev", models.IntegerField()),
                (
                    "summary",
                    models.JSONField(
                        default=apps.job.models.costing.get_default_cost_set_summary,
                        help_text="Summary data for this cost set (cost, rev, hours)",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "order_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("job_number", models.IntegerField(unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="This becomes the first line item on the invoice",
                        null=True,
                    ),
                ),
                ("quote_acceptance_date", models.DateTimeField(blank=True, null=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set automatically when job moves to recently_completed or archived",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("awaiting_approval", "Awaiting Approval"),
                            ("approved", "Approved"),
                            ("in_progress", "In Progress"),
                            ("unusual", "Unusual"),
                            ("recently_completed", "Recently Completed"),
                            ("special", "Special"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "rejected_flag",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this job was rejected (shown in Archived with rejected styling)",
                    ),
                ),
                (
                    "rdti_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("non_rd", "Non-R&D"),
                            ("core_rd", "Core R&D"),
                            ("supporting_rd", "Supporting R&D"),
                        ],
                        help_text="R&D Tax Incentive classification for this job",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "pricing_methodology",
                    models.CharField(
                        choices=[
                            ("time_materials", "Time & Materials"),
                            ("fixed_price", "Fixed Price"),
                        ],
                        default="time_materials",
                        help_text="Determines whether job uses quotes or time and materials pricing type.",
                        max_length=20,
                    ),
                ),
                (
                    "price_cap",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum amount to invoice for T&M jobs (do not exceed). For quoted jobs it is set to the quote.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "speed_quality_tradeoff",
                    models.CharField(
                        choices=[
                            ("fast", "Fast - Prioritize Speed"),
                            ("normal", "Normal - Balanced"),
                            ("quality", "Quality - Prioritize Quality"),
                        ],
                        default="normal",
                        help_text="Speed vs quality tradeoff for workshop execution",
                        max_length=20,
                    ),
                ),
                ("job_is_valid", models.BooleanField(default=False)),
                ("collected", models.BooleanField(default=False)),
                ("paid", models.BooleanField(default=False)),
                (
                    "fully_invoiced",
                    models.BooleanField(
                        default=False,
                        help_text="The total value of invoices for this job matches the total value of the job.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("complex_job", models.BooleanField(default=False)),
                (
                    "is_urgent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this job requires urgent rates and priority handling",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about the job. Not shown on the invoice.",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.FloatField(
                        default=0.0,
                        help_text="Priority of the job, higher numbers are higher priority.",
                    ),
                ),
                (
                    "min_people",
                    models.IntegerField(
                        default=1,
                        help_text="Minimum number of workshop staff required to work on this job simultaneously",
                    ),
                ),
                (
                    "max_people",
                    models.IntegerField(
                        default=1,
                        help_text="Maximum number of workshop staff that can work on this job simultaneously",
                    ),
                ),
                (
                    "xero_project_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "xero_default_task_id",
                    models.CharField(
                        blank=True,
                        help_text="Xero task ID for the default Labor task used for time entries",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("xero_last_modified", models.DateTimeField(blank=True, null=True)),
                (
                    "xero_last_synced",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="company.client",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="The contact person for this job",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="company.clientcontact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_xero_pay_item",
                    models.ForeignKey(
                        help_text="Default pay item for time entry. Prepopulates dropdown, can be overridden.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="workflow.xeropayitem",
                    ),
                ),
                (
                    "latest_actual",
                    models.OneToOneField(
                        help_text="Latest actual cost set snapshot",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="job.costset",
                    ),
                ),
                (
                    "latest_estimate",
                    models.OneToOneField(
                        help_text="Latest estimate cost set snapshot",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="job.costset",
                    ),
                ),
                (
                    "latest_quote",
                    models.OneToOneField(
                        help_text="Latest quote cost set snapshot",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="job.costset",
                    ),
                ),
                (
                    "people",
                    models.ManyToManyField(
                        related_name="assigned_jobs", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="costset",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost_sets",
                to="job.job",
            ),
        ),
        migrations.CreateModel(
            name="JobDeltaRejection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("change_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("reason", models.CharField(max_length=255)),
                ("detail", models.TextField(blank=True)),
                ("envelope", models.JSONField()),
                ("checksum", models.CharField(blank=True, max_length=128)),
                ("request_etag", models.CharField(blank=True, max_length=128)),
                ("request_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delta_rejections",
                        to="job.job",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolved_delta_rejections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delta_rejections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="JobEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "event_type",
                    models.CharField(default="automatic_event", max_length=100),
                ),
                ("schema_version", models.PositiveSmallIntegerField(default=0)),
                ("change_id", models.UUIDField(blank=True, null=True)),
                ("delta_before", models.JSONField(blank=True, null=True)),
                ("delta_after", models.JSONField(blank=True, null=True)),
                ("delta_meta", models.JSONField(blank=True, null=True)),
                (
                    "delta_checksum",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "detail",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured audit data for this event. Keys vary by event_type.",
                    ),
                ),
                (
                    "dedup_hash",
                    models.CharField(
                        blank=True,
                        help_text="MD5 hash for deduplication based on job+staff+description+type",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="job.job",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="JobFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("deleted", "Deleted")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("print_on_jobsheet", models.BooleanField(default=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="job.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="JobQuoteChat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        help_text="Frontend-generated unique ID",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra data like streaming status, processing time, etc.",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote_chat_messages",
                        to="job.job",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="LabourSubtype",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Sort order in dropdowns and reports"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive subtypes keep historical lines valid but are not offered for new entry and are not seeded onto new jobs",
                    ),
                ),
                (
                    "is_workshop",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this subtype is the default workshop subtype for staff and rate selection",
                    ),
                ),
                (
                    "counts_for_scheduling",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this labour consumes the production staff pool for scheduling and workshop PDF remaining-hours calculations",
                    ),
                ),
                (
                    "default_charge_out_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Company-level rate used to seed JobLabourRate on new jobs",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("default_charge_out_rate__gte", 0)),
                        name="laboursubtype_default_rate_non_negative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="JobLabourRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "charge_out_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labour_rates",
                        to="job.job",
                    ),
                ),
                (
                    "labour_subtype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_rates",
                        to="job.laboursubtype",
                    ),
                ),
            ],
            options={
                "ordering": ["labour_subtype__display_order", "labour_subtype__name"],
            },
        ),
        migrations.CreateModel(
            name="CostLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("time", "Time"),
                            ("material", "Material"),
                            ("adjust", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "desc",
                    models.CharField(
                        blank=True,
                        help_text="Description of this cost line",
                        max_length=255,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("1.000"), max_digits=10
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "unit_rev",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "ext_refs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="External references (e.g., time entry IDs, material IDs)",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata - structure varies by kind (see class docstring)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accounting_date",
                    models.DateField(
                        help_text="The date this cost should be attributed to for accounting purposes"
                    ),
                ),
                (
                    "xero_time_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "xero_expense_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("xero_last_modified", models.DateTimeField(blank=True, null=True)),
                (
                    "xero_last_synced",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether this line is approved or not by an office staff (when the line is created by a workshop worker)",
                    ),
                ),
                (
                    "entry_seq",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Sequence number within a staff member's daily actual time entries.",
                        null=True,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member for actual time entries.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_lines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "xero_pay_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Xero pay item for this time entry (leave type, earnings rate, etc.)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_lines",
                        to="workflow.xeropayitem",
                    ),
                ),
                (
                    "cost_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_lines",
                        to="job.costset",
                    ),
                ),
                (
                    "labour_subtype",
                    models.ForeignKey(
                        blank=True,
                        help_text="The labour subtype for time lines (Workshop, Admin, Onsite, ...)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_lines",
                        to="job.laboursubtype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="QuoteSpreadsheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sheet_id",
                    models.CharField(help_text="Google Drive file ID", max_length=100),
                ),
                ("sheet_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "tab",
                    models.CharField(
                        blank=True, default="Primary Details", max_length=100, null=True
                    ),
                ),
                (
                    "job",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quote_sheet",
                        to="job.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote Spreadsheet",
                "verbose_name_plural": "Quote Spreadsheets",
            },
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["status", "priority"], name="job_priority_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="costset",
            constraint=models.UniqueConstraint(
                fields=("job", "kind", "rev"), name="unique_job_kind_rev"
            ),
        ),
        migrations.AddIndex(
            model_name="jobdeltarejection",
            index=models.Index(
                fields=["change_id", "-created_at"], name="job_delta_rej_change_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobdeltarejection",
            index=models.Index(
                fields=["-created_at"], name="job_delta_rej_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobdeltarejection",
            index=models.Index(
                fields=["resolved", "reason"], name="job_delta_rej_res_rsn_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobevent",
            index=models.Index(
                fields=["job", "-timestamp"], name="jobevent_job_timestamp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobevent",
            index=models.Index(
                fields=["event_type", "-timestamp"], name="jobevent_type_timestamp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobevent",
            index=models.Index(
                fields=["staff", "-timestamp"], name="jobevent_staff_timestamp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobevent",
            index=models.Index(fields=["dedup_hash"], name="jobevent_dedup_hash_idx"),
        ),
        migrations.AddIndex(
            model_name="jobevent",
            index=models.Index(fields=["change_id"], name="jobevent_change_idx"),
        ),
        migrations.AddConstraint(
            model_name="jobevent",
            constraint=models.UniqueConstraint(
                fields=("job", "staff", "event_type", "dedup_hash"),
                name="unique_manual_event_per_user_job",
            ),
        ),
        migrations.AddIndex(
            model_name="jobquotechat",
            index=models.Index(
                fields=["job", "timestamp"], name="job_jobquot_job_id_c83a63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobquotechat",
            index=models.Index(
                fields=["message_id"], name="job_jobquot_message_786ba1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="joblabourrate",
            constraint=models.CheckConstraint(
                condition=models.Q(("charge_out_rate__gte", 0)),
                name="joblabourrate_charge_out_rate_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="joblabourrate",
            constraint=models.UniqueConstraint(
                fields=("job", "labour_subtype"), name="unique_job_labour_subtype"
            ),
        ),
        migrations.AddIndex(
            model_name="costline",
            index=models.Index(
                fields=["cost_set_id", "kind"], name="job_costlin_cost_se_5afccf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="costline",
            index=models.Index(
                fields=["cost_set_id", "created_at"],
                name="job_costlin_cost_se_c0dcd8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="costline",
            index=models.Index(
                fields=["cost_set_id", "kind", "created_at"],
                name="job_costlin_cost_se_a4dadb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="costline",
            index=models.Index(
                fields=["staff", "accounting_date", "entry_seq"],
                name="job_costlin_staff_i_2efa8d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="costline",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("entry_seq__isnull", False),
                    ("kind", "time"),
                    ("staff__isnull", False),
                ),
                fields=("staff", "accounting_date", "entry_seq"),
                name="unique_time_entry_staff_day_seq",
            ),
        ),
        migrations.AddConstraint(
            model_name="costline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("entry_seq__isnull", True), ("staff__isnull", True)),
                    models.Q(("entry_seq__isnull", False), ("staff__isnull", False)),
                    _connector="OR",
                ),
                name="costline_staff_entry_seq_pair",
            ),
        ),
    ]
