# Generated by Django 6.0.7 on 2026-08-17 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0003_allow_blank_company_and_created_by"),
        ("xero", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="costline",
            name="managed_by",
            field=models.CharField(
                blank=True,
                choices=[("leave", "Leave")],
                help_text="Workflow that owns this line; owned lines are changed through that workflow.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="costline",
            constraint=models.CheckConstraint(
                condition=models.Q(("managed_by", ""), _negated=True),
                name="costline_managed_by_not_blank",
            ),
        ),
    ]
