# Generated by Django 6.0.4 on 2026-07-08 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_person_link_structure"),
        ("job", "0003_rename_client_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="person",
            field=models.ForeignKey(
                blank=True,
                help_text="The person for this job",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="person_jobs",
                to="company.person",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                help_text="The contact person for this job",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="company.companypersonlink",
            ),
        ),
    ]
