# Generated by Django 6.0.4 on 2026-07-08 22:47

from typing import Any

import django.db.models.deletion
from django.db import migrations, models


def repair_job_people(apps: Any, schema_editor: Any) -> None:
    Job = apps.get_model("job", "Job")
    CompanyPersonLink = apps.get_model("company", "CompanyPersonLink")

    link_person_by_id = dict(
        CompanyPersonLink.objects.exclude(person__isnull=True).values_list(
            "id", "person_id"
        )
    )
    jobs = Job.objects.filter(person__isnull=True).exclude(contact__isnull=True)
    for job in jobs.iterator():
        person_id = link_person_by_id.get(job.contact_id)
        if person_id is not None:
            job.person_id = person_id
            job.save(update_fields=["person"])


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_alter_companypersonlink_options_and_more"),
        ("job", "0004_job_person_alter_job_contact"),
    ]

    operations = [
        migrations.RunPython(repair_job_people, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="job",
            name="contact",
        ),
        migrations.AlterField(
            model_name="job",
            name="person",
            field=models.ForeignKey(
                blank=True,
                help_text="The person for this job",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="company.person",
            ),
        ),
    ]
