# Generated by Django 6.1.1 on 2026-09-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0007_complete_quote_chat_storage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costline",
            name="managed_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("leave", "Leave"),
                    ("stocktake", "Stocktake"),
                    ("stock", "Stock movement"),
                ],
                help_text="Workflow that owns this line; owned lines are changed through that workflow.",
                max_length=20,
                null=True,
            ),
        ),
    ]
