# Generated by Django 6.1.1 on 2026-09-08 01:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0008_alter_costline_managed_by"),
        ("xero", "0002_remove_xeroapp_day_remaining_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="costline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("managed_by__isnull", True),
                    ("managed_by__in", ["leave", "stocktake", "stock"]),
                    _connector="OR",
                ),
                name="costline_known_owner",
            ),
        ),
    ]
