# Generated by Django 6.0.7 on 2026-07-31 21:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0009_text_unset_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobCompletionChecklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time_entries_complete", models.BooleanField(default=False)),
                ("materials_complete", models.BooleanField(default=False)),
                ("customer_approval_confirmed", models.BooleanField(default=False)),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When an item was last changed; NULL until the first change.",
                        null=True,
                    ),
                ),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completion_checklist",
                        to="job.job",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who last changed an item; NULL until the first change.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Completion Checklist",
                "verbose_name_plural": "Job Completion Checklists",
            },
        ),
    ]
