# Generated by Django 6.1.1 on 2026-09-08 03:50

import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0010_costline_costline_known_owner"),
    ]

    operations = [
        migrations.RunSQL(
            """
            LOCK TABLE job_job, job_costset, job_costline IN SHARE ROW EXCLUSIVE MODE;
            WITH actual AS (
                SELECT s.id, jsonb_build_object(
                    'cost', COALESCE(SUM(c.quantity * c.unit_cost), 0),
                    'rev', COALESCE(SUM(c.quantity * c.unit_rev), 0),
                    'hours', COALESCE(SUM(c.quantity) FILTER (WHERE c.kind = 'time'), 0)
                ) AS totals
                FROM job_costset s LEFT JOIN job_costline c ON c.cost_set_id = s.id
                GROUP BY s.id
            ), rebuilt AS (
                UPDATE job_costset s SET summary =
                    CASE WHEN jsonb_typeof(s.summary) = 'object' THEN s.summary
                         ELSE '{}'::jsonb END || actual.totals
                FROM actual WHERE s.id = actual.id AND NOT (s.summary @> actual.totals)
                RETURNING s.job_id
            )
            UPDATE job_job SET updated_at = CURRENT_TIMESTAMP
            WHERE id IN (SELECT job_id FROM rebuilt);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddConstraint(
            model_name="costset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("summary__has_keys", ["cost", "rev", "hours"]),
                    django.db.models.lookups.Exact(
                        models.Func(
                            models.F("summary"),
                            function="jsonb_typeof",
                            output_field=models.CharField(),
                        ),
                        models.Value("object"),
                    ),
                    django.db.models.lookups.Exact(
                        models.Func(
                            models.F("summary__cost"),
                            function="jsonb_typeof",
                            output_field=models.CharField(),
                        ),
                        models.Value("number"),
                    ),
                    django.db.models.lookups.Exact(
                        models.Func(
                            models.F("summary__rev"),
                            function="jsonb_typeof",
                            output_field=models.CharField(),
                        ),
                        models.Value("number"),
                    ),
                    django.db.models.lookups.Exact(
                        models.Func(
                            models.F("summary__hours"),
                            function="jsonb_typeof",
                            output_field=models.CharField(),
                        ),
                        models.Value("number"),
                    ),
                ),
                name="costset_numeric_summary",
            ),
        ),
    ]
