# Generated by Django 6.1.1 on 2026-09-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0011_incremental_cost_summary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="costline",
            options={
                "ordering": [
                    models.Case(
                        models.When(kind="material", then=models.Value(1)),
                        models.When(kind="adjust", then=models.Value(2)),
                        models.When(kind="time", then=models.Value(3)),
                        output_field=models.IntegerField(),
                    ),
                    "created_at",
                    "id",
                ]
            },
        ),
    ]
