# Generated by Django 6.1.1 on 2026-10-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0016_consolidate_notes_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="costline",
            name="remote_entry",
            field=models.BooleanField(
                default=False,
                help_text="The worker saved this line without a location at the company address.",
            ),
        ),
    ]
