# Generated by Django 6.0.1 on 2026-03-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0070_delete_safetydocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="rdti_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("non_rd", "Non-R&D"),
                    ("core_rd", "Core R&D"),
                    ("supporting_rd", "Supporting R&D"),
                ],
                help_text="R&D Tax Incentive classification for this job",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="rdti_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("non_rd", "Non-R&D"),
                    ("core_rd", "Core R&D"),
                    ("supporting_rd", "Supporting R&D"),
                ],
                help_text="R&D Tax Incentive classification for this job",
                max_length=20,
                null=True,
            ),
        ),
    ]
