# Generated by Django 6.0.3 on 2026-04-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0071_add_rdti_type"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="jobquotechat",
            new_name="job_jobquot_job_id_c83a63_idx",
            old_name="job_quote_c_job_id_24cfd1_idx",
        ),
        migrations.RenameIndex(
            model_name="jobquotechat",
            new_name="job_jobquot_message_786ba1_idx",
            old_name="job_quote_c_message_33b6a6_idx",
        ),
        migrations.AlterModelTable(
            name="historicaljob",
            table=None,
        ),
        migrations.AlterModelTable(
            name="job",
            table=None,
        ),
        migrations.AlterModelTable(
            name="jobdeltarejection",
            table=None,
        ),
        migrations.AlterModelTable(
            name="jobevent",
            table=None,
        ),
        migrations.AlterModelTable(
            name="jobfile",
            table=None,
        ),
        migrations.AlterModelTable(
            name="jobquotechat",
            table=None,
        ),
    ]
