# Generated by Django 6.0.3 on 2026-04-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "job",
            "0072_rename_job_quote_c_job_id_24cfd1_idx_job_jobquot_job_id_c83a63_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="max_people",
            field=models.IntegerField(
                default=1,
                help_text="Maximum number of workshop staff that can work on this job simultaneously",
            ),
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="min_people",
            field=models.IntegerField(
                default=1,
                help_text="Minimum number of workshop staff required to work on this job simultaneously",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="max_people",
            field=models.IntegerField(
                default=1,
                help_text="Maximum number of workshop staff that can work on this job simultaneously",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="min_people",
            field=models.IntegerField(
                default=1,
                help_text="Minimum number of workshop staff required to work on this job simultaneously",
            ),
        ),
    ]
