# Generated by Django 6.0.4 on 2026-04-21 06:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0018_client_allow_jobs"),
        ("job", "0074_jobdeltarejection_resolved_and_more"),
        ("workflow", "0211_apperror_app_error_resolved_msg_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                condition=models.Q(
                    ("pricing_methodology", "fixed_price"), ("status", "archived")
                ),
                fields=["completed_at"],
                name="job_recent_archived_fp_idx",
            ),
        ),
    ]
