# Generated by Django 6.0.3 on 2026-04-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0075_backfill_jobevent_status_from_historicaljob"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobevent",
            name="detail",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Structured audit data for this event. Keys vary by event_type.",
            ),
        ),
        migrations.AlterField(
            model_name="jobevent",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
