# Generated by Django 6.0.4 on 2026-06-10 09:45

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0091_require_latest_costsets_drop_historicaljob"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabourSubtype",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Sort order in dropdowns and reports"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive subtypes keep historical lines valid but are not offered for new entry and are not seeded onto new jobs",
                    ),
                ),
                (
                    "is_workshop",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this subtype counts as workshop work for scheduling and the workshop PDF",
                    ),
                ),
                (
                    "default_charge_out_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Company-level rate used to seed JobLabourRate on new jobs",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="JobLabourRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "charge_out_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labour_rates",
                        to="job.job",
                    ),
                ),
                (
                    "labour_subtype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_rates",
                        to="job.laboursubtype",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job", "labour_subtype"),
                        name="unique_job_labour_subtype",
                    )
                ],
            },
        ),
    ]
