# Generated by Django 6.0.4 on 2026-06-10 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0093_seed_labour_subtypes"),
    ]

    operations = [
        migrations.AddField(
            model_name="costline",
            name="labour_subtype",
            field=models.ForeignKey(
                blank=True,
                help_text="The labour subtype for time lines (Workshop, Office/Admin, ...)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cost_lines",
                to="job.laboursubtype",
            ),
        ),
    ]
