# Generated by Django 6.0.4 on 2026-06-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0095_backfill_job_labour_rates_and_costline_subtypes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="charge_out_rate",
        ),
    ]
