# Generated by Django 6.0.4 on 2026-06-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0096_remove_job_charge_out_rate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="joblabourrate",
            options={
                "ordering": ["labour_subtype__display_order", "labour_subtype__name"]
            },
        ),
    ]
