# Generated by Django 6.0.7 on 2026-08-01 10:23

import uuid
from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="XeroError",
            fields=[
                (
                    "apperror_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.apperror",
                    ),
                ),
                ("entity", models.CharField(max_length=100)),
                ("reference_id", models.CharField(max_length=255)),
                ("kind", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Xero Error",
                "verbose_name_plural": "Xero Errors",
                "db_table": "workflow_xeroerror",
            },
            bases=("core.apperror",),
        ),
        migrations.CreateModel(
            name="XeroSyncCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_key", models.CharField(max_length=50, unique=True)),
                ("last_modified", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "workflow_xerosynccursor",
            },
        ),
        migrations.CreateModel(
            name="XeroAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_id", models.UUIDField(unique=True)),
                (
                    "xero_tenant_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "account_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("account_name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "account_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("tax_type", models.CharField(blank=True, max_length=50, null=True)),
                ("enable_payments", models.BooleanField(default=False)),
                ("xero_last_modified", models.DateTimeField()),
                (
                    "xero_last_synced",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ("raw_json", models.JSONField()),
                ("django_created_at", models.DateTimeField(auto_now_add=True)),
                ("django_updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "workflow_xeroaccount",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("account_code", ""), _negated=True),
                        name="workflow_xeroaccount_account_code_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("account_type", ""), _negated=True),
                        name="account_type_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("description", ""), _negated=True),
                        name="workflow_xeroaccount_description_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("tax_type", ""), _negated=True),
                        name="tax_type_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("xero_tenant_id", ""), _negated=True),
                        name="workflow_xeroaccount_xero_tenant_id_not_blank",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="XeroApp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=64)),
                ("client_id", models.CharField(max_length=128, unique=True)),
                ("client_secret", models.CharField(max_length=256)),
                ("redirect_uri", models.CharField(max_length=512)),
                (
                    "webhook_key",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("token_type", models.CharField(blank=True, max_length=50, null=True)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("scope", models.TextField(blank=True, null=True)),
                ("day_remaining", models.IntegerField(blank=True, null=True)),
                ("minute_remaining", models.IntegerField(blank=True, null=True)),
                ("snapshot_at", models.DateTimeField(blank=True, null=True)),
                ("last_429_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "workflow_xeroapp",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="xero_app_only_one_active",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("access_token", ""), _negated=True),
                        name="access_token_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("refresh_token", ""), _negated=True),
                        name="refresh_token_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("scope", ""), _negated=True),
                        name="scope_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("token_type", ""), _negated=True),
                        name="token_type_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("webhook_key", ""), _negated=True),
                        name="webhook_key_not_blank",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="XeroPayItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "xero_id",
                    models.CharField(
                        blank=True,
                        help_text="Xero's UUID for this pay item",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "xero_tenant_id",
                    models.CharField(
                        blank=True,
                        help_text="Xero tenant this pay item belongs to",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'Ordinary Time', 'Annual Leave')",
                        max_length=100,
                    ),
                ),
                (
                    "uses_leave_api",
                    models.BooleanField(
                        help_text="True = Xero Leave API, False = Xero Timesheets API"
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rate multiplier from Xero (1.0, 1.5, 2.0, etc.). NULL for leave types.",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "xero_last_modified",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last modified timestamp from Xero",
                        null=True,
                    ),
                ),
                (
                    "xero_last_synced",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="When we last synced this record from Xero",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Xero Pay Item",
                "verbose_name_plural": "Xero Pay Items",
                "db_table": "workflow_xeropayitem",
                "ordering": ["uses_leave_api", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "uses_leave_api"),
                        name="unique_pay_item_name_per_api",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("xero_id", ""), _negated=True),
                        name="workflow_xeropayitem_xero_id_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("xero_tenant_id", ""), _negated=True),
                        name="workflow_xeropayitem_xero_tenant_id_not_blank",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="XeroPayRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_id", models.UUIDField(unique=True)),
                ("xero_tenant_id", models.CharField(max_length=255)),
                ("payroll_calendar_id", models.UUIDField(blank=True, null=True)),
                ("period_start_date", models.DateField()),
                ("period_end_date", models.DateField()),
                ("payment_date", models.DateField()),
                (
                    "pay_run_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "pay_run_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "total_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "total_pay",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("raw_json", models.JSONField()),
                ("xero_last_modified", models.DateTimeField()),
                (
                    "xero_last_synced",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ("django_created_at", models.DateTimeField(auto_now_add=True)),
                ("django_updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Xero Pay Run",
                "verbose_name_plural": "Xero Pay Runs",
                "db_table": "workflow_xeropayrun",
                "ordering": ["-payment_date"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("pay_run_status", ""), _negated=True),
                        name="pay_run_status_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("pay_run_type", ""), _negated=True),
                        name="pay_run_type_not_blank",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="XeroPaySlip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_id", models.UUIDField(unique=True)),
                ("xero_tenant_id", models.CharField(max_length=255)),
                ("xero_employee_id", models.UUIDField()),
                (
                    "employee_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gross_earnings",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10),
                ),
                (
                    "net_pay",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10),
                ),
                (
                    "timesheet_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Hours from timesheet_earnings_lines (actual worked hours)",
                        max_digits=8,
                    ),
                ),
                (
                    "leave_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Hours from leave_earnings_lines (sick, annual, etc.)",
                        max_digits=8,
                    ),
                ),
                ("raw_json", models.JSONField()),
                ("xero_last_modified", models.DateTimeField()),
                (
                    "xero_last_synced",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ("django_created_at", models.DateTimeField(auto_now_add=True)),
                ("django_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pay_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pay_slips",
                        to="xero.xeropayrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xero Pay Slip",
                "verbose_name_plural": "Xero Pay Slips",
                "db_table": "workflow_xeropayslip",
                "ordering": ["-pay_run__payment_date", "employee_name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("employee_name", ""), _negated=True),
                        name="employee_name_not_blank",
                    )
                ],
                "unique_together": {("pay_run", "xero_employee_id")},
            },
        ),
    ]
