# Generated by Django 6.1.1 on 2026-09-06 07:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("xero", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="xeroapp",
            name="day_remaining",
        ),
        migrations.RemoveField(
            model_name="xeroapp",
            name="last_429_at",
        ),
        migrations.RemoveField(
            model_name="xeroapp",
            name="minute_remaining",
        ),
        migrations.RemoveField(
            model_name="xeroapp",
            name="snapshot_at",
        ),
    ]
