# Generated by Django 6.1.1 on 2026-09-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xero", "0002_remove_xeroapp_day_remaining_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="XeroDetailRefresh",
            fields=[
                ("tenant_id", models.CharField(max_length=50, primary_key=True, serialize=False)),
                ("last_success_at", models.DateTimeField()),
            ],
        ),
    ]
