# Generated by Django 6.1.1 on 2026-09-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xero", "0004_backfill_staff_xero_payroll_terms_checksum"),
    ]

    operations = [
        migrations.CreateModel(
            name="FakeXeroObject",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("contact", "Contact"),
                            ("invoice", "Invoice"),
                            ("credit_note", "Credit note"),
                            ("quote", "Quote"),
                            ("purchase_order", "Purchase order"),
                            ("item", "Item"),
                            ("account", "Account"),
                            ("tax_rate", "Tax rate"),
                            ("organisation", "Organisation"),
                            ("branding_theme", "Branding theme"),
                            ("employee", "Employee"),
                            ("salary_and_wage", "Salary and wage"),
                            ("working_pattern", "Working pattern"),
                            ("pay_run", "Pay run"),
                            ("pay_slip", "Pay slip"),
                            ("leave_type", "Leave type"),
                            ("earnings_rate", "Earnings rate"),
                            ("history_record", "History record"),
                            ("attachment", "Attachment"),
                        ],
                        max_length=32,
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("parent_id", models.UUIDField(blank=True, null=True)),
                ("updated_date_utc", models.DateTimeField()),
                ("body", models.JSONField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "kind", "updated_date_utc"],
                        name="fakexero_tenant_kind_updated",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("number__isnull", False)),
                        fields=("tenant_id", "kind", "number"),
                        name="fakexeroobject_number_unique_per_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("number", ""), _negated=True),
                        name="fakexeroobject_number_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("name", ""), _negated=True),
                        name="fakexeroobject_name_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status", ""), _negated=True),
                        name="fakexeroobject_status_not_blank",
                    ),
                ],
            },
        ),
    ]
