"""How many slips Xero reported for a pay run, so "mirrored" means whole.

No backfill: setting old rows to the count of slips they hold would ratify a
partial mirror as complete, which is the defect this column exists to end.
Every Posted run therefore starts NULL and is read once more on the first
sync after deploy, one call per run (63 in production, well under the day
floor); a run that is whole then costs nothing again.
"""

# Generated by Django 6.1.1 on 2026-09-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xero", "0005_fakexeroobject"),
    ]

    operations = [
        migrations.AddField(
            model_name="xeropayrun",
            name="pay_slip_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
