# Generated by Django 6.1.1 on 2026-09-14 09:50

import django.db.models.deletion
from django.db import migrations, models

import apps.xero.fake.models


class Migration(migrations.Migration):
    dependencies = [
        ("xero", "0006_xeropayrun_pay_slip_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="FakeAccount",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("tenant_id", models.CharField(max_length=255)),
                ("updated_date_utc", models.DateTimeField()),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(max_length=500)),
                ("status", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("tax_type", models.CharField(blank=True, max_length=50, null=True)),
                ("account_class", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "xero_fake_account",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FakeAttachment",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("tenant_id", models.CharField(max_length=255)),
                ("updated_date_utc", models.DateTimeField()),
                ("resource", models.CharField(max_length=50)),
                ("document_id", models.UUIDField()),
                ("file_name", models.CharField(max_length=500)),
                ("mime_type", models.CharField(max_length=255)),
                ("content_length", models.IntegerField()),
                ("include_online", models.BooleanField()),
                ("url", models.CharField(max_length=5000)),
            ],
            options={
                "db_table": "xero_fake_attachment",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FakeBrandingTheme",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("tenant_id", models.CharField(max_length=255)),
                ("updated_date_utc", models.DateTimeField()),
                ("name", models.CharField(max_length=500)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "xero_fake_brandingtheme",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FakeContact",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("tenant_id", models.CharField(max_length=255)),
                ("updated_date_utc", models.DateTimeField()),
                ("name", models.CharField(max_length=500)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("email_address", models.CharField(blank=True, max_length=500, null=True)),
                ("account_number", models.CharField(blank=True, max_length=255, null=True)),
                ("is_customer", models.BooleanField(blank=True, null=True)),
                ("is_supplier", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "xero_fake_contact",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FakeCreditNote",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("tenant_id", models.CharField(max_length=255)),
                ("updated_date_utc", models.DateTimeField()),
                ("number", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(max_length=50)),
                ("date", models.DateField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=4000, null=True)),
                ("currency_code", models.CharField(blank=True, max_length=3, null=True)),
                ("branding_theme_id", models.UUIDField(blank=True, null=True)),
                ("line_amount_types", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "sub_total",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "total_tax",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "total",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                ("type", models.CharField(max_length=50)),
                (
                    "remaining_credit",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
            ],
            options={
                "db_table": "xero_fake_creditnote",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FakeCreditNoteLine",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("position", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "unit_amount",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                ("account_code", models.CharField(blank=True, max_length=50, null=True)),
                ("tax_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "tax_amount",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "line_amount",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                ("item_code", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "xero_fake_creditnoteline",
                "ordering": ["position"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FakeEarningsRate",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("tenant_id", models.CharField(max_length=255)),
                ("updated_date_utc", models.DateTimeField()),
                ("name", models.CharField(max_length=255)),
                ("earnings_type", models.CharField(max_length=50)),
                ("rate_type", models.CharField(max_length=50)),
                ("type_of_units", models.CharField(blank=True, max_length=50, null=True)),
                ("current_record", models.BooleanField()),
                (
                    "rate_per_unit",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "multiple_of_ordinary_earnings_rate",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
            ],
            options={
                "db_table": "xero_fake_earningsrate",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FakeEmployee",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("tenant_id", models.CharField(max_length=255)),
                ("updated_date_utc", models.DateTimeField()),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.CharField(blank=True, max_length=500, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("payroll_calendar_id", models.UUIDField(blank=True, null=True)),
                ("job_title", models.CharField(blank=True, max_length=500, null=True)),
                ("employment_type", models.CharField(blank=True, max_length=50, null=True)),
                ("created_date_utc", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "xero_fake_employee",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FakeHistoryRecord",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("tenant_id", models.CharField(max_length=255)),
                ("updated_date_utc", models.DateTimeField()),
                ("resource", models.CharField(max_length=50)),
                ("document_id", models.UUIDField()),
                ("changes", models.CharField(max_length=255)),
                ("date_utc", models.DateTimeField()),
                ("user", models.CharField(max_length=255)),
                ("details", models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                "db_table": "xero_fake_historyrecord",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FakeInvoice",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("tenant_id", models.CharField(max_length=255)),
                ("updated_date_utc", models.DateTimeField()),
                ("number", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(max_length=50)),
                ("date", models.DateField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=4000, null=True)),
                ("currency_code", models.CharField(blank=True, max_length=3, null=True)),
                ("branding_theme_id", models.UUIDField(blank=True, null=True)),
                ("line_amount_types", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "sub_total",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "total_tax",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "total",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                ("type", models.CharField(max_length=50)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "amount_due",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "amount_paid",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "amount_credited",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                ("fully_paid_on_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "xero_fake_invoice",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FakeInvoiceLine",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("position", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "unit_amount",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                ("account_code", models.CharField(blank=True, max_length=50, null=True)),
                ("tax_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "tax_amount",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "line_amount",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                ("item_code", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "xero_fake_invoiceline",
                "ordering": ["position"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FakeItem",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("tenant_id", models.CharField(max_length=255)),
                ("updated_date_utc", models.DateTimeField()),
                ("code", models.CharField(max_length=255)),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                ("is_sold", models.BooleanField(blank=True, null=True)),
                ("is_purchased", models.BooleanField(blank=True, null=True)),
                ("is_tracked_as_inventory", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "xero_fake_item",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FakeLeaveType",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("tenant_id", models.CharField(max_length=255)),
                ("updated_date_utc", models.DateTimeField()),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField()),
                ("is_paid_leave", models.BooleanField()),
                ("type_of_units", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "xero_fake_leavetype",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FakeOrganisation",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("tenant_id", models.CharField(max_length=255)),
                ("updated_date_utc", models.DateTimeField()),
                ("name", models.CharField(max_length=500)),
                ("short_code", models.CharField(blank=True, max_length=50, null=True)),
                ("base_currency", models.CharField(max_length=3)),
                ("status", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "xero_fake_organisation",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FakePayRun",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("tenant_id", models.CharField(max_length=255)),
                ("updated_date_utc", models.DateTimeField()),
                ("payroll_calendar_id", models.UUIDField()),
                ("period_start_date", models.DateField()),
                ("period_end_date", models.DateField()),
                ("payment_date", models.DateField()),
                ("status", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("calendar_type", models.CharField(max_length=50)),
                (
                    "total_cost",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "total_pay",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                ("posted_date_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "xero_fake_payrun",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FakePayRunCalendar",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("tenant_id", models.CharField(max_length=255)),
                ("updated_date_utc", models.DateTimeField()),
                ("name", models.CharField(max_length=255)),
                ("calendar_type", models.CharField(max_length=50)),
                ("period_start_date", models.DateField()),
                ("period_end_date", models.DateField()),
                ("payment_date", models.DateField()),
            ],
            options={
                "db_table": "xero_fake_payruncalendar",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FakePaySlip",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("tenant_id", models.CharField(max_length=255)),
                ("updated_date_utc", models.DateTimeField()),
                ("employee_id", models.UUIDField()),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "total_earnings",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "gross_earnings",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "total_pay",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
            ],
            options={
                "db_table": "xero_fake_payslip",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FakePurchaseOrder",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("tenant_id", models.CharField(max_length=255)),
                ("updated_date_utc", models.DateTimeField()),
                ("number", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(max_length=50)),
                ("date", models.DateField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=4000, null=True)),
                ("currency_code", models.CharField(blank=True, max_length=3, null=True)),
                ("branding_theme_id", models.UUIDField(blank=True, null=True)),
                ("line_amount_types", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "sub_total",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "total_tax",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "total",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "xero_fake_purchaseorder",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FakePurchaseOrderLine",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("position", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "unit_amount",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                ("account_code", models.CharField(blank=True, max_length=50, null=True)),
                ("tax_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "tax_amount",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "line_amount",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                ("item_code", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "xero_fake_purchaseorderline",
                "ordering": ["position"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FakeQuote",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("tenant_id", models.CharField(max_length=255)),
                ("updated_date_utc", models.DateTimeField()),
                ("number", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(max_length=50)),
                ("date", models.DateField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=4000, null=True)),
                ("currency_code", models.CharField(blank=True, max_length=3, null=True)),
                ("branding_theme_id", models.UUIDField(blank=True, null=True)),
                ("line_amount_types", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "sub_total",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "total_tax",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "total",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "xero_fake_quote",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FakeQuoteLine",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("position", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "unit_amount",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                ("account_code", models.CharField(blank=True, max_length=50, null=True)),
                ("tax_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "tax_amount",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "line_amount",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                ("item_code", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "xero_fake_quoteline",
                "ordering": ["position"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FakeSalaryAndWage",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("tenant_id", models.CharField(max_length=255)),
                ("updated_date_utc", models.DateTimeField()),
                ("earnings_rate_id", models.UUIDField()),
                ("effective_from", models.DateField()),
                ("status", models.CharField(max_length=50)),
                ("payment_type", models.CharField(max_length=50)),
                (
                    "rate_per_unit",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "annual_salary",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "units_per_week",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "units_per_day",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "days_per_week",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
            ],
            options={
                "db_table": "xero_fake_salaryandwage",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FakeTaxRate",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("tenant_id", models.CharField(max_length=255)),
                ("updated_date_utc", models.DateTimeField()),
                ("name", models.CharField(max_length=500)),
                ("tax_type", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
                ("effective_rate", models.DecimalField(decimal_places=4, max_digits=9)),
            ],
            options={
                "db_table": "xero_fake_taxrate",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FakeWorkingPattern",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("tenant_id", models.CharField(max_length=255)),
                ("updated_date_utc", models.DateTimeField()),
                ("effective_from", models.DateField()),
            ],
            options={
                "db_table": "xero_fake_workingpattern",
                "abstract": False,
            },
        ),
        migrations.RemoveIndex(
            model_name="fakexeroobject",
            name="fakexero_tenant_kind_updated",
        ),
        migrations.RemoveConstraint(
            model_name="fakexeroobject",
            name="fakexeroobject_number_unique_per_kind",
        ),
        migrations.RemoveConstraint(
            model_name="fakexeroobject",
            name="fakexeroobject_number_not_blank",
        ),
        migrations.RemoveConstraint(
            model_name="fakexeroobject",
            name="fakexeroobject_name_not_blank",
        ),
        migrations.RemoveConstraint(
            model_name="fakexeroobject",
            name="fakexeroobject_status_not_blank",
        ),
        migrations.DeleteModel(
            name="FakeXeroObject",
        ),
        migrations.AddIndex(
            model_name="fakeaccount",
            index=models.Index(
                fields=["tenant_id", "updated_date_utc"], name="fakeaccount_tenant_upd"
            ),
        ),
        migrations.AddConstraint(
            model_name="fakeaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code__isnull", False), ("status", "ACTIVE")),
                fields=("tenant_id", "code"),
                name="account_code_unique_while_active",
            ),
        ),
        migrations.AddIndex(
            model_name="fakeattachment",
            index=models.Index(
                fields=["tenant_id", "updated_date_utc"], name="fakeattachment_tenant_upd"
            ),
        ),
        migrations.AddIndex(
            model_name="fakeattachment",
            index=models.Index(
                fields=["tenant_id", "resource", "document_id"], name="attachment_document"
            ),
        ),
        migrations.AddIndex(
            model_name="fakebrandingtheme",
            index=models.Index(
                fields=["tenant_id", "updated_date_utc"], name="fakebrandingtheme_tenant_upd"
            ),
        ),
        migrations.AddIndex(
            model_name="fakecontact",
            index=models.Index(
                fields=["tenant_id", "updated_date_utc"], name="fakecontact_tenant_upd"
            ),
        ),
        migrations.AddIndex(
            model_name="fakecontact",
            index=models.Index(fields=["tenant_id", "name"], name="contact_tenant_name"),
        ),
        migrations.AddIndex(
            model_name="fakecontact",
            index=models.Index(fields=["tenant_id", "status"], name="contact_tenant_status"),
        ),
        migrations.AddField(
            model_name="fakecreditnote",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="xero.fakecontact",
            ),
        ),
        migrations.AddField(
            model_name="fakecreditnoteline",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creditnote_lines",
                to="xero.fakecreditnote",
            ),
        ),
        migrations.AddIndex(
            model_name="fakeearningsrate",
            index=models.Index(
                fields=["tenant_id", "updated_date_utc"], name="fakeearningsrate_tenant_upd"
            ),
        ),
        migrations.AddConstraint(
            model_name="fakeearningsrate",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "name"), name="earningsrate_name_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="fakeemployee",
            index=models.Index(
                fields=["tenant_id", "updated_date_utc"], name="fakeemployee_tenant_upd"
            ),
        ),
        migrations.AddIndex(
            model_name="fakeemployee",
            index=models.Index(fields=["tenant_id", "email"], name="employee_tenant_email"),
        ),
        migrations.AddIndex(
            model_name="fakehistoryrecord",
            index=models.Index(
                fields=["tenant_id", "updated_date_utc"], name="fakehistoryrecord_tenant_upd"
            ),
        ),
        migrations.AddIndex(
            model_name="fakehistoryrecord",
            index=models.Index(
                fields=["tenant_id", "resource", "document_id"], name="history_document"
            ),
        ),
        migrations.AddField(
            model_name="fakeinvoice",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="xero.fakecontact",
            ),
        ),
        migrations.AddField(
            model_name="fakeinvoiceline",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_lines",
                to="xero.fakeinvoice",
            ),
        ),
        migrations.AddIndex(
            model_name="fakeitem",
            index=models.Index(
                fields=["tenant_id", "updated_date_utc"], name="fakeitem_tenant_upd"
            ),
        ),
        migrations.AddConstraint(
            model_name="fakeitem",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "code"), name="item_code_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="fakeleavetype",
            index=models.Index(
                fields=["tenant_id", "updated_date_utc"], name="fakeleavetype_tenant_upd"
            ),
        ),
        migrations.AddConstraint(
            model_name="fakeleavetype",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "name"), name="leavetype_name_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="fakeorganisation",
            index=models.Index(
                fields=["tenant_id", "updated_date_utc"], name="fakeorganisation_tenant_upd"
            ),
        ),
        migrations.AddConstraint(
            model_name="fakeorganisation",
            constraint=models.UniqueConstraint(
                fields=("tenant_id",), name="organisation_one_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="fakepayrun",
            index=models.Index(
                fields=["tenant_id", "updated_date_utc"], name="fakepayrun_tenant_upd"
            ),
        ),
        migrations.AddConstraint(
            model_name="fakepayrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "Draft")),
                fields=("tenant_id", "payroll_calendar_id"),
                name="payrun_one_draft_per_calendar",
            ),
        ),
        migrations.AddIndex(
            model_name="fakepayruncalendar",
            index=models.Index(
                fields=["tenant_id", "updated_date_utc"], name="fakepayruncalendar_tenant_upd"
            ),
        ),
        migrations.AddConstraint(
            model_name="fakepayruncalendar",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "name"), name="payruncalendar_name_unique"
            ),
        ),
        migrations.AddField(
            model_name="fakepayslip",
            name="pay_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slips",
                to="xero.fakepayrun",
            ),
        ),
        migrations.AddField(
            model_name="fakepurchaseorder",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="xero.fakecontact",
            ),
        ),
        migrations.AddField(
            model_name="fakepurchaseorderline",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchaseorder_lines",
                to="xero.fakepurchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="fakequote",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="xero.fakecontact",
            ),
        ),
        migrations.AddField(
            model_name="fakequoteline",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quote_lines",
                to="xero.fakequote",
            ),
        ),
        migrations.AddField(
            model_name="fakesalaryandwage",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salaries",
                to="xero.fakeemployee",
            ),
        ),
        migrations.AddIndex(
            model_name="faketaxrate",
            index=models.Index(
                fields=["tenant_id", "updated_date_utc"], name="faketaxrate_tenant_upd"
            ),
        ),
        migrations.AddConstraint(
            model_name="faketaxrate",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "tax_type"), name="taxrate_type_unique"
            ),
        ),
        migrations.AddField(
            model_name="fakeworkingpattern",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patterns",
                to="xero.fakeemployee",
            ),
        ),
        migrations.AddIndex(
            model_name="fakecreditnote",
            index=models.Index(
                fields=["tenant_id", "updated_date_utc"], name="fakecreditnote_tenant_upd"
            ),
        ),
        migrations.AddIndex(
            model_name="fakecreditnote",
            index=models.Index(fields=["tenant_id", "number"], name="fakecreditnote_tenant_num"),
        ),
        migrations.AddIndex(
            model_name="fakecreditnote",
            index=models.Index(fields=["tenant_id", "status"], name="fakecreditnote_tenant_stat"),
        ),
        migrations.AddConstraint(
            model_name="fakecreditnote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number__isnull", False), ("type", "ACCRECCREDIT")),
                fields=("tenant_id", "number"),
                name="creditnote_number_unique_per_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="fakeinvoice",
            index=models.Index(
                fields=["tenant_id", "updated_date_utc"], name="fakeinvoice_tenant_upd"
            ),
        ),
        migrations.AddIndex(
            model_name="fakeinvoice",
            index=models.Index(fields=["tenant_id", "number"], name="fakeinvoice_tenant_num"),
        ),
        migrations.AddIndex(
            model_name="fakeinvoice",
            index=models.Index(fields=["tenant_id", "status"], name="fakeinvoice_tenant_stat"),
        ),
        migrations.AddConstraint(
            model_name="fakeinvoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number__isnull", False), ("type", "ACCREC")),
                fields=("tenant_id", "number"),
                name="invoice_number_unique_per_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="fakepayslip",
            index=models.Index(
                fields=["tenant_id", "updated_date_utc"], name="fakepayslip_tenant_upd"
            ),
        ),
        migrations.AddConstraint(
            model_name="fakepayslip",
            constraint=models.UniqueConstraint(
                fields=("pay_run", "employee_id"), name="payslip_one_per_employee_per_run"
            ),
        ),
        migrations.AddIndex(
            model_name="fakepurchaseorder",
            index=models.Index(
                fields=["tenant_id", "updated_date_utc"], name="fakepurchaseorder_tenant_upd"
            ),
        ),
        migrations.AddIndex(
            model_name="fakepurchaseorder",
            index=models.Index(fields=["tenant_id", "number"], name="fakepurchaseorder_tenant_num"),
        ),
        migrations.AddIndex(
            model_name="fakepurchaseorder",
            index=models.Index(
                fields=["tenant_id", "status"], name="fakepurchaseorder_tenant_stat"
            ),
        ),
        migrations.AddConstraint(
            model_name="fakepurchaseorder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number__isnull", False)),
                fields=("tenant_id", "number"),
                name="purchaseorder_number_unique_per_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="fakequote",
            index=models.Index(
                fields=["tenant_id", "updated_date_utc"], name="fakequote_tenant_upd"
            ),
        ),
        migrations.AddIndex(
            model_name="fakequote",
            index=models.Index(fields=["tenant_id", "number"], name="fakequote_tenant_num"),
        ),
        migrations.AddIndex(
            model_name="fakequote",
            index=models.Index(fields=["tenant_id", "status"], name="fakequote_tenant_stat"),
        ),
        migrations.AddConstraint(
            model_name="fakequote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number__isnull", False)),
                fields=("tenant_id", "number"),
                name="quote_number_unique_per_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="fakesalaryandwage",
            index=models.Index(
                fields=["tenant_id", "updated_date_utc"], name="fakesalaryandwage_tenant_upd"
            ),
        ),
        migrations.AddIndex(
            model_name="fakeworkingpattern",
            index=models.Index(
                fields=["tenant_id", "updated_date_utc"], name="fakeworkingpattern_tenant_upd"
            ),
        ),
    ]
