# Generated by Django 6.1.1 on 2026-09-14 10:20

import django.db.models.deletion
from django.db import migrations, models

import apps.xero.fake.models


class Migration(migrations.Migration):
    dependencies = [
        ("xero", "0007_fake_xero_relational"),
    ]

    operations = [
        migrations.CreateModel(
            name="FakeLeaveBalance",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("attributes", models.JSONField(encoder=apps.xero.fake.models.WireJSONEncoder)),
                ("tenant_id", models.CharField(max_length=255)),
                ("updated_date_utc", models.DateTimeField()),
                ("leave_type_id", models.UUIDField()),
                ("name", models.CharField(max_length=255)),
                ("balance", models.DecimalField(decimal_places=4, max_digits=20)),
                ("type_of_units", models.CharField(max_length=50)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="xero.fakeemployee",
                    ),
                ),
            ],
            options={
                "db_table": "xero_fake_leavebalance",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "updated_date_utc"], name="fakeleavebalance_tenant_upd"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "leave_type_id"), name="leavebalance_type_unique"
                    )
                ],
            },
        ),
    ]
