# Generated by Django 6.1.1 on 2026-10-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xero", "0008_fakeleavebalance"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="fakequote",
            name="quote_number_unique_per_tenant",
        ),
        migrations.AddConstraint(
            model_name="fakequote",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("number__isnull", False), models.Q(("status", "DELETED"), _negated=True)
                ),
                fields=("tenant_id", "number"),
                name="quote_number_unique_per_tenant",
            ),
        ),
    ]
