# This file is autogenerated by update_init.py script

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .db_scrubber import scrub
        from .error_grouping import (
            list_grouped_app_errors,
            list_grouped_xero_errors,
            mark_app_error_group_resolved,
            mark_app_error_group_resolved_by_fingerprint,
            mark_app_error_group_unresolved,
            mark_app_error_group_unresolved_by_fingerprint,
            mark_xero_error_group_resolved,
            mark_xero_error_group_resolved_by_fingerprint,
            mark_xero_error_group_unresolved,
            mark_xero_error_group_unresolved_by_fingerprint,
        )
        from .error_persistence import (
            extract_job_context,
            extract_request_context,
            list_app_errors,
            persist_and_raise,
            persist_app_error,
            persist_xero_error,
        )
        from .llm_service import LLMService, quick_completion, quick_json_completion
        from .request import get_client_ip
        from .search import apply_text_search
        from .search_telemetry import (
            SearchTelemetryService,
            normalize_search_query,
            stable_event_hash,
        )
        from .session_replay_service import (
            append_chunk,
            create_recording,
            list_recordings,
            purge_old_recordings,
            recording_events,
        )
        from .validation import to_decimal, validate_required_fields
        from .xero_sync_service import XeroSyncService, XeroSyncStartResult
        from .xero_sync_worker import xero_sync_task
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "LLMService",
    "SearchTelemetryService",
    "XeroSyncService",
    "XeroSyncStartResult",
    "append_chunk",
    "apply_text_search",
    "create_recording",
    "extract_job_context",
    "extract_request_context",
    "get_client_ip",
    "list_app_errors",
    "list_grouped_app_errors",
    "list_grouped_xero_errors",
    "list_recordings",
    "mark_app_error_group_resolved",
    "mark_app_error_group_resolved_by_fingerprint",
    "mark_app_error_group_unresolved",
    "mark_app_error_group_unresolved_by_fingerprint",
    "mark_xero_error_group_resolved",
    "mark_xero_error_group_resolved_by_fingerprint",
    "mark_xero_error_group_unresolved",
    "mark_xero_error_group_unresolved_by_fingerprint",
    "normalize_search_query",
    "persist_and_raise",
    "persist_app_error",
    "persist_xero_error",
    "purge_old_recordings",
    "quick_completion",
    "quick_json_completion",
    "recording_events",
    "scrub",
    "stable_event_hash",
    "to_decimal",
    "validate_required_fields",
    "xero_sync_task",
]
