# This file is autogenerated by update_init.py script

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .core import JobAgingService, KPIService, StaffPerformanceService
        from .invoice_calculation import (
            InvoiceCalculationError,
            InvoiceCalculationResult,
            calculate_invoice_amount,
            get_prior_valid_invoice_total,
        )
        from .payroll_reconciliation_service import PayrollReconciliationService
        from .rdti_spend_service import RDTISpendService
        from .sales_pipeline_service import SalesPipelineService
        from .wip_service import WIPService
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "InvoiceCalculationError",
    "InvoiceCalculationResult",
    "JobAgingService",
    "KPIService",
    "PayrollReconciliationService",
    "RDTISpendService",
    "SalesPipelineService",
    "StaffPerformanceService",
    "WIPService",
    "calculate_invoice_amount",
    "get_prior_valid_invoice_total",
]
