# This file is autogenerated by update_init.py script

from .apps import CompanyConfig
from .utils import date_to_datetime

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .models import (
            Company,
            CompanyPersonLink,
            CompanyQuerySet,
            ContactMethod,
            Person,
            PhoneAssignmentConflictError,
            Supplier,
            SupplierPickupAddress,
            SupplierSearchAlias,
        )
        from .serializers import (
            CompanyCreateResponseSerializer,
            CompanyCreateSerializer,
            CompanyDetailResponseSerializer,
            CompanyDuplicateErrorResponseSerializer,
            CompanyErrorResponseSerializer,
            CompanyJobHeaderSerializer,
            CompanyJobsResponseSerializer,
            CompanyListResponseSerializer,
            CompanyNameOnlySerializer,
            CompanyPersonAttrs,
            CompanyPersonLinkAttrs,
            CompanyPersonLinkSerializer,
            CompanySearchResponseSerializer,
            CompanySearchResultSerializer,
            CompanySerializer,
            CompanyUpdateResponseSerializer,
            CompanyUpdateSerializer,
            ContactMethodSerializer,
            JobPersonBaseSerializer,
            JobPersonResponseSerializer,
            JobPersonUpdateSerializer,
            StandardErrorSerializer,
            SupplierPickupAddressSerializer,
            SupplierSearchAliasCreateSerializer,
            SupplierSearchAliasSerializer,
            set_primary_phone,
        )
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "Company",
    "CompanyConfig",
    "CompanyCreateResponseSerializer",
    "CompanyCreateSerializer",
    "CompanyDetailResponseSerializer",
    "CompanyDuplicateErrorResponseSerializer",
    "CompanyErrorResponseSerializer",
    "CompanyJobHeaderSerializer",
    "CompanyJobsResponseSerializer",
    "CompanyListResponseSerializer",
    "CompanyNameOnlySerializer",
    "CompanyPersonAttrs",
    "CompanyPersonLink",
    "CompanyPersonLinkAttrs",
    "CompanyPersonLinkSerializer",
    "CompanyQuerySet",
    "CompanySearchResponseSerializer",
    "CompanySearchResultSerializer",
    "CompanySerializer",
    "CompanyUpdateResponseSerializer",
    "CompanyUpdateSerializer",
    "ContactMethod",
    "ContactMethodSerializer",
    "JobPersonBaseSerializer",
    "JobPersonResponseSerializer",
    "JobPersonUpdateSerializer",
    "Person",
    "PhoneAssignmentConflictError",
    "StandardErrorSerializer",
    "Supplier",
    "SupplierPickupAddress",
    "SupplierPickupAddressSerializer",
    "SupplierSearchAlias",
    "SupplierSearchAliasCreateSerializer",
    "SupplierSearchAliasSerializer",
    "date_to_datetime",
    "set_primary_phone",
]
