# Generated by Django 6.0.3 on 2026-04-16 04:12

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("job", "0073_add_min_max_people"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchedulerRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ran_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "algorithm_version",
                    models.CharField(
                        default="v1",
                        help_text="Version identifier for the scheduling algorithm",
                        max_length=50,
                    ),
                ),
                ("succeeded", models.BooleanField(default=False)),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True,
                        help_text="Error message if the run failed",
                        null=True,
                    ),
                ),
                (
                    "job_count",
                    models.IntegerField(
                        default=0, help_text="Number of jobs processed in this run"
                    ),
                ),
                (
                    "unscheduled_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of jobs that could not be scheduled in this run",
                    ),
                ),
            ],
            options={
                "ordering": ["-ran_at"],
            },
        ),
        migrations.CreateModel(
            name="AllocationBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("allocation_date", models.DateField()),
                (
                    "allocated_hours",
                    models.FloatField(
                        help_text="Hours allocated to this job for this staff member on this date"
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=0,
                        help_text="Ordering within the run for reconstructing the schedule",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocation_blocks",
                        to="job.job",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocation_blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scheduler_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocation_blocks",
                        to="operations.schedulerrun",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduler_run", "sequence", "allocation_date"],
            },
        ),
        migrations.CreateModel(
            name="JobProjection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("anticipated_start_date", models.DateField(blank=True, null=True)),
                ("anticipated_end_date", models.DateField(blank=True, null=True)),
                (
                    "remaining_hours",
                    models.FloatField(
                        help_text="Remaining hours at the time of this scheduler run"
                    ),
                ),
                ("is_late", models.BooleanField(default=False)),
                ("is_unscheduled", models.BooleanField(default=False)),
                (
                    "unscheduled_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "missing_estimate_or_quote_hours",
                                "Missing estimate or quote hours",
                            ),
                            (
                                "min_people_exceeds_staff",
                                "min_people exceeds available workshop staff",
                            ),
                            (
                                "invalid_staffing_constraints",
                                "Invalid staffing constraints (max_people < min_people)",
                            ),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projections",
                        to="job.job",
                    ),
                ),
                (
                    "scheduler_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_projections",
                        to="operations.schedulerrun",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduler_run", "job__priority"],
                "unique_together": {("scheduler_run", "job")},
            },
        ),
    ]
