# Generated by Django 6.0.4 on 2026-04-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial_operations_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobprojection",
            name="unscheduled_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "missing_estimate_or_quote_hours",
                        "Missing estimate or quote hours",
                    ),
                    (
                        "min_people_exceeds_staff",
                        "min_people exceeds available workshop staff",
                    ),
                    (
                        "invalid_staffing_constraints",
                        "Invalid staffing constraints (max_people < min_people)",
                    ),
                    (
                        "not_reached_in_horizon",
                        "Higher-priority jobs consumed all capacity within the schedule horizon",
                    ),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
