/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedKanbanRouteImport } from './routes/_authed/kanban'
import { Route as AuthedJobsJobIdRouteImport } from './routes/_authed/jobs/$jobId'
import { Route as AuthedJobsCreateRouteImport } from './routes/_authed/jobs/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedKanbanRoute = AuthedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsJobIdRoute = AuthedJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsCreateRoute = AuthedJobsCreateRouteImport.update({
  id: '/jobs/create',
  path: '/jobs/create',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/kanban': typeof AuthedKanbanRoute
  '/jobs/$jobId': typeof AuthedJobsJobIdRoute
  '/jobs/create': typeof AuthedJobsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/kanban': typeof AuthedKanbanRoute
  '/jobs/$jobId': typeof AuthedJobsJobIdRoute
  '/jobs/create': typeof AuthedJobsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/kanban': typeof AuthedKanbanRoute
  '/_authed/jobs/$jobId': typeof AuthedJobsJobIdRoute
  '/_authed/jobs/create': typeof AuthedJobsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/kanban' | '/jobs/$jobId' | '/jobs/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/kanban' | '/jobs/$jobId' | '/jobs/create'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/kanban'
    | '/_authed/jobs/$jobId'
    | '/_authed/jobs/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/kanban': {
      id: '/_authed/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthedKanbanRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs/$jobId': {
      id: '/_authed/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AuthedJobsJobIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs/create': {
      id: '/_authed/jobs/create'
      path: '/jobs/create'
      fullPath: '/jobs/create'
      preLoaderRoute: typeof AuthedJobsCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedKanbanRoute: typeof AuthedKanbanRoute
  AuthedJobsJobIdRoute: typeof AuthedJobsJobIdRoute
  AuthedJobsCreateRoute: typeof AuthedJobsCreateRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedKanbanRoute: AuthedKanbanRoute,
  AuthedJobsJobIdRoute: AuthedJobsJobIdRoute,
  AuthedJobsCreateRoute: AuthedJobsCreateRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
