/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedKanbanRouteImport } from './routes/_authed/kanban'
import { Route as AuthedJobsJobIdRouteImport } from './routes/_authed/jobs/$jobId'
import { Route as AuthedJobsCreateRouteImport } from './routes/_authed/jobs/create'
import { Route as AuthedReportsJobMovementRouteImport } from './routes/_authed/reports/job-movement'
import { Route as AuthedReportsWipRouteImport } from './routes/_authed/reports/wip'
import { Route as AuthedTimesheetsDailyRouteImport } from './routes/_authed/timesheets/daily'
import { Route as AuthedTimesheetsEntryRouteImport } from './routes/_authed/timesheets/entry'
import { Route as AuthedCrmCompaniesIndexRouteImport } from './routes/_authed/crm/companies/index'
import { Route as AuthedCrmCompaniesCompanyIdRouteImport } from './routes/_authed/crm/companies/$companyId'
import { Route as AuthedPurchasingPoIndexRouteImport } from './routes/_authed/purchasing/po/index'
import { Route as AuthedPurchasingPoPoIdRouteImport } from './routes/_authed/purchasing/po/$poId'
import { Route as AuthedPurchasingPoCreateRouteImport } from './routes/_authed/purchasing/po/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedKanbanRoute = AuthedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsJobIdRoute = AuthedJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsCreateRoute = AuthedJobsCreateRouteImport.update({
  id: '/jobs/create',
  path: '/jobs/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsJobMovementRoute =
  AuthedReportsJobMovementRouteImport.update({
    id: '/reports/job-movement',
    path: '/reports/job-movement',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedReportsWipRoute = AuthedReportsWipRouteImport.update({
  id: '/reports/wip',
  path: '/reports/wip',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTimesheetsDailyRoute = AuthedTimesheetsDailyRouteImport.update({
  id: '/timesheets/daily',
  path: '/timesheets/daily',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTimesheetsEntryRoute = AuthedTimesheetsEntryRouteImport.update({
  id: '/timesheets/entry',
  path: '/timesheets/entry',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCrmCompaniesIndexRoute = AuthedCrmCompaniesIndexRouteImport.update({
  id: '/crm/companies/',
  path: '/crm/companies/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCrmCompaniesCompanyIdRoute =
  AuthedCrmCompaniesCompanyIdRouteImport.update({
    id: '/crm/companies/$companyId',
    path: '/crm/companies/$companyId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedPurchasingPoIndexRoute = AuthedPurchasingPoIndexRouteImport.update({
  id: '/purchasing/po/',
  path: '/purchasing/po/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPurchasingPoPoIdRoute = AuthedPurchasingPoPoIdRouteImport.update({
  id: '/purchasing/po/$poId',
  path: '/purchasing/po/$poId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPurchasingPoCreateRoute =
  AuthedPurchasingPoCreateRouteImport.update({
    id: '/purchasing/po/create',
    path: '/purchasing/po/create',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/kanban': typeof AuthedKanbanRoute
  '/jobs/$jobId': typeof AuthedJobsJobIdRoute
  '/jobs/create': typeof AuthedJobsCreateRoute
  '/reports/job-movement': typeof AuthedReportsJobMovementRoute
  '/reports/wip': typeof AuthedReportsWipRoute
  '/timesheets/daily': typeof AuthedTimesheetsDailyRoute
  '/timesheets/entry': typeof AuthedTimesheetsEntryRoute
  '/crm/companies/$companyId': typeof AuthedCrmCompaniesCompanyIdRoute
  '/purchasing/po/$poId': typeof AuthedPurchasingPoPoIdRoute
  '/purchasing/po/create': typeof AuthedPurchasingPoCreateRoute
  '/crm/companies/': typeof AuthedCrmCompaniesIndexRoute
  '/purchasing/po/': typeof AuthedPurchasingPoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/kanban': typeof AuthedKanbanRoute
  '/jobs/$jobId': typeof AuthedJobsJobIdRoute
  '/jobs/create': typeof AuthedJobsCreateRoute
  '/reports/job-movement': typeof AuthedReportsJobMovementRoute
  '/reports/wip': typeof AuthedReportsWipRoute
  '/timesheets/daily': typeof AuthedTimesheetsDailyRoute
  '/timesheets/entry': typeof AuthedTimesheetsEntryRoute
  '/crm/companies/$companyId': typeof AuthedCrmCompaniesCompanyIdRoute
  '/purchasing/po/$poId': typeof AuthedPurchasingPoPoIdRoute
  '/purchasing/po/create': typeof AuthedPurchasingPoCreateRoute
  '/crm/companies': typeof AuthedCrmCompaniesIndexRoute
  '/purchasing/po': typeof AuthedPurchasingPoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/kanban': typeof AuthedKanbanRoute
  '/_authed/jobs/$jobId': typeof AuthedJobsJobIdRoute
  '/_authed/jobs/create': typeof AuthedJobsCreateRoute
  '/_authed/reports/job-movement': typeof AuthedReportsJobMovementRoute
  '/_authed/reports/wip': typeof AuthedReportsWipRoute
  '/_authed/timesheets/daily': typeof AuthedTimesheetsDailyRoute
  '/_authed/timesheets/entry': typeof AuthedTimesheetsEntryRoute
  '/_authed/crm/companies/$companyId': typeof AuthedCrmCompaniesCompanyIdRoute
  '/_authed/purchasing/po/$poId': typeof AuthedPurchasingPoPoIdRoute
  '/_authed/purchasing/po/create': typeof AuthedPurchasingPoCreateRoute
  '/_authed/crm/companies/': typeof AuthedCrmCompaniesIndexRoute
  '/_authed/purchasing/po/': typeof AuthedPurchasingPoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/kanban'
    | '/jobs/$jobId'
    | '/jobs/create'
    | '/reports/job-movement'
    | '/reports/wip'
    | '/timesheets/daily'
    | '/timesheets/entry'
    | '/crm/companies/$companyId'
    | '/purchasing/po/$poId'
    | '/purchasing/po/create'
    | '/crm/companies/'
    | '/purchasing/po/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/kanban'
    | '/jobs/$jobId'
    | '/jobs/create'
    | '/reports/job-movement'
    | '/reports/wip'
    | '/timesheets/daily'
    | '/timesheets/entry'
    | '/crm/companies/$companyId'
    | '/purchasing/po/$poId'
    | '/purchasing/po/create'
    | '/crm/companies'
    | '/purchasing/po'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/kanban'
    | '/_authed/jobs/$jobId'
    | '/_authed/jobs/create'
    | '/_authed/reports/job-movement'
    | '/_authed/reports/wip'
    | '/_authed/timesheets/daily'
    | '/_authed/timesheets/entry'
    | '/_authed/crm/companies/$companyId'
    | '/_authed/purchasing/po/$poId'
    | '/_authed/purchasing/po/create'
    | '/_authed/crm/companies/'
    | '/_authed/purchasing/po/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/kanban': {
      id: '/_authed/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthedKanbanRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs/$jobId': {
      id: '/_authed/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AuthedJobsJobIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs/create': {
      id: '/_authed/jobs/create'
      path: '/jobs/create'
      fullPath: '/jobs/create'
      preLoaderRoute: typeof AuthedJobsCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports/job-movement': {
      id: '/_authed/reports/job-movement'
      path: '/reports/job-movement'
      fullPath: '/reports/job-movement'
      preLoaderRoute: typeof AuthedReportsJobMovementRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports/wip': {
      id: '/_authed/reports/wip'
      path: '/reports/wip'
      fullPath: '/reports/wip'
      preLoaderRoute: typeof AuthedReportsWipRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/timesheets/daily': {
      id: '/_authed/timesheets/daily'
      path: '/timesheets/daily'
      fullPath: '/timesheets/daily'
      preLoaderRoute: typeof AuthedTimesheetsDailyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/timesheets/entry': {
      id: '/_authed/timesheets/entry'
      path: '/timesheets/entry'
      fullPath: '/timesheets/entry'
      preLoaderRoute: typeof AuthedTimesheetsEntryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/crm/companies/': {
      id: '/_authed/crm/companies/'
      path: '/crm/companies'
      fullPath: '/crm/companies/'
      preLoaderRoute: typeof AuthedCrmCompaniesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/crm/companies/$companyId': {
      id: '/_authed/crm/companies/$companyId'
      path: '/crm/companies/$companyId'
      fullPath: '/crm/companies/$companyId'
      preLoaderRoute: typeof AuthedCrmCompaniesCompanyIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/purchasing/po/': {
      id: '/_authed/purchasing/po/'
      path: '/purchasing/po'
      fullPath: '/purchasing/po/'
      preLoaderRoute: typeof AuthedPurchasingPoIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/purchasing/po/$poId': {
      id: '/_authed/purchasing/po/$poId'
      path: '/purchasing/po/$poId'
      fullPath: '/purchasing/po/$poId'
      preLoaderRoute: typeof AuthedPurchasingPoPoIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/purchasing/po/create': {
      id: '/_authed/purchasing/po/create'
      path: '/purchasing/po/create'
      fullPath: '/purchasing/po/create'
      preLoaderRoute: typeof AuthedPurchasingPoCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedKanbanRoute: typeof AuthedKanbanRoute
  AuthedJobsJobIdRoute: typeof AuthedJobsJobIdRoute
  AuthedJobsCreateRoute: typeof AuthedJobsCreateRoute
  AuthedReportsJobMovementRoute: typeof AuthedReportsJobMovementRoute
  AuthedReportsWipRoute: typeof AuthedReportsWipRoute
  AuthedTimesheetsDailyRoute: typeof AuthedTimesheetsDailyRoute
  AuthedTimesheetsEntryRoute: typeof AuthedTimesheetsEntryRoute
  AuthedCrmCompaniesCompanyIdRoute: typeof AuthedCrmCompaniesCompanyIdRoute
  AuthedPurchasingPoPoIdRoute: typeof AuthedPurchasingPoPoIdRoute
  AuthedPurchasingPoCreateRoute: typeof AuthedPurchasingPoCreateRoute
  AuthedCrmCompaniesIndexRoute: typeof AuthedCrmCompaniesIndexRoute
  AuthedPurchasingPoIndexRoute: typeof AuthedPurchasingPoIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedKanbanRoute: AuthedKanbanRoute,
  AuthedJobsJobIdRoute: AuthedJobsJobIdRoute,
  AuthedJobsCreateRoute: AuthedJobsCreateRoute,
  AuthedReportsJobMovementRoute: AuthedReportsJobMovementRoute,
  AuthedReportsWipRoute: AuthedReportsWipRoute,
  AuthedTimesheetsDailyRoute: AuthedTimesheetsDailyRoute,
  AuthedTimesheetsEntryRoute: AuthedTimesheetsEntryRoute,
  AuthedCrmCompaniesCompanyIdRoute: AuthedCrmCompaniesCompanyIdRoute,
  AuthedPurchasingPoPoIdRoute: AuthedPurchasingPoPoIdRoute,
  AuthedPurchasingPoCreateRoute: AuthedPurchasingPoCreateRoute,
  AuthedCrmCompaniesIndexRoute: AuthedCrmCompaniesIndexRoute,
  AuthedPurchasingPoIndexRoute: AuthedPurchasingPoIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
