/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SessionCheckRouteImport } from './routes/session-check'
import { Route as AuthedKanbanRouteImport } from './routes/_authed/kanban'
import { Route as AuthedAdminIntegrationsRouteImport } from './routes/_authed/admin/integrations'
import { Route as AuthedAdminLeaveSettingsRouteImport } from './routes/_authed/admin/leave-settings'
import { Route as AuthedAdminStaffRouteImport } from './routes/_authed/admin/staff'
import { Route as AuthedAdminXeroRouteImport } from './routes/_authed/admin/xero'
import { Route as AuthedJobsJobIdRouteImport } from './routes/_authed/jobs/$jobId'
import { Route as AuthedJobsCreateRouteImport } from './routes/_authed/jobs/create'
import { Route as AuthedPurchasingStockRouteImport } from './routes/_authed/purchasing/stock'
import { Route as AuthedReportsJobMovementRouteImport } from './routes/_authed/reports/job-movement'
import { Route as AuthedReportsPayrollReconciliationRouteImport } from './routes/_authed/reports/payroll-reconciliation'
import { Route as AuthedReportsSalesForecastRouteImport } from './routes/_authed/reports/sales-forecast'
import { Route as AuthedReportsWipRouteImport } from './routes/_authed/reports/wip'
import { Route as AuthedTimesheetsDailyRouteImport } from './routes/_authed/timesheets/daily'
import { Route as AuthedTimesheetsEntryRouteImport } from './routes/_authed/timesheets/entry'
import { Route as AuthedTimesheetsLeaveRouteImport } from './routes/_authed/timesheets/leave'
import { Route as AuthedTimesheetsMyTimeRouteImport } from './routes/_authed/timesheets/my-time'
import { Route as AuthedTimesheetsWeeklyRouteImport } from './routes/_authed/timesheets/weekly'
import { Route as AuthedAdminCompanyDefaultsIndexRouteImport } from './routes/_authed/admin/company-defaults/index'
import { Route as AuthedAdminCompanyDefaultsSectionRouteImport } from './routes/_authed/admin/company-defaults/$section'
import { Route as AuthedCrmCallsIndexRouteImport } from './routes/_authed/crm/calls/index'
import { Route as AuthedCrmCompaniesIndexRouteImport } from './routes/_authed/crm/companies/index'
import { Route as AuthedCrmCompaniesCompanyIdRouteImport } from './routes/_authed/crm/companies/$companyId'
import { Route as AuthedCrmPeopleIndexRouteImport } from './routes/_authed/crm/people/index'
import { Route as AuthedCrmPeoplePersonIdRouteImport } from './routes/_authed/crm/people/$personId'
import { Route as AuthedPurchasingPoIndexRouteImport } from './routes/_authed/purchasing/po/index'
import { Route as AuthedPurchasingPoPoIdRouteImport } from './routes/_authed/purchasing/po/$poId'
import { Route as AuthedPurchasingPoCreateRouteImport } from './routes/_authed/purchasing/po/create'
import { Route as AuthedProcessDocumentsFormsCategoryIndexRouteImport } from './routes/_authed/process-documents/forms/$category/index'
import { Route as AuthedProcessDocumentsFormsCategoryFormIdRouteImport } from './routes/_authed/process-documents/forms/$category/$formId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionCheckRoute = SessionCheckRouteImport.update({
  id: '/session-check',
  path: '/session-check',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedKanbanRoute = AuthedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminIntegrationsRoute = AuthedAdminIntegrationsRouteImport.update({
  id: '/admin/integrations',
  path: '/admin/integrations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminLeaveSettingsRoute =
  AuthedAdminLeaveSettingsRouteImport.update({
    id: '/admin/leave-settings',
    path: '/admin/leave-settings',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminStaffRoute = AuthedAdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminXeroRoute = AuthedAdminXeroRouteImport.update({
  id: '/admin/xero',
  path: '/admin/xero',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsJobIdRoute = AuthedJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsCreateRoute = AuthedJobsCreateRouteImport.update({
  id: '/jobs/create',
  path: '/jobs/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPurchasingStockRoute = AuthedPurchasingStockRouteImport.update({
  id: '/purchasing/stock',
  path: '/purchasing/stock',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsJobMovementRoute =
  AuthedReportsJobMovementRouteImport.update({
    id: '/reports/job-movement',
    path: '/reports/job-movement',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedReportsPayrollReconciliationRoute =
  AuthedReportsPayrollReconciliationRouteImport.update({
    id: '/reports/payroll-reconciliation',
    path: '/reports/payroll-reconciliation',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedReportsSalesForecastRoute =
  AuthedReportsSalesForecastRouteImport.update({
    id: '/reports/sales-forecast',
    path: '/reports/sales-forecast',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedReportsWipRoute = AuthedReportsWipRouteImport.update({
  id: '/reports/wip',
  path: '/reports/wip',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTimesheetsDailyRoute = AuthedTimesheetsDailyRouteImport.update({
  id: '/timesheets/daily',
  path: '/timesheets/daily',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTimesheetsEntryRoute = AuthedTimesheetsEntryRouteImport.update({
  id: '/timesheets/entry',
  path: '/timesheets/entry',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTimesheetsLeaveRoute = AuthedTimesheetsLeaveRouteImport.update({
  id: '/timesheets/leave',
  path: '/timesheets/leave',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTimesheetsMyTimeRoute = AuthedTimesheetsMyTimeRouteImport.update({
  id: '/timesheets/my-time',
  path: '/timesheets/my-time',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTimesheetsWeeklyRoute = AuthedTimesheetsWeeklyRouteImport.update({
  id: '/timesheets/weekly',
  path: '/timesheets/weekly',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminCompanyDefaultsIndexRoute =
  AuthedAdminCompanyDefaultsIndexRouteImport.update({
    id: '/admin/company-defaults/',
    path: '/admin/company-defaults/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminCompanyDefaultsSectionRoute =
  AuthedAdminCompanyDefaultsSectionRouteImport.update({
    id: '/admin/company-defaults/$section',
    path: '/admin/company-defaults/$section',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCrmCallsIndexRoute = AuthedCrmCallsIndexRouteImport.update({
  id: '/crm/calls/',
  path: '/crm/calls/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCrmCompaniesIndexRoute = AuthedCrmCompaniesIndexRouteImport.update({
  id: '/crm/companies/',
  path: '/crm/companies/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCrmCompaniesCompanyIdRoute =
  AuthedCrmCompaniesCompanyIdRouteImport.update({
    id: '/crm/companies/$companyId',
    path: '/crm/companies/$companyId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCrmPeopleIndexRoute = AuthedCrmPeopleIndexRouteImport.update({
  id: '/crm/people/',
  path: '/crm/people/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCrmPeoplePersonIdRoute = AuthedCrmPeoplePersonIdRouteImport.update({
  id: '/crm/people/$personId',
  path: '/crm/people/$personId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPurchasingPoIndexRoute = AuthedPurchasingPoIndexRouteImport.update({
  id: '/purchasing/po/',
  path: '/purchasing/po/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPurchasingPoPoIdRoute = AuthedPurchasingPoPoIdRouteImport.update({
  id: '/purchasing/po/$poId',
  path: '/purchasing/po/$poId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPurchasingPoCreateRoute =
  AuthedPurchasingPoCreateRouteImport.update({
    id: '/purchasing/po/create',
    path: '/purchasing/po/create',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedProcessDocumentsFormsCategoryIndexRoute =
  AuthedProcessDocumentsFormsCategoryIndexRouteImport.update({
    id: '/process-documents/forms/$category/',
    path: '/process-documents/forms/$category/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedProcessDocumentsFormsCategoryFormIdRoute =
  AuthedProcessDocumentsFormsCategoryFormIdRouteImport.update({
    id: '/process-documents/forms/$category/$formId',
    path: '/process-documents/forms/$category/$formId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/session-check': typeof SessionCheckRoute
  '/kanban': typeof AuthedKanbanRoute
  '/admin/integrations': typeof AuthedAdminIntegrationsRoute
  '/admin/leave-settings': typeof AuthedAdminLeaveSettingsRoute
  '/admin/staff': typeof AuthedAdminStaffRoute
  '/admin/xero': typeof AuthedAdminXeroRoute
  '/jobs/$jobId': typeof AuthedJobsJobIdRoute
  '/jobs/create': typeof AuthedJobsCreateRoute
  '/purchasing/stock': typeof AuthedPurchasingStockRoute
  '/reports/job-movement': typeof AuthedReportsJobMovementRoute
  '/reports/payroll-reconciliation': typeof AuthedReportsPayrollReconciliationRoute
  '/reports/sales-forecast': typeof AuthedReportsSalesForecastRoute
  '/reports/wip': typeof AuthedReportsWipRoute
  '/timesheets/daily': typeof AuthedTimesheetsDailyRoute
  '/timesheets/entry': typeof AuthedTimesheetsEntryRoute
  '/timesheets/leave': typeof AuthedTimesheetsLeaveRoute
  '/timesheets/my-time': typeof AuthedTimesheetsMyTimeRoute
  '/timesheets/weekly': typeof AuthedTimesheetsWeeklyRoute
  '/admin/company-defaults/$section': typeof AuthedAdminCompanyDefaultsSectionRoute
  '/crm/companies/$companyId': typeof AuthedCrmCompaniesCompanyIdRoute
  '/crm/people/$personId': typeof AuthedCrmPeoplePersonIdRoute
  '/purchasing/po/$poId': typeof AuthedPurchasingPoPoIdRoute
  '/purchasing/po/create': typeof AuthedPurchasingPoCreateRoute
  '/admin/company-defaults/': typeof AuthedAdminCompanyDefaultsIndexRoute
  '/crm/calls/': typeof AuthedCrmCallsIndexRoute
  '/crm/companies/': typeof AuthedCrmCompaniesIndexRoute
  '/crm/people/': typeof AuthedCrmPeopleIndexRoute
  '/purchasing/po/': typeof AuthedPurchasingPoIndexRoute
  '/process-documents/forms/$category/$formId': typeof AuthedProcessDocumentsFormsCategoryFormIdRoute
  '/process-documents/forms/$category/': typeof AuthedProcessDocumentsFormsCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/session-check': typeof SessionCheckRoute
  '/kanban': typeof AuthedKanbanRoute
  '/admin/integrations': typeof AuthedAdminIntegrationsRoute
  '/admin/leave-settings': typeof AuthedAdminLeaveSettingsRoute
  '/admin/staff': typeof AuthedAdminStaffRoute
  '/admin/xero': typeof AuthedAdminXeroRoute
  '/jobs/$jobId': typeof AuthedJobsJobIdRoute
  '/jobs/create': typeof AuthedJobsCreateRoute
  '/purchasing/stock': typeof AuthedPurchasingStockRoute
  '/reports/job-movement': typeof AuthedReportsJobMovementRoute
  '/reports/payroll-reconciliation': typeof AuthedReportsPayrollReconciliationRoute
  '/reports/sales-forecast': typeof AuthedReportsSalesForecastRoute
  '/reports/wip': typeof AuthedReportsWipRoute
  '/timesheets/daily': typeof AuthedTimesheetsDailyRoute
  '/timesheets/entry': typeof AuthedTimesheetsEntryRoute
  '/timesheets/leave': typeof AuthedTimesheetsLeaveRoute
  '/timesheets/my-time': typeof AuthedTimesheetsMyTimeRoute
  '/timesheets/weekly': typeof AuthedTimesheetsWeeklyRoute
  '/admin/company-defaults/$section': typeof AuthedAdminCompanyDefaultsSectionRoute
  '/crm/companies/$companyId': typeof AuthedCrmCompaniesCompanyIdRoute
  '/crm/people/$personId': typeof AuthedCrmPeoplePersonIdRoute
  '/purchasing/po/$poId': typeof AuthedPurchasingPoPoIdRoute
  '/purchasing/po/create': typeof AuthedPurchasingPoCreateRoute
  '/admin/company-defaults': typeof AuthedAdminCompanyDefaultsIndexRoute
  '/crm/calls': typeof AuthedCrmCallsIndexRoute
  '/crm/companies': typeof AuthedCrmCompaniesIndexRoute
  '/crm/people': typeof AuthedCrmPeopleIndexRoute
  '/purchasing/po': typeof AuthedPurchasingPoIndexRoute
  '/process-documents/forms/$category/$formId': typeof AuthedProcessDocumentsFormsCategoryFormIdRoute
  '/process-documents/forms/$category': typeof AuthedProcessDocumentsFormsCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/session-check': typeof SessionCheckRoute
  '/_authed/kanban': typeof AuthedKanbanRoute
  '/_authed/admin/integrations': typeof AuthedAdminIntegrationsRoute
  '/_authed/admin/leave-settings': typeof AuthedAdminLeaveSettingsRoute
  '/_authed/admin/staff': typeof AuthedAdminStaffRoute
  '/_authed/admin/xero': typeof AuthedAdminXeroRoute
  '/_authed/jobs/$jobId': typeof AuthedJobsJobIdRoute
  '/_authed/jobs/create': typeof AuthedJobsCreateRoute
  '/_authed/purchasing/stock': typeof AuthedPurchasingStockRoute
  '/_authed/reports/job-movement': typeof AuthedReportsJobMovementRoute
  '/_authed/reports/payroll-reconciliation': typeof AuthedReportsPayrollReconciliationRoute
  '/_authed/reports/sales-forecast': typeof AuthedReportsSalesForecastRoute
  '/_authed/reports/wip': typeof AuthedReportsWipRoute
  '/_authed/timesheets/daily': typeof AuthedTimesheetsDailyRoute
  '/_authed/timesheets/entry': typeof AuthedTimesheetsEntryRoute
  '/_authed/timesheets/leave': typeof AuthedTimesheetsLeaveRoute
  '/_authed/timesheets/my-time': typeof AuthedTimesheetsMyTimeRoute
  '/_authed/timesheets/weekly': typeof AuthedTimesheetsWeeklyRoute
  '/_authed/admin/company-defaults/$section': typeof AuthedAdminCompanyDefaultsSectionRoute
  '/_authed/crm/companies/$companyId': typeof AuthedCrmCompaniesCompanyIdRoute
  '/_authed/crm/people/$personId': typeof AuthedCrmPeoplePersonIdRoute
  '/_authed/purchasing/po/$poId': typeof AuthedPurchasingPoPoIdRoute
  '/_authed/purchasing/po/create': typeof AuthedPurchasingPoCreateRoute
  '/_authed/admin/company-defaults/': typeof AuthedAdminCompanyDefaultsIndexRoute
  '/_authed/crm/calls/': typeof AuthedCrmCallsIndexRoute
  '/_authed/crm/companies/': typeof AuthedCrmCompaniesIndexRoute
  '/_authed/crm/people/': typeof AuthedCrmPeopleIndexRoute
  '/_authed/purchasing/po/': typeof AuthedPurchasingPoIndexRoute
  '/_authed/process-documents/forms/$category/$formId': typeof AuthedProcessDocumentsFormsCategoryFormIdRoute
  '/_authed/process-documents/forms/$category/': typeof AuthedProcessDocumentsFormsCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/session-check'
    | '/kanban'
    | '/admin/integrations'
    | '/admin/leave-settings'
    | '/admin/staff'
    | '/admin/xero'
    | '/jobs/$jobId'
    | '/jobs/create'
    | '/purchasing/stock'
    | '/reports/job-movement'
    | '/reports/payroll-reconciliation'
    | '/reports/sales-forecast'
    | '/reports/wip'
    | '/timesheets/daily'
    | '/timesheets/entry'
    | '/timesheets/leave'
    | '/timesheets/my-time'
    | '/timesheets/weekly'
    | '/admin/company-defaults/$section'
    | '/crm/companies/$companyId'
    | '/crm/people/$personId'
    | '/purchasing/po/$poId'
    | '/purchasing/po/create'
    | '/admin/company-defaults/'
    | '/crm/calls/'
    | '/crm/companies/'
    | '/crm/people/'
    | '/purchasing/po/'
    | '/process-documents/forms/$category/$formId'
    | '/process-documents/forms/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/session-check'
    | '/kanban'
    | '/admin/integrations'
    | '/admin/leave-settings'
    | '/admin/staff'
    | '/admin/xero'
    | '/jobs/$jobId'
    | '/jobs/create'
    | '/purchasing/stock'
    | '/reports/job-movement'
    | '/reports/payroll-reconciliation'
    | '/reports/sales-forecast'
    | '/reports/wip'
    | '/timesheets/daily'
    | '/timesheets/entry'
    | '/timesheets/leave'
    | '/timesheets/my-time'
    | '/timesheets/weekly'
    | '/admin/company-defaults/$section'
    | '/crm/companies/$companyId'
    | '/crm/people/$personId'
    | '/purchasing/po/$poId'
    | '/purchasing/po/create'
    | '/admin/company-defaults'
    | '/crm/calls'
    | '/crm/companies'
    | '/crm/people'
    | '/purchasing/po'
    | '/process-documents/forms/$category/$formId'
    | '/process-documents/forms/$category'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/session-check'
    | '/_authed/kanban'
    | '/_authed/admin/integrations'
    | '/_authed/admin/leave-settings'
    | '/_authed/admin/staff'
    | '/_authed/admin/xero'
    | '/_authed/jobs/$jobId'
    | '/_authed/jobs/create'
    | '/_authed/purchasing/stock'
    | '/_authed/reports/job-movement'
    | '/_authed/reports/payroll-reconciliation'
    | '/_authed/reports/sales-forecast'
    | '/_authed/reports/wip'
    | '/_authed/timesheets/daily'
    | '/_authed/timesheets/entry'
    | '/_authed/timesheets/leave'
    | '/_authed/timesheets/my-time'
    | '/_authed/timesheets/weekly'
    | '/_authed/admin/company-defaults/$section'
    | '/_authed/crm/companies/$companyId'
    | '/_authed/crm/people/$personId'
    | '/_authed/purchasing/po/$poId'
    | '/_authed/purchasing/po/create'
    | '/_authed/admin/company-defaults/'
    | '/_authed/crm/calls/'
    | '/_authed/crm/companies/'
    | '/_authed/crm/people/'
    | '/_authed/purchasing/po/'
    | '/_authed/process-documents/forms/$category/$formId'
    | '/_authed/process-documents/forms/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SessionCheckRoute: typeof SessionCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-check': {
      id: '/session-check'
      path: '/session-check'
      fullPath: '/session-check'
      preLoaderRoute: typeof SessionCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/kanban': {
      id: '/_authed/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthedKanbanRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/integrations': {
      id: '/_authed/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AuthedAdminIntegrationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/leave-settings': {
      id: '/_authed/admin/leave-settings'
      path: '/admin/leave-settings'
      fullPath: '/admin/leave-settings'
      preLoaderRoute: typeof AuthedAdminLeaveSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/staff': {
      id: '/_authed/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthedAdminStaffRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/xero': {
      id: '/_authed/admin/xero'
      path: '/admin/xero'
      fullPath: '/admin/xero'
      preLoaderRoute: typeof AuthedAdminXeroRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs/$jobId': {
      id: '/_authed/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AuthedJobsJobIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs/create': {
      id: '/_authed/jobs/create'
      path: '/jobs/create'
      fullPath: '/jobs/create'
      preLoaderRoute: typeof AuthedJobsCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/purchasing/stock': {
      id: '/_authed/purchasing/stock'
      path: '/purchasing/stock'
      fullPath: '/purchasing/stock'
      preLoaderRoute: typeof AuthedPurchasingStockRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports/job-movement': {
      id: '/_authed/reports/job-movement'
      path: '/reports/job-movement'
      fullPath: '/reports/job-movement'
      preLoaderRoute: typeof AuthedReportsJobMovementRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports/payroll-reconciliation': {
      id: '/_authed/reports/payroll-reconciliation'
      path: '/reports/payroll-reconciliation'
      fullPath: '/reports/payroll-reconciliation'
      preLoaderRoute: typeof AuthedReportsPayrollReconciliationRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports/sales-forecast': {
      id: '/_authed/reports/sales-forecast'
      path: '/reports/sales-forecast'
      fullPath: '/reports/sales-forecast'
      preLoaderRoute: typeof AuthedReportsSalesForecastRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports/wip': {
      id: '/_authed/reports/wip'
      path: '/reports/wip'
      fullPath: '/reports/wip'
      preLoaderRoute: typeof AuthedReportsWipRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/timesheets/daily': {
      id: '/_authed/timesheets/daily'
      path: '/timesheets/daily'
      fullPath: '/timesheets/daily'
      preLoaderRoute: typeof AuthedTimesheetsDailyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/timesheets/entry': {
      id: '/_authed/timesheets/entry'
      path: '/timesheets/entry'
      fullPath: '/timesheets/entry'
      preLoaderRoute: typeof AuthedTimesheetsEntryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/timesheets/leave': {
      id: '/_authed/timesheets/leave'
      path: '/timesheets/leave'
      fullPath: '/timesheets/leave'
      preLoaderRoute: typeof AuthedTimesheetsLeaveRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/timesheets/my-time': {
      id: '/_authed/timesheets/my-time'
      path: '/timesheets/my-time'
      fullPath: '/timesheets/my-time'
      preLoaderRoute: typeof AuthedTimesheetsMyTimeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/timesheets/weekly': {
      id: '/_authed/timesheets/weekly'
      path: '/timesheets/weekly'
      fullPath: '/timesheets/weekly'
      preLoaderRoute: typeof AuthedTimesheetsWeeklyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/company-defaults/': {
      id: '/_authed/admin/company-defaults/'
      path: '/admin/company-defaults'
      fullPath: '/admin/company-defaults/'
      preLoaderRoute: typeof AuthedAdminCompanyDefaultsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/company-defaults/$section': {
      id: '/_authed/admin/company-defaults/$section'
      path: '/admin/company-defaults/$section'
      fullPath: '/admin/company-defaults/$section'
      preLoaderRoute: typeof AuthedAdminCompanyDefaultsSectionRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/crm/calls/': {
      id: '/_authed/crm/calls/'
      path: '/crm/calls'
      fullPath: '/crm/calls/'
      preLoaderRoute: typeof AuthedCrmCallsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/crm/companies/': {
      id: '/_authed/crm/companies/'
      path: '/crm/companies'
      fullPath: '/crm/companies/'
      preLoaderRoute: typeof AuthedCrmCompaniesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/crm/companies/$companyId': {
      id: '/_authed/crm/companies/$companyId'
      path: '/crm/companies/$companyId'
      fullPath: '/crm/companies/$companyId'
      preLoaderRoute: typeof AuthedCrmCompaniesCompanyIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/crm/people/': {
      id: '/_authed/crm/people/'
      path: '/crm/people'
      fullPath: '/crm/people/'
      preLoaderRoute: typeof AuthedCrmPeopleIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/crm/people/$personId': {
      id: '/_authed/crm/people/$personId'
      path: '/crm/people/$personId'
      fullPath: '/crm/people/$personId'
      preLoaderRoute: typeof AuthedCrmPeoplePersonIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/purchasing/po/': {
      id: '/_authed/purchasing/po/'
      path: '/purchasing/po'
      fullPath: '/purchasing/po/'
      preLoaderRoute: typeof AuthedPurchasingPoIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/purchasing/po/$poId': {
      id: '/_authed/purchasing/po/$poId'
      path: '/purchasing/po/$poId'
      fullPath: '/purchasing/po/$poId'
      preLoaderRoute: typeof AuthedPurchasingPoPoIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/purchasing/po/create': {
      id: '/_authed/purchasing/po/create'
      path: '/purchasing/po/create'
      fullPath: '/purchasing/po/create'
      preLoaderRoute: typeof AuthedPurchasingPoCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/process-documents/forms/$category/': {
      id: '/_authed/process-documents/forms/$category/'
      path: '/process-documents/forms/$category'
      fullPath: '/process-documents/forms/$category/'
      preLoaderRoute: typeof AuthedProcessDocumentsFormsCategoryIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/process-documents/forms/$category/$formId': {
      id: '/_authed/process-documents/forms/$category/$formId'
      path: '/process-documents/forms/$category/$formId'
      fullPath: '/process-documents/forms/$category/$formId'
      preLoaderRoute: typeof AuthedProcessDocumentsFormsCategoryFormIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedKanbanRoute: typeof AuthedKanbanRoute
  AuthedAdminIntegrationsRoute: typeof AuthedAdminIntegrationsRoute
  AuthedAdminLeaveSettingsRoute: typeof AuthedAdminLeaveSettingsRoute
  AuthedAdminStaffRoute: typeof AuthedAdminStaffRoute
  AuthedAdminXeroRoute: typeof AuthedAdminXeroRoute
  AuthedJobsJobIdRoute: typeof AuthedJobsJobIdRoute
  AuthedJobsCreateRoute: typeof AuthedJobsCreateRoute
  AuthedPurchasingStockRoute: typeof AuthedPurchasingStockRoute
  AuthedReportsJobMovementRoute: typeof AuthedReportsJobMovementRoute
  AuthedReportsPayrollReconciliationRoute: typeof AuthedReportsPayrollReconciliationRoute
  AuthedReportsSalesForecastRoute: typeof AuthedReportsSalesForecastRoute
  AuthedReportsWipRoute: typeof AuthedReportsWipRoute
  AuthedTimesheetsDailyRoute: typeof AuthedTimesheetsDailyRoute
  AuthedTimesheetsEntryRoute: typeof AuthedTimesheetsEntryRoute
  AuthedTimesheetsLeaveRoute: typeof AuthedTimesheetsLeaveRoute
  AuthedTimesheetsMyTimeRoute: typeof AuthedTimesheetsMyTimeRoute
  AuthedTimesheetsWeeklyRoute: typeof AuthedTimesheetsWeeklyRoute
  AuthedAdminCompanyDefaultsSectionRoute: typeof AuthedAdminCompanyDefaultsSectionRoute
  AuthedCrmCompaniesCompanyIdRoute: typeof AuthedCrmCompaniesCompanyIdRoute
  AuthedCrmPeoplePersonIdRoute: typeof AuthedCrmPeoplePersonIdRoute
  AuthedPurchasingPoPoIdRoute: typeof AuthedPurchasingPoPoIdRoute
  AuthedPurchasingPoCreateRoute: typeof AuthedPurchasingPoCreateRoute
  AuthedAdminCompanyDefaultsIndexRoute: typeof AuthedAdminCompanyDefaultsIndexRoute
  AuthedCrmCallsIndexRoute: typeof AuthedCrmCallsIndexRoute
  AuthedCrmCompaniesIndexRoute: typeof AuthedCrmCompaniesIndexRoute
  AuthedCrmPeopleIndexRoute: typeof AuthedCrmPeopleIndexRoute
  AuthedPurchasingPoIndexRoute: typeof AuthedPurchasingPoIndexRoute
  AuthedProcessDocumentsFormsCategoryFormIdRoute: typeof AuthedProcessDocumentsFormsCategoryFormIdRoute
  AuthedProcessDocumentsFormsCategoryIndexRoute: typeof AuthedProcessDocumentsFormsCategoryIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedKanbanRoute: AuthedKanbanRoute,
  AuthedAdminIntegrationsRoute: AuthedAdminIntegrationsRoute,
  AuthedAdminLeaveSettingsRoute: AuthedAdminLeaveSettingsRoute,
  AuthedAdminStaffRoute: AuthedAdminStaffRoute,
  AuthedAdminXeroRoute: AuthedAdminXeroRoute,
  AuthedJobsJobIdRoute: AuthedJobsJobIdRoute,
  AuthedJobsCreateRoute: AuthedJobsCreateRoute,
  AuthedPurchasingStockRoute: AuthedPurchasingStockRoute,
  AuthedReportsJobMovementRoute: AuthedReportsJobMovementRoute,
  AuthedReportsPayrollReconciliationRoute:
    AuthedReportsPayrollReconciliationRoute,
  AuthedReportsSalesForecastRoute: AuthedReportsSalesForecastRoute,
  AuthedReportsWipRoute: AuthedReportsWipRoute,
  AuthedTimesheetsDailyRoute: AuthedTimesheetsDailyRoute,
  AuthedTimesheetsEntryRoute: AuthedTimesheetsEntryRoute,
  AuthedTimesheetsLeaveRoute: AuthedTimesheetsLeaveRoute,
  AuthedTimesheetsMyTimeRoute: AuthedTimesheetsMyTimeRoute,
  AuthedTimesheetsWeeklyRoute: AuthedTimesheetsWeeklyRoute,
  AuthedAdminCompanyDefaultsSectionRoute:
    AuthedAdminCompanyDefaultsSectionRoute,
  AuthedCrmCompaniesCompanyIdRoute: AuthedCrmCompaniesCompanyIdRoute,
  AuthedCrmPeoplePersonIdRoute: AuthedCrmPeoplePersonIdRoute,
  AuthedPurchasingPoPoIdRoute: AuthedPurchasingPoPoIdRoute,
  AuthedPurchasingPoCreateRoute: AuthedPurchasingPoCreateRoute,
  AuthedAdminCompanyDefaultsIndexRoute: AuthedAdminCompanyDefaultsIndexRoute,
  AuthedCrmCallsIndexRoute: AuthedCrmCallsIndexRoute,
  AuthedCrmCompaniesIndexRoute: AuthedCrmCompaniesIndexRoute,
  AuthedCrmPeopleIndexRoute: AuthedCrmPeopleIndexRoute,
  AuthedPurchasingPoIndexRoute: AuthedPurchasingPoIndexRoute,
  AuthedProcessDocumentsFormsCategoryFormIdRoute:
    AuthedProcessDocumentsFormsCategoryFormIdRoute,
  AuthedProcessDocumentsFormsCategoryIndexRoute:
    AuthedProcessDocumentsFormsCategoryIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SessionCheckRoute: SessionCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
