#!/bin/bash
# Check requirements.txt is the deterministic export of poetry.lock.
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
    echo "# autogenerated from poetry.lock via poetry export"
    poetry export --without-hashes --without-urls --all-groups --all-extras -f requirements.txt
} > "$tmp"

if cmp -s "$tmp" requirements.txt; then
    exit 0
fi

echo "ERROR: requirements.txt is stale for poetry.lock." >&2
echo "Run: scripts/generate_requirements.sh" >&2
echo "" >&2
echo "Poetry version:" >&2
poetry --version >&2 || true
echo "" >&2
echo "Diff:" >&2
diff -u requirements.txt "$tmp" >&2 || true
exit 1
