#!/bin/bash
# Regenerate requirements.txt from poetry.lock for Codesight.
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
    echo "# autogenerated from poetry.lock via poetry export"
    poetry export --without-hashes --without-urls --all-groups --all-extras -f requirements.txt
} > "$tmp"

if ! cmp -s "$tmp" requirements.txt; then
    mv "$tmp" requirements.txt
    trap - EXIT
fi
