# Generated by Django 6.0.7 on 2026-08-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotebookLmLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Menu item name", max_length=100)),
                ("url", models.URLField(help_text="NotebookLM notebook URL")),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="Show this link in the training menu"
                    ),
                ),
                (
                    "restriction",
                    models.CharField(
                        choices=[
                            ("none", "All staff"),
                            ("superuser", "Superusers only"),
                        ],
                        default="none",
                        help_text="Who may see this link in the menu",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Menu display order"),
                ),
            ],
            options={
                "verbose_name": "NotebookLM Link",
                "verbose_name_plural": "NotebookLM Links",
                "db_table": "workflow_notebooklmlink",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AIProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Friendly name for this provider", max_length=100),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="API Key for this AI Provider",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "default",
                    models.BooleanField(
                        default=False, help_text="Use this provider as the default"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        help_text="Model name (e.g., gemini-flash-latest)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("Claude", "Anthropic"),
                            ("Gemini", "Google"),
                            ("Mistral", "Mistral"),
                            ("OpenAI", "Openai"),
                        ],
                        help_text="Type of AI provider",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Provider",
                "verbose_name_plural": "AI Providers",
                "db_table": "workflow_aiprovider",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("api_key", ""), _negated=True),
                        name="workflow_aiprovider_api_key_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("model_name", ""), _negated=True),
                        name="model_name_not_blank",
                    ),
                ],
            },
        ),
    ]
