# Generated by Django 6.0.4 on 2026-07-06 00:12

import uuid

import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_baseline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapeJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("products_scraped", models.IntegerField(default=0)),
                ("products_failed", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scrape_jobs",
                        to="client.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scrape Job",
                "verbose_name_plural": "Scrape Jobs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "credential_type",
                    models.CharField(
                        choices=[
                            ("username_password", "Username and password"),
                            ("api_key", "API key"),
                            ("api_key_header", "API key header"),
                            ("oauth2", "OAuth 2"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "username",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "password",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "api_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                ("extra_config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_credentials",
                        to="client.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Credential",
                "verbose_name_plural": "Supplier Credentials",
                "ordering": ["supplier__name", "label"],
            },
        ),
        migrations.CreateModel(
            name="SupplierPriceList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Original filename of the uploaded price list",
                        max_length=255,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_lists",
                        to="client.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Price List",
                "verbose_name_plural": "Supplier Price Lists",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=500)),
                (
                    "item_no",
                    models.CharField(
                        help_text="Supplier's item/SKU number", max_length=100
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("specifications", models.TextField(blank=True, null=True)),
                (
                    "variant_id",
                    models.CharField(
                        help_text="Unique variant identifier from supplier",
                        max_length=100,
                    ),
                ),
                (
                    "variant_width",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "variant_length",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "variant_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price_unit",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'per metre', 'each'",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("variant_available_stock", models.IntegerField(blank=True, null=True)),
                (
                    "url",
                    models.URLField(
                        help_text="Direct URL to this product on supplier's website",
                        max_length=1000,
                    ),
                ),
                (
                    "is_discontinued",
                    models.BooleanField(
                        default=False,
                        help_text="Product URL no longer in supplier sitemap; skip future scrapes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_scraped", models.DateTimeField(auto_now=True)),
                (
                    "parsed_item_code",
                    models.CharField(
                        blank=True,
                        help_text="Item code parsed for inventory mapping",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "parsed_description",
                    models.CharField(
                        blank=True,
                        help_text="Standardized description for inventory",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "parsed_metal_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("stainless_steel", "Stainless Steel"),
                            ("mild_steel", "Mild Steel"),
                            ("aluminium", "Aluminium"),
                            ("brass", "Brass"),
                            ("copper", "Copper"),
                            ("titanium", "Titanium"),
                            ("zinc", "Zinc"),
                            ("galvanized", "Galvanized"),
                            ("unspecified", "Unspecified"),
                            ("other", "Other"),
                        ],
                        help_text="Metal type parsed from product specifications",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "parsed_alloy",
                    models.CharField(
                        blank=True,
                        help_text="Alloy specification (e.g., 304, 6061)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "parsed_specifics",
                    models.CharField(
                        blank=True,
                        help_text="Specific details parsed from product data",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "parsed_dimensions",
                    models.CharField(
                        blank=True,
                        help_text="Standardized dimensions format",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "parsed_unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Standardized unit cost",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "parsed_price_unit",
                    models.CharField(
                        blank=True,
                        help_text="Standardized price unit (e.g., 'per metre', 'each')",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("parsed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parser_version",
                    models.CharField(
                        blank=True,
                        help_text="Version of parser used for this data",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "parser_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Parser confidence score 0.00-1.00",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "mapping_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA-256 hash linking to ProductParsingMapping for this product",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="quoting.supplierpricelist",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scraped_products",
                        to="client.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierScraperConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scraper_class", models.CharField(db_index=True, max_length=255)),
                ("portal_url", models.URLField(max_length=1000)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scraper_configs",
                        to="quoting.suppliercredential",
                    ),
                ),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scraper_config",
                        to="client.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Scraper Config",
                "verbose_name_plural": "Supplier Scraper Configs",
                "ordering": ["supplier__name"],
            },
        ),
        migrations.CreateModel(
            name="ProductParsingMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "input_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash of normalized input data",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(help_text="Original input data that was parsed"),
                ),
                (
                    "derived_key",
                    models.CharField(
                        blank=True,
                        help_text="Derived key for this mapping, if applicable",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "mapped_item_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mapped_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mapped_metal_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("stainless_steel", "Stainless Steel"),
                            ("mild_steel", "Mild Steel"),
                            ("aluminium", "Aluminium"),
                            ("brass", "Brass"),
                            ("copper", "Copper"),
                            ("titanium", "Titanium"),
                            ("zinc", "Zinc"),
                            ("galvanized", "Galvanized"),
                            ("unspecified", "Unspecified"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "mapped_alloy",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "mapped_specifics",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mapped_dimensions",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mapped_unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "mapped_price_unit",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "parser_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "parser_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "llm_response",
                    models.JSONField(
                        blank=True,
                        help_text="Full LLM response for debugging",
                        null=True,
                    ),
                ),
                (
                    "is_validated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this mapping has been manually validated",
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this mapping was validated",
                        null=True,
                    ),
                ),
                (
                    "validation_notes",
                    models.TextField(
                        blank=True, help_text="Notes from manual validation", null=True
                    ),
                ),
                (
                    "item_code_is_in_xero",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the mapped item code exists in Xero inventory (Stock model)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who validated this mapping",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Parsing Mapping",
                "verbose_name_plural": "Product Parsing Mappings",
                "indexes": [
                    models.Index(
                        fields=["input_hash"], name="quoting_pro_input_h_ffd369_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="quoting_pro_created_09311f_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="suppliercredential",
            constraint=models.UniqueConstraint(
                fields=("supplier", "label"), name="unique_supplier_credential_label"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierproduct",
            index=models.Index(
                fields=["variant_id"], name="quoting_sup_variant_948a79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierproduct",
            index=models.Index(
                fields=["item_no"], name="quoting_sup_item_no_c2e6f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierproduct",
            index=models.Index(fields=["url"], name="quoting_sup_url_2d3c4a_idx"),
        ),
        migrations.AddIndex(
            model_name="supplierproduct",
            index=models.Index(
                fields=["product_name"], name="quoting_sup_product_d21402_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="supplierproduct",
            unique_together={("supplier", "url", "item_no", "variant_id")},
        ),
        migrations.AddConstraint(
            model_name="supplierscraperconfig",
            constraint=models.UniqueConstraint(
                fields=("scraper_class",), name="unique_supplier_scraper_class"
            ),
        ),
    ]
