# Generated by Django 6.0.7 on 2026-07-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quoting", "0002_forbid_blank_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productparsingmapping",
            name="mapped_metal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("stainless_steel", "Stainless Steel"),
                    ("mild_steel", "Mild Steel"),
                    ("aluminium", "Aluminium"),
                    ("brass", "Brass"),
                    ("copper", "Copper"),
                    ("titanium", "Titanium"),
                    ("zinc", "Zinc"),
                    ("galvanized", "Galvanized"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplierproduct",
            name="parsed_metal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("stainless_steel", "Stainless Steel"),
                    ("mild_steel", "Mild Steel"),
                    ("aluminium", "Aluminium"),
                    ("brass", "Brass"),
                    ("copper", "Copper"),
                    ("titanium", "Titanium"),
                    ("zinc", "Zinc"),
                    ("galvanized", "Galvanized"),
                    ("other", "Other"),
                ],
                help_text="Metal type parsed from product specifications",
                max_length=50,
                null=True,
            ),
        ),
    ]
