# Generated by Codex on 2026-05-15

from django.db import migrations, models


def use_aluminium(apps, schema_editor):
    ProductParsingMapping = apps.get_model("quoting", "ProductParsingMapping")
    SupplierProduct = apps.get_model("quoting", "SupplierProduct")
    legacy_value = "alumin" + "um"

    ProductParsingMapping.objects.filter(mapped_metal_type=legacy_value).update(
        mapped_metal_type="aluminium"
    )
    SupplierProduct.objects.filter(parsed_metal_type=legacy_value).update(
        parsed_metal_type="aluminium"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("quoting", "0018_mark_404_products_as_discontinued"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productparsingmapping",
            name="mapped_metal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("stainless_steel", "Stainless Steel"),
                    ("mild_steel", "Mild Steel"),
                    ("aluminium", "Aluminium"),
                    ("brass", "Brass"),
                    ("copper", "Copper"),
                    ("titanium", "Titanium"),
                    ("zinc", "Zinc"),
                    ("galvanized", "Galvanized"),
                    ("unspecified", "Unspecified"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplierproduct",
            name="parsed_metal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("stainless_steel", "Stainless Steel"),
                    ("mild_steel", "Mild Steel"),
                    ("aluminium", "Aluminium"),
                    ("brass", "Brass"),
                    ("copper", "Copper"),
                    ("titanium", "Titanium"),
                    ("zinc", "Zinc"),
                    ("galvanized", "Galvanized"),
                    ("unspecified", "Unspecified"),
                    ("other", "Other"),
                ],
                help_text="Metal type parsed from product specifications",
                max_length=50,
                null=True,
            ),
        ),
        migrations.RunPython(use_aluminium, migrations.RunPython.noop),
    ]
