# Generated by Django 6.0.4 on 2026-06-11 23:59

import uuid

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0022_client_name_trgm_index"),
        ("quoting", "0019_use_aluminium_metal_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "credential_type",
                    models.CharField(
                        choices=[
                            ("username_password", "Username and password"),
                            ("api_key", "API key"),
                            ("api_key_header", "API key header"),
                            ("oauth2", "OAuth 2"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "username",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "password",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "api_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                ("extra_config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_credentials",
                        to="client.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Credential",
                "verbose_name_plural": "Supplier Credentials",
                "ordering": ["supplier__name", "label"],
            },
        ),
        migrations.CreateModel(
            name="SupplierScraperConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scraper_class", models.CharField(db_index=True, max_length=255)),
                ("portal_url", models.URLField(max_length=1000)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scraper_configs",
                        to="quoting.suppliercredential",
                    ),
                ),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scraper_config",
                        to="client.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Scraper Config",
                "verbose_name_plural": "Supplier Scraper Configs",
                "ordering": ["supplier__name"],
            },
        ),
        migrations.AddConstraint(
            model_name="suppliercredential",
            constraint=models.UniqueConstraint(
                fields=("supplier", "label"), name="unique_supplier_credential_label"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierscraperconfig",
            constraint=models.UniqueConstraint(
                fields=("scraper_class",), name="unique_supplier_scraper_class"
            ),
        ),
    ]
