# Generated by Django 6.1.1 on 2026-09-06 08:09

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VendorCall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        choices=[
                            ("xero", "Xero"),
                            ("xero_token", "Xero token endpoint"),
                            ("llm", "LLM gateway"),
                            ("maps", "Google Maps"),
                            ("phone", "Phone provider"),
                        ],
                        max_length=20,
                    ),
                ),
                ("method", models.CharField(max_length=10)),
                ("endpoint", models.CharField(max_length=255)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("duration_ms", models.PositiveIntegerField()),
                ("status_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("day_remaining", models.IntegerField(blank=True, null=True)),
                ("minute_remaining", models.IntegerField(blank=True, null=True)),
                ("tokens_in", models.PositiveIntegerField(blank=True, null=True)),
                ("tokens_out", models.PositiveIntegerField(blank=True, null=True)),
                ("model_name", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["vendor", "-occurred_at"], name="vendorcall_vendor_time_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("model_name", ""), _negated=True),
                        name="vendorcall_model_name_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("method", ""), _negated=True),
                        name="vendorcall_method_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("endpoint", ""), _negated=True),
                        name="vendorcall_endpoint_not_blank",
                    ),
                ],
            },
        ),
    ]
