# Generated by Django 6.1.1 on 2026-09-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observability", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorcall",
            name="estimated_cost_usd",
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
