# This file is autogenerated by update_init.py script

from .apps import AccountsConfig

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .models import Staff, StaffManager
        from .permissions import CanManageTimesheets, IsStaff
        from .serializers import (
            BaseStaffSerializer,
            CustomTokenObtainPairSerializer,
            EmptySerializer,
            GenericStaffMethodsMixin,
            KanbanStaffSerializer,
            StaffCreateSerializer,
            StaffSerializer,
            TokenObtainPairResponseSerializer,
            TokenRefreshResponseSerializer,
            UserProfileSerializer,
        )
        from .staff_anonymization import create_staff_profile, generate_email
        from .utils import (
            get_displayable_staff,
            get_excluded_staff,
            get_staff_from_nickname,
            is_valid_uuid,
        )
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "AccountsConfig",
    "BaseStaffSerializer",
    "CanManageTimesheets",
    "CustomTokenObtainPairSerializer",
    "EmptySerializer",
    "GenericStaffMethodsMixin",
    "IsStaff",
    "KanbanStaffSerializer",
    "Staff",
    "StaffCreateSerializer",
    "StaffManager",
    "StaffSerializer",
    "TokenObtainPairResponseSerializer",
    "TokenRefreshResponseSerializer",
    "UserProfileSerializer",
    "create_staff_profile",
    "generate_email",
    "get_displayable_staff",
    "get_excluded_staff",
    "get_staff_from_nickname",
    "is_valid_uuid",
]
