/**
 * Golden-vector contract test (ADR 0004): the TypeScript canonicaliser must
 * reproduce the Python-generated checksums bit-for-bit. The vectors live at
 * repo-root tests/delta-checksum-goldens.json (regenerated by
 * scripts/gen_delta_goldens.py — Python is authoritative).
 */
import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

import { computeJobDeltaChecksum } from '../checksum'

interface GoldenVector {
  name: string
  job_id: string
  js_values: Record<string, unknown>
  checksum: string
}

const goldens: GoldenVector[] = JSON.parse(
  readFileSync(
    new URL('../../../../../tests/delta-checksum-goldens.json', import.meta.url),
    'utf8',
  ),
)

describe('delta checksum golden vectors (Python parity)', () => {
  it.each(goldens.map((v) => [v.name, v] as const))('%s', async (_name, vector) => {
    const checksum = await computeJobDeltaChecksum(vector.job_id, vector.js_values)
    expect(checksum).toBe(vector.checksum)
  })
})
