# This file is autogenerated by update_init.py script

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .workshop_schedule_serializer import (
            AssignedStaffSerializer,
            DaySerializer,
            ScheduledJobSerializer,
            UnscheduledJobSerializer,
            WorkshopScheduleQuerySerializer,
            WorkshopScheduleResponseSerializer,
        )
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "AssignedStaffSerializer",
    "DaySerializer",
    "ScheduledJobSerializer",
    "UnscheduledJobSerializer",
    "WorkshopScheduleQuerySerializer",
    "WorkshopScheduleResponseSerializer",
]
