# This file is autogenerated by update_init.py script

from .address_views import AddressValidateView
from .company_rest_views import (
    CompanyCreateRestView,
    CompanyJobsRestView,
    CompanyListAllRestView,
    CompanyRetrieveRestView,
    CompanySearchRestView,
    CompanyUpdateRestView,
    JobPersonRestView,
)
from .person_views import (
    CompanyPeopleView,
    CompanyPersonPhoneOwnershipView,
    PersonCompanyLinkDetailView,
    PersonCompanyLinksView,
    PersonContactMethodDetailView,
    PersonContactMethodsView,
    PersonDetailView,
    PersonListView,
)
from .supplier_search_alias_views import (
    CompanySupplierAliasListCreateView,
    SupplierAliasDetailView,
)

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .contact_method_viewset import ContactMethodViewSet
        from .supplier_pickup_address_viewset import SupplierPickupAddressViewSet
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "AddressValidateView",
    "CompanyCreateRestView",
    "CompanyJobsRestView",
    "CompanyListAllRestView",
    "CompanyPeopleView",
    "CompanyPersonPhoneOwnershipView",
    "CompanyRetrieveRestView",
    "CompanySearchRestView",
    "CompanySupplierAliasListCreateView",
    "CompanyUpdateRestView",
    "ContactMethodViewSet",
    "JobPersonRestView",
    "PersonCompanyLinkDetailView",
    "PersonCompanyLinksView",
    "PersonContactMethodDetailView",
    "PersonContactMethodsView",
    "PersonDetailView",
    "PersonListView",
    "SupplierAliasDetailView",
    "SupplierPickupAddressViewSet",
]
