# This file is autogenerated by update_init.py script

from .apps import CrmConfig

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .models import (
            PhoneCallRecord,
            PhoneCallRecording,
            PhoneNumberClientMapping,
        )
        from .serializers import (
            PhoneCallRecordSerializer,
            PhoneCallRecordingSerializer,
            PhoneNumberClientMappingSerializer,
        )
        from .tasks import delete_archived_phone_recordings_task, sync_phone_calls_task
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "CrmConfig",
    "PhoneCallRecord",
    "PhoneCallRecordSerializer",
    "PhoneCallRecording",
    "PhoneCallRecordingSerializer",
    "PhoneNumberClientMapping",
    "PhoneNumberClientMappingSerializer",
    "delete_archived_phone_recordings_task",
    "sync_phone_calls_task",
]
