# This file is autogenerated by update_init.py script

from .apps import CrmConfig

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .models import PhoneCallRecord, PhoneCallRecording
        from .serializers import (
            PhoneCallJobLinkPayload,
            PhoneCallPayloadModel,
            PhoneCallRecordSerializer,
            PhoneCallRecordingResponse,
            PhoneCallRecordingSerializer,
            PhoneNumberAssignmentPayload,
        )
        from .tasks import delete_archived_phone_recordings_task, sync_phone_calls_task
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "CrmConfig",
    "PhoneCallJobLinkPayload",
    "PhoneCallPayloadModel",
    "PhoneCallRecord",
    "PhoneCallRecordSerializer",
    "PhoneCallRecording",
    "PhoneCallRecordingResponse",
    "PhoneCallRecordingSerializer",
    "PhoneNumberAssignmentPayload",
    "delete_archived_phone_recordings_task",
    "sync_phone_calls_task",
]
