# This file is autogenerated by update_init.py script

from .apps import CrmConfig

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .models import (
            PhoneCallRecord,
            PhoneCallRecording,
            PhoneEndpoint,
            PhoneProviderSettings,
        )
        from .serializers import (
            PhoneCallJobLinkSerializer,
            PhoneCallRecordSerializer,
            PhoneCallRecordingSerializer,
            PhoneEndpointAttrs,
            PhoneEndpointSerializer,
            PhoneNumberAssignmentSerializer,
            PhoneProviderSettingsAttrs,
            PhoneProviderSettingsSerializer,
        )
        from .tasks import (
            RematchPhoneCallsTask,
            delete_archived_phone_recordings_task,
            sync_phone_calls_task,
        )
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "CrmConfig",
    "PhoneCallJobLinkSerializer",
    "PhoneCallRecord",
    "PhoneCallRecordSerializer",
    "PhoneCallRecording",
    "PhoneCallRecordingSerializer",
    "PhoneEndpoint",
    "PhoneEndpointAttrs",
    "PhoneEndpointSerializer",
    "PhoneNumberAssignmentSerializer",
    "PhoneProviderSettings",
    "PhoneProviderSettingsAttrs",
    "PhoneProviderSettingsSerializer",
    "RematchPhoneCallsTask",
    "delete_archived_phone_recordings_task",
    "sync_phone_calls_task",
]
