# This file is autogenerated by update_init.py script

from .phone_call_views import PhoneCallRecordViewSet, PhoneCallRecordingViewSet

__all__ = [
    "PhoneCallRecordViewSet",
    "PhoneCallRecordingViewSet",
]
