# Generated by Django 6.1.1 on 2026-09-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0008_release_integration_settings"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="IntegrationSettings",
                    fields=[
                        (
                            "id",
                            models.PositiveSmallIntegerField(
                                default=1, editable=False, primary_key=True, serialize=False
                            ),
                        ),
                        (
                            "google_maps_api_key",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        ("phone_provider_enabled", models.BooleanField(default=False)),
                        (
                            "phone_provider_recording_deletion_enabled",
                            models.BooleanField(default=False),
                        ),
                        (
                            "phone_provider_recording_deletion_after_days",
                            models.PositiveSmallIntegerField(default=31),
                        ),
                        (
                            "phone_provider_base_url",
                            models.URLField(blank=True, default=None, null=True),
                        ),
                        ("phone_provider_username", models.TextField(blank=True, null=True)),
                        ("phone_provider_password", models.TextField(blank=True, null=True)),
                        (
                            "phone_provider_account_code",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "verbose_name": "Integration Settings",
                        "verbose_name_plural": "Integration Settings",
                        "db_table": "crm_phoneprovidersettings",
                        "constraints": [
                            models.CheckConstraint(
                                condition=models.Q(("id", 1)),
                                name="core_integrationsettings_singleton",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(("google_maps_api_key", ""), _negated=True),
                                name="core_integrationsettings_google_maps_api_key_not_blank",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(("phone_provider_base_url", ""), _negated=True),
                                name="core_integrationsettings_phone_provider_base_url_not_blank",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(("phone_provider_username", ""), _negated=True),
                                name="core_integrationsettings_phone_provider_username_not_blank",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(("phone_provider_password", ""), _negated=True),
                                name="core_integrationsettings_phone_provider_password_not_blank",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(
                                    ("phone_provider_account_code", ""), _negated=True
                                ),
                                name="core_integrationsettings_phone_provider_account_code_not_blank",
                            ),
                        ],
                    },
                ),
            ],
        ),
    ]
