# Generated by Django 6.1.1 on 2026-09-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0002_transfer_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationsettings",
            name="chatkit_domain_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="integrationsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("chatkit_domain_key", ""), _negated=True),
                name="integrations_chatkit_domain_key_not_blank",
            ),
        ),
    ]
